// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace OpenGL\EGL;

class EGL
{
    public static function eglChooseConfig(int dpy, int attrib_list, int configs, int config_size, int num_config) -> bool
    {
        int r;

        let r = egl_eglchooseconfig(dpy, attrib_list, configs, config_size, num_config);

        return r == 1;
    }

    public static function eglCopyBuffers(int dpy, int surface, int target) -> bool
    {
        int r;

        let r = egl_eglcopybuffers(dpy, surface, target);

        return r == 1;
    }

    public static function eglCreateContext(int dpy, int config, int share_context, int attrib_list) -> int
    {
        return egl_eglcreatecontext(dpy, config, share_context, attrib_list);
    }

    public static function eglCreatePbufferSurface(int dpy, int config, int attrib_list) -> int
    {
        return egl_eglcreatepbuffersurface(dpy, config, attrib_list);
    }

    public static function eglCreatePixmapSurface(int dpy, int config, int pixmap, int attrib_list) -> int
    {
        return egl_eglcreatepixmapsurface(dpy, config, pixmap, attrib_list);
    }

    public static function eglCreateWindowSurface(int dpy, int config, int win, int attrib_list) -> int
    {
        return egl_eglcreatewindowsurface(dpy, config, win, attrib_list);
    }

    public static function eglDestroyContext(int dpy, int ctx) -> bool
    {
        int r;

        let r = egl_egldestroycontext(dpy, ctx);

        return r == 1;
    }

    public static function eglDestroySurface(int dpy, int surface) -> bool
    {
        int r;

        let r = egl_egldestroysurface(dpy, surface);

        return r == 1;
    }

    public static function eglGetConfigAttrib(int dpy, int config, int attribute, int value) -> bool
    {
        int r;

        let r = egl_eglgetconfigattrib(dpy, config, attribute, value);

        return r == 1;
    }

    public static function eglGetConfigs(int dpy, int configs, int config_size, int num_config) -> bool
    {
        int r;

        let r = egl_eglgetconfigs(dpy, configs, config_size, num_config);

        return r == 1;
    }

    public static function eglGetCurrentDisplay() -> int
    {
        return egl_eglgetcurrentdisplay();
    }

    public static function eglGetCurrentSurface(int readdraw) -> int
    {
        return egl_eglgetcurrentsurface(readdraw);
    }

    public static function eglGetDisplay(int display_id) -> int
    {
        return egl_eglgetdisplay(display_id);
    }

    public static function eglGetError() -> int
    {
        return egl_eglgeterror();
    }

    public static function eglGetProcAddress(string procname) -> int
    {
        return egl_eglgetprocaddress(procname);
    }

    public static function eglInitialize(int dpy, int major, int minor) -> bool
    {
        int r;

        let r = egl_eglinitialize(dpy, major, minor);

        return r == 1;
    }

    public static function eglMakeCurrent(int dpy, int draw, int read, int ctx) -> bool
    {
        int r;

        let r = egl_eglmakecurrent(dpy, draw, read, ctx);

        return r == 1;
    }

    public static function eglQueryContext(int dpy, int ctx, int attribute, int value) -> bool
    {
        int r;

        let r = egl_eglquerycontext(dpy, ctx, attribute, value);

        return r == 1;
    }

    public static function eglQueryString(int dpy, int name) -> var
    {
        var result;

        let result = egl_eglquerystring(dpy, name);

        return result;
    }

    public static function eglQuerySurface(int dpy, int surface, int attribute, int value) -> bool
    {
        int r;

        let r = egl_eglquerysurface(dpy, surface, attribute, value);

        return r == 1;
    }

    public static function eglSwapBuffers(int dpy, int surface) -> bool
    {
        int r;

        let r = egl_eglswapbuffers(dpy, surface);

        return r == 1;
    }

    public static function eglTerminate(int dpy) -> bool
    {
        int r;

        let r = egl_eglterminate(dpy);

        return r == 1;
    }

    public static function eglWaitGL() -> bool
    {
        int r;

        let r = egl_eglwaitgl();

        return r == 1;
    }

    public static function eglWaitNative(int engine) -> bool
    {
        int r;

        let r = egl_eglwaitnative(engine);

        return r == 1;
    }

    public static function eglBindTexImage(int dpy, int surface, int buffer) -> bool
    {
        int r;

        let r = egl_eglbindteximage(dpy, surface, buffer);

        return r == 1;
    }

    public static function eglReleaseTexImage(int dpy, int surface, int buffer) -> bool
    {
        int r;

        let r = egl_eglreleaseteximage(dpy, surface, buffer);

        return r == 1;
    }

    public static function eglSurfaceAttrib(int dpy, int surface, int attribute, int value) -> bool
    {
        int r;

        let r = egl_eglsurfaceattrib(dpy, surface, attribute, value);

        return r == 1;
    }

    public static function eglSwapInterval(int dpy, int interval) -> bool
    {
        int r;

        let r = egl_eglswapinterval(dpy, interval);

        return r == 1;
    }

    public static function eglBindAPI(int api) -> bool
    {
        int r;

        let r = egl_eglbindapi(api);

        return r == 1;
    }

    public static function eglQueryAPI() -> int
    {
        return egl_eglqueryapi();
    }

    public static function eglCreatePbufferFromClientBuffer(int dpy, int buftype, int buffer, int config, int attrib_list) -> int
    {
        return egl_eglcreatepbufferfromclientbuffer(dpy, buftype, buffer, config, attrib_list);
    }

    public static function eglReleaseThread() -> bool
    {
        int r;

        let r = egl_eglreleasethread();

        return r == 1;
    }

    public static function eglWaitClient() -> bool
    {
        int r;

        let r = egl_eglwaitclient();

        return r == 1;
    }

    public static function eglGetCurrentContext() -> int
    {
        return egl_eglgetcurrentcontext();
    }

    public static function eglCreateSync(int dpy, int type, int attrib_list) -> int
    {
        return egl_eglcreatesync(dpy, type, attrib_list);
    }

    public static function eglDestroySync(int dpy, int sync) -> bool
    {
        int r;

        let r = egl_egldestroysync(dpy, sync);

        return r == 1;
    }

    public static function eglClientWaitSync(int dpy, int sync, int flags, int timeout) -> int
    {
        return egl_eglclientwaitsync(dpy, sync, flags, timeout);
    }

    public static function eglGetSyncAttrib(int dpy, int sync, int attribute, int value) -> bool
    {
        int r;

        let r = egl_eglgetsyncattrib(dpy, sync, attribute, value);

        return r == 1;
    }

    public static function eglCreateImage(int dpy, int ctx, int target, int buffer, int attrib_list) -> int
    {
        return egl_eglcreateimage(dpy, ctx, target, buffer, attrib_list);
    }

    public static function eglDestroyImage(int dpy, int image) -> bool
    {
        int r;

        let r = egl_egldestroyimage(dpy, image);

        return r == 1;
    }

    public static function eglGetPlatformDisplay(int platform, int native_display, int attrib_list) -> int
    {
        return egl_eglgetplatformdisplay(platform, native_display, attrib_list);
    }

    public static function eglCreatePlatformWindowSurface(int dpy, int config, int native_window, int attrib_list) -> int
    {
        return egl_eglcreateplatformwindowsurface(dpy, config, native_window, attrib_list);
    }

    public static function eglCreatePlatformPixmapSurface(int dpy, int config, int native_pixmap, int attrib_list) -> int
    {
        return egl_eglcreateplatformpixmapsurface(dpy, config, native_pixmap, attrib_list);
    }

    public static function eglWaitSync(int dpy, int sync, int flags) -> bool
    {
        int r;

        let r = egl_eglwaitsync(dpy, sync, flags);

        return r == 1;
    }
}
