// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace OpenGL\GL\GL30;

class GL30
{
    public static function glColorMaski(int index, bool r, bool g, bool b, bool a) -> void
    {
        gl30_glcolormaski(index, r, g, b, a);
    }

    public static function glGetBooleani_v(int target, int index, int data) -> void
    {
        gl30_glgetbooleani_v(target, index, data);
    }

    public static function glGetIntegeri_v(int target, int index, int data) -> void
    {
        gl30_glgetintegeri_v(target, index, data);
    }

    public static function glEnablei(int target, int index) -> void
    {
        gl30_glenablei(target, index);
    }

    public static function glDisablei(int target, int index) -> void
    {
        gl30_gldisablei(target, index);
    }

    public static function glIsEnabledi(int target, int index) -> bool
    {
        int r;

        let r = gl30_glisenabledi(target, index);

        return r == 1;
    }

    public static function glBeginTransformFeedback(int primitiveMode) -> void
    {
        gl30_glbegintransformfeedback(primitiveMode);
    }

    public static function glEndTransformFeedback() -> void
    {
        gl30_glendtransformfeedback();
    }

    public static function glBindBufferRange(int target, int index, int buffer, int offset, int size) -> void
    {
        gl30_glbindbufferrange(target, index, buffer, offset, size);
    }

    public static function glBindBufferBase(int target, int index, int buffer) -> void
    {
        gl30_glbindbufferbase(target, index, buffer);
    }

    public static function glTransformFeedbackVaryings(int program, int count, array varyings, int bufferMode) -> void
    {
        gl30_gltransformfeedbackvaryings(program, count, varyings, bufferMode);
    }

    public static function glGetTransformFeedbackVarying(int program, int index, int bufSize, int length, int size, int type, int name) -> void
    {
        gl30_glgettransformfeedbackvarying(program, index, bufSize, length, size, type, name);
    }

    public static function glClampColor(int target, int clamp) -> void
    {
        gl30_glclampcolor(target, clamp);
    }

    public static function glBeginConditionalRender(int id, int mode) -> void
    {
        gl30_glbeginconditionalrender(id, mode);
    }

    public static function glEndConditionalRender() -> void
    {
        gl30_glendconditionalrender();
    }

    public static function glVertexAttribIPointer(int index, int size, int type, int stride, int pointer) -> void
    {
        gl30_glvertexattribipointer(index, size, type, stride, pointer);
    }

    public static function glGetVertexAttribIiv(int index, int pname, int params) -> void
    {
        gl30_glgetvertexattribiiv(index, pname, params);
    }

    public static function glGetVertexAttribIuiv(int index, int pname, int params) -> void
    {
        gl30_glgetvertexattribiuiv(index, pname, params);
    }

    public static function glVertexAttribI1i(int index, int x) -> void
    {
        gl30_glvertexattribi1i(index, x);
    }

    public static function glVertexAttribI2i(int index, int x, int y) -> void
    {
        gl30_glvertexattribi2i(index, x, y);
    }

    public static function glVertexAttribI3i(int index, int x, int y, int z) -> void
    {
        gl30_glvertexattribi3i(index, x, y, z);
    }

    public static function glVertexAttribI4i(int index, int x, int y, int z, int w) -> void
    {
        gl30_glvertexattribi4i(index, x, y, z, w);
    }

    public static function glVertexAttribI1ui(int index, int x) -> void
    {
        gl30_glvertexattribi1ui(index, x);
    }

    public static function glVertexAttribI2ui(int index, int x, int y) -> void
    {
        gl30_glvertexattribi2ui(index, x, y);
    }

    public static function glVertexAttribI3ui(int index, int x, int y, int z) -> void
    {
        gl30_glvertexattribi3ui(index, x, y, z);
    }

    public static function glVertexAttribI4ui(int index, int x, int y, int z, int w) -> void
    {
        gl30_glvertexattribi4ui(index, x, y, z, w);
    }

    public static function glVertexAttribI1iv(int index, int v) -> void
    {
        gl30_glvertexattribi1iv(index, v);
    }

    public static function glVertexAttribI2iv(int index, int v) -> void
    {
        gl30_glvertexattribi2iv(index, v);
    }

    public static function glVertexAttribI3iv(int index, int v) -> void
    {
        gl30_glvertexattribi3iv(index, v);
    }

    public static function glVertexAttribI4iv(int index, int v) -> void
    {
        gl30_glvertexattribi4iv(index, v);
    }

    public static function glVertexAttribI1uiv(int index, int v) -> void
    {
        gl30_glvertexattribi1uiv(index, v);
    }

    public static function glVertexAttribI2uiv(int index, int v) -> void
    {
        gl30_glvertexattribi2uiv(index, v);
    }

    public static function glVertexAttribI3uiv(int index, int v) -> void
    {
        gl30_glvertexattribi3uiv(index, v);
    }

    public static function glVertexAttribI4uiv(int index, int v) -> void
    {
        gl30_glvertexattribi4uiv(index, v);
    }

    public static function glVertexAttribI4bv(int index, int v) -> void
    {
        gl30_glvertexattribi4bv(index, v);
    }

    public static function glVertexAttribI4sv(int index, int v) -> void
    {
        gl30_glvertexattribi4sv(index, v);
    }

    public static function glVertexAttribI4ubv(int index, int v) -> void
    {
        gl30_glvertexattribi4ubv(index, v);
    }

    public static function glVertexAttribI4usv(int index, int v) -> void
    {
        gl30_glvertexattribi4usv(index, v);
    }

    public static function glGetUniformuiv(int program, int location, int params) -> void
    {
        gl30_glgetuniformuiv(program, location, params);
    }

    public static function glBindFragDataLocation(int program, int color, string name) -> void
    {
        gl30_glbindfragdatalocation(program, color, name);
    }

    public static function glGetFragDataLocation(int program, string name) -> int
    {
        return gl30_glgetfragdatalocation(program, name);
    }

    public static function glUniform1ui(int location, int v0) -> void
    {
        gl30_gluniform1ui(location, v0);
    }

    public static function glUniform2ui(int location, int v0, int v1) -> void
    {
        gl30_gluniform2ui(location, v0, v1);
    }

    public static function glUniform3ui(int location, int v0, int v1, int v2) -> void
    {
        gl30_gluniform3ui(location, v0, v1, v2);
    }

    public static function glUniform4ui(int location, int v0, int v1, int v2, int v3) -> void
    {
        gl30_gluniform4ui(location, v0, v1, v2, v3);
    }

    public static function glUniform1uiv(int location, int count, int value) -> void
    {
        gl30_gluniform1uiv(location, count, value);
    }

    public static function glUniform2uiv(int location, int count, int value) -> void
    {
        gl30_gluniform2uiv(location, count, value);
    }

    public static function glUniform3uiv(int location, int count, int value) -> void
    {
        gl30_gluniform3uiv(location, count, value);
    }

    public static function glUniform4uiv(int location, int count, int value) -> void
    {
        gl30_gluniform4uiv(location, count, value);
    }

    public static function glTexParameterIiv(int target, int pname, int params) -> void
    {
        gl30_gltexparameteriiv(target, pname, params);
    }

    public static function glTexParameterIuiv(int target, int pname, int params) -> void
    {
        gl30_gltexparameteriuiv(target, pname, params);
    }

    public static function glGetTexParameterIiv(int target, int pname, int params) -> void
    {
        gl30_glgettexparameteriiv(target, pname, params);
    }

    public static function glGetTexParameterIuiv(int target, int pname, int params) -> void
    {
        gl30_glgettexparameteriuiv(target, pname, params);
    }

    public static function glClearBufferiv(int buffer, int drawbuffer, int value) -> void
    {
        gl30_glclearbufferiv(buffer, drawbuffer, value);
    }

    public static function glClearBufferuiv(int buffer, int drawbuffer, int value) -> void
    {
        gl30_glclearbufferuiv(buffer, drawbuffer, value);
    }

    public static function glClearBufferfv(int buffer, int drawbuffer, int value) -> void
    {
        gl30_glclearbufferfv(buffer, drawbuffer, value);
    }

    public static function glClearBufferfi(int buffer, int drawbuffer, double depth, int stencil) -> void
    {
        gl30_glclearbufferfi(buffer, drawbuffer, depth, stencil);
    }

    public static function glGetStringi(int name, int index) -> var
    {
        var result;

        let result = gl30_glgetstringi(name, index);

        return result;
    }

    public static function glIsRenderbuffer(int renderbuffer) -> bool
    {
        int r;

        let r = gl30_glisrenderbuffer(renderbuffer);

        return r == 1;
    }

    public static function glBindRenderbuffer(int target, int renderbuffer) -> void
    {
        gl30_glbindrenderbuffer(target, renderbuffer);
    }

    public static function glDeleteRenderbuffers(int n, int renderbuffers) -> void
    {
        gl30_gldeleterenderbuffers(n, renderbuffers);
    }

    public static function glGenRenderbuffers(int n, int renderbuffers) -> void
    {
        gl30_glgenrenderbuffers(n, renderbuffers);
    }

    public static function glRenderbufferStorage(int target, int internalformat, int width, int height) -> void
    {
        gl30_glrenderbufferstorage(target, internalformat, width, height);
    }

    public static function glGetRenderbufferParameteriv(int target, int pname, int params) -> void
    {
        gl30_glgetrenderbufferparameteriv(target, pname, params);
    }

    public static function glIsFramebuffer(int framebuffer) -> bool
    {
        int r;

        let r = gl30_glisframebuffer(framebuffer);

        return r == 1;
    }

    public static function glBindFramebuffer(int target, int framebuffer) -> void
    {
        gl30_glbindframebuffer(target, framebuffer);
    }

    public static function glDeleteFramebuffers(int n, int framebuffers) -> void
    {
        gl30_gldeleteframebuffers(n, framebuffers);
    }

    public static function glGenFramebuffers(int n, int framebuffers) -> void
    {
        gl30_glgenframebuffers(n, framebuffers);
    }

    public static function glCheckFramebufferStatus(int target) -> int
    {
        return gl30_glcheckframebufferstatus(target);
    }

    public static function glFramebufferTexture1D(int target, int attachment, int textarget, int texture, int level) -> void
    {
        gl30_glframebuffertexture1d(target, attachment, textarget, texture, level);
    }

    public static function glFramebufferTexture2D(int target, int attachment, int textarget, int texture, int level) -> void
    {
        gl30_glframebuffertexture2d(target, attachment, textarget, texture, level);
    }

    public static function glFramebufferTexture3D(int target, int attachment, int textarget, int texture, int level, int zoffset) -> void
    {
        gl30_glframebuffertexture3d(target, attachment, textarget, texture, level, zoffset);
    }

    public static function glFramebufferRenderbuffer(int target, int attachment, int renderbuffertarget, int renderbuffer) -> void
    {
        gl30_glframebufferrenderbuffer(target, attachment, renderbuffertarget, renderbuffer);
    }

    public static function glGetFramebufferAttachmentParameteriv(int target, int attachment, int pname, int params) -> void
    {
        gl30_glgetframebufferattachmentparameteriv(target, attachment, pname, params);
    }

    public static function glGenerateMipmap(int target) -> void
    {
        gl30_glgeneratemipmap(target);
    }

    public static function glBlitFramebuffer(int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, int mask, int filter) -> void
    {
        gl30_glblitframebuffer(srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter);
    }

    public static function glRenderbufferStorageMultisample(int target, int samples, int internalformat, int width, int height) -> void
    {
        gl30_glrenderbufferstoragemultisample(target, samples, internalformat, width, height);
    }

    public static function glFramebufferTextureLayer(int target, int attachment, int texture, int level, int layer) -> void
    {
        gl30_glframebuffertexturelayer(target, attachment, texture, level, layer);
    }

    public static function glMapBufferRange(int target, int offset, int length, int access) -> int
    {
        return gl30_glmapbufferrange(target, offset, length, access);
    }

    public static function glFlushMappedBufferRange(int target, int offset, int length) -> void
    {
        gl30_glflushmappedbufferrange(target, offset, length);
    }

    public static function glBindVertexArray(int array_) -> void
    {
        gl30_glbindvertexarray(array_);
    }

    public static function glDeleteVertexArrays(int n, int arrays) -> void
    {
        gl30_gldeletevertexarrays(n, arrays);
    }

    public static function glGenVertexArrays(int n, int arrays) -> void
    {
        gl30_glgenvertexarrays(n, arrays);
    }

    public static function glIsVertexArray(int array_) -> bool
    {
        int r;

        let r = gl30_glisvertexarray(array_);

        return r == 1;
    }
}
