// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace OpenGL\GL\GL15;

class GL15
{
    public static function glGenQueries(int n, int ids) -> void
    {
        gl15_glgenqueries(n, ids);
    }

    public static function glDeleteQueries(int n, int ids) -> void
    {
        gl15_gldeletequeries(n, ids);
    }

    public static function glIsQuery(int id) -> bool
    {
        int r;

        let r = gl15_glisquery(id);

        return r == 1;
    }

    public static function glBeginQuery(int target, int id) -> void
    {
        gl15_glbeginquery(target, id);
    }

    public static function glEndQuery(int target) -> void
    {
        gl15_glendquery(target);
    }

    public static function glGetQueryiv(int target, int pname, int params) -> void
    {
        gl15_glgetqueryiv(target, pname, params);
    }

    public static function glGetQueryObjectiv(int id, int pname, int params) -> void
    {
        gl15_glgetqueryobjectiv(id, pname, params);
    }

    public static function glGetQueryObjectuiv(int id, int pname, int params) -> void
    {
        gl15_glgetqueryobjectuiv(id, pname, params);
    }

    public static function glBindBuffer(int target, int buffer) -> void
    {
        gl15_glbindbuffer(target, buffer);
    }

    public static function glDeleteBuffers(int n, int buffers) -> void
    {
        gl15_gldeletebuffers(n, buffers);
    }

    public static function glGenBuffers(int n, int buffers) -> void
    {
        gl15_glgenbuffers(n, buffers);
    }

    public static function glIsBuffer(int buffer) -> bool
    {
        int r;

        let r = gl15_glisbuffer(buffer);

        return r == 1;
    }

    public static function glBufferData(int target, int size, int data, int usage) -> void
    {
        gl15_glbufferdata(target, size, data, usage);
    }

    public static function glBufferSubData(int target, int offset, int size, int data) -> void
    {
        gl15_glbuffersubdata(target, offset, size, data);
    }

    public static function glGetBufferSubData(int target, int offset, int size, int data) -> void
    {
        gl15_glgetbuffersubdata(target, offset, size, data);
    }

    public static function glMapBuffer(int target, int access) -> int
    {
        return gl15_glmapbuffer(target, access);
    }

    public static function glUnmapBuffer(int target) -> bool
    {
        int r;

        let r = gl15_glunmapbuffer(target);

        return r == 1;
    }

    public static function glGetBufferParameteriv(int target, int pname, int params) -> void
    {
        gl15_glgetbufferparameteriv(target, pname, params);
    }

    public static function glGetBufferPointerv(int target, int pname, int params) -> void
    {
        gl15_glgetbufferpointerv(target, pname, params);
    }
}
