// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace OpenGL\GL\GL12;

class GL12
{
    public static function glDrawRangeElements(int mode, int start, int end, int count, int type, int indices) -> void
    {
        gl12_gldrawrangeelements(mode, start, end, count, type, indices);
    }

    public static function glTexImage3D(int target, int level, int internalformat, int width, int height, int depth, int border, int format, int type, int pixels) -> void
    {
        gl12_glteximage3d(target, level, internalformat, width, height, depth, border, format, type, pixels);
    }

    public static function glTexSubImage3D(int target, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, int pixels) -> void
    {
        gl12_gltexsubimage3d(target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pixels);
    }

    public static function glCopyTexSubImage3D(int target, int level, int xoffset, int yoffset, int zoffset, int x, int y, int width, int height) -> void
    {
        gl12_glcopytexsubimage3d(target, level, xoffset, yoffset, zoffset, x, y, width, height);
    }
}
