// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace OpenGL\GL\GL20;

class GL20
{
    public static function glBlendEquationSeparate(int modeRGB, int modeAlpha) -> void
    {
        gl20_glblendequationseparate(modeRGB, modeAlpha);
    }

    public static function glDrawBuffers(int n, int bufs) -> void
    {
        gl20_gldrawbuffers(n, bufs);
    }

    public static function glStencilOpSeparate(int face, int sfail, int dpfail, int dppass) -> void
    {
        gl20_glstencilopseparate(face, sfail, dpfail, dppass);
    }

    public static function glStencilFuncSeparate(int face, int func, int ref, int mask) -> void
    {
        gl20_glstencilfuncseparate(face, func, ref, mask);
    }

    public static function glStencilMaskSeparate(int face, int mask) -> void
    {
        gl20_glstencilmaskseparate(face, mask);
    }

    public static function glAttachShader(int program, int shader) -> void
    {
        gl20_glattachshader(program, shader);
    }

    public static function glBindAttribLocation(int program, int index, string name) -> void
    {
        gl20_glbindattriblocation(program, index, name);
    }

    public static function glCompileShader(int shader) -> void
    {
        gl20_glcompileshader(shader);
    }

    public static function glCreateProgram() -> int
    {
        return gl20_glcreateprogram();
    }

    public static function glCreateShader(int type) -> int
    {
        return gl20_glcreateshader(type);
    }

    public static function glDeleteProgram(int program) -> void
    {
        gl20_gldeleteprogram(program);
    }

    public static function glDeleteShader(int shader) -> void
    {
        gl20_gldeleteshader(shader);
    }

    public static function glDetachShader(int program, int shader) -> void
    {
        gl20_gldetachshader(program, shader);
    }

    public static function glDisableVertexAttribArray(int index) -> void
    {
        gl20_gldisablevertexattribarray(index);
    }

    public static function glEnableVertexAttribArray(int index) -> void
    {
        gl20_glenablevertexattribarray(index);
    }

    public static function glGetActiveAttrib(int program, int index, int bufSize, int length, int size, int type, int name) -> void
    {
        gl20_glgetactiveattrib(program, index, bufSize, length, size, type, name);
    }

    public static function glGetActiveUniform(int program, int index, int bufSize, int length, int size, int type, int name) -> void
    {
        gl20_glgetactiveuniform(program, index, bufSize, length, size, type, name);
    }

    public static function glGetAttachedShaders(int program, int maxCount, int count, int shaders) -> void
    {
        gl20_glgetattachedshaders(program, maxCount, count, shaders);
    }

    public static function glGetAttribLocation(int program, string name) -> int
    {
        return gl20_glgetattriblocation(program, name);
    }

    public static function glGetProgramiv(int program, int pname, int params) -> void
    {
        gl20_glgetprogramiv(program, pname, params);
    }

    public static function glGetProgramInfoLog(int program, int bufSize, int length, int infoLog) -> void
    {
        gl20_glgetprograminfolog(program, bufSize, length, infoLog);
    }

    public static function glGetShaderiv(int shader, int pname, int params) -> void
    {
        gl20_glgetshaderiv(shader, pname, params);
    }

    public static function glGetShaderInfoLog(int shader, int bufSize, int length, int infoLog) -> void
    {
        gl20_glgetshaderinfolog(shader, bufSize, length, infoLog);
    }

    public static function glGetShaderSource(int shader, int bufSize, int length, int source) -> void
    {
        gl20_glgetshadersource(shader, bufSize, length, source);
    }

    public static function glGetUniformLocation(int program, string name) -> int
    {
        return gl20_glgetuniformlocation(program, name);
    }

    public static function glGetUniformfv(int program, int location, int params) -> void
    {
        gl20_glgetuniformfv(program, location, params);
    }

    public static function glGetUniformiv(int program, int location, int params) -> void
    {
        gl20_glgetuniformiv(program, location, params);
    }

    public static function glGetVertexAttribdv(int index, int pname, int params) -> void
    {
        gl20_glgetvertexattribdv(index, pname, params);
    }

    public static function glGetVertexAttribfv(int index, int pname, int params) -> void
    {
        gl20_glgetvertexattribfv(index, pname, params);
    }

    public static function glGetVertexAttribiv(int index, int pname, int params) -> void
    {
        gl20_glgetvertexattribiv(index, pname, params);
    }

    public static function glGetVertexAttribPointerv(int index, int pname, int pointer) -> void
    {
        gl20_glgetvertexattribpointerv(index, pname, pointer);
    }

    public static function glIsProgram(int program) -> bool
    {
        int r;

        let r = gl20_glisprogram(program);

        return r == 1;
    }

    public static function glIsShader(int shader) -> bool
    {
        int r;

        let r = gl20_glisshader(shader);

        return r == 1;
    }

    public static function glLinkProgram(int program) -> void
    {
        gl20_gllinkprogram(program);
    }

    public static function glShaderSource(int shader, int count, array string_, int length) -> void
    {
        gl20_glshadersource(shader, count, string_, length);
    }

    public static function glUseProgram(int program) -> void
    {
        gl20_gluseprogram(program);
    }

    public static function glUniform1f(int location, double v0) -> void
    {
        gl20_gluniform1f(location, v0);
    }

    public static function glUniform2f(int location, double v0, double v1) -> void
    {
        gl20_gluniform2f(location, v0, v1);
    }

    public static function glUniform3f(int location, double v0, double v1, double v2) -> void
    {
        gl20_gluniform3f(location, v0, v1, v2);
    }

    public static function glUniform4f(int location, double v0, double v1, double v2, double v3) -> void
    {
        gl20_gluniform4f(location, v0, v1, v2, v3);
    }

    public static function glUniform1i(int location, int v0) -> void
    {
        gl20_gluniform1i(location, v0);
    }

    public static function glUniform2i(int location, int v0, int v1) -> void
    {
        gl20_gluniform2i(location, v0, v1);
    }

    public static function glUniform3i(int location, int v0, int v1, int v2) -> void
    {
        gl20_gluniform3i(location, v0, v1, v2);
    }

    public static function glUniform4i(int location, int v0, int v1, int v2, int v3) -> void
    {
        gl20_gluniform4i(location, v0, v1, v2, v3);
    }

    public static function glUniform1fv(int location, int count, int value) -> void
    {
        gl20_gluniform1fv(location, count, value);
    }

    public static function glUniform2fv(int location, int count, int value) -> void
    {
        gl20_gluniform2fv(location, count, value);
    }

    public static function glUniform3fv(int location, int count, int value) -> void
    {
        gl20_gluniform3fv(location, count, value);
    }

    public static function glUniform4fv(int location, int count, int value) -> void
    {
        gl20_gluniform4fv(location, count, value);
    }

    public static function glUniform1iv(int location, int count, int value) -> void
    {
        gl20_gluniform1iv(location, count, value);
    }

    public static function glUniform2iv(int location, int count, int value) -> void
    {
        gl20_gluniform2iv(location, count, value);
    }

    public static function glUniform3iv(int location, int count, int value) -> void
    {
        gl20_gluniform3iv(location, count, value);
    }

    public static function glUniform4iv(int location, int count, int value) -> void
    {
        gl20_gluniform4iv(location, count, value);
    }

    public static function glUniformMatrix2fv(int location, int count, bool transpose, int value) -> void
    {
        gl20_gluniformmatrix2fv(location, count, transpose, value);
    }

    public static function glUniformMatrix3fv(int location, int count, bool transpose, int value) -> void
    {
        gl20_gluniformmatrix3fv(location, count, transpose, value);
    }

    public static function glUniformMatrix4fv(int location, int count, bool transpose, int value) -> void
    {
        gl20_gluniformmatrix4fv(location, count, transpose, value);
    }

    public static function glValidateProgram(int program) -> void
    {
        gl20_glvalidateprogram(program);
    }

    public static function glVertexAttrib1d(int index, double x) -> void
    {
        gl20_glvertexattrib1d(index, x);
    }

    public static function glVertexAttrib1dv(int index, int v) -> void
    {
        gl20_glvertexattrib1dv(index, v);
    }

    public static function glVertexAttrib1f(int index, double x) -> void
    {
        gl20_glvertexattrib1f(index, x);
    }

    public static function glVertexAttrib1fv(int index, int v) -> void
    {
        gl20_glvertexattrib1fv(index, v);
    }

    public static function glVertexAttrib1s(int index, int x) -> void
    {
        gl20_glvertexattrib1s(index, x);
    }

    public static function glVertexAttrib1sv(int index, int v) -> void
    {
        gl20_glvertexattrib1sv(index, v);
    }

    public static function glVertexAttrib2d(int index, double x, double y) -> void
    {
        gl20_glvertexattrib2d(index, x, y);
    }

    public static function glVertexAttrib2dv(int index, int v) -> void
    {
        gl20_glvertexattrib2dv(index, v);
    }

    public static function glVertexAttrib2f(int index, double x, double y) -> void
    {
        gl20_glvertexattrib2f(index, x, y);
    }

    public static function glVertexAttrib2fv(int index, int v) -> void
    {
        gl20_glvertexattrib2fv(index, v);
    }

    public static function glVertexAttrib2s(int index, int x, int y) -> void
    {
        gl20_glvertexattrib2s(index, x, y);
    }

    public static function glVertexAttrib2sv(int index, int v) -> void
    {
        gl20_glvertexattrib2sv(index, v);
    }

    public static function glVertexAttrib3d(int index, double x, double y, double z) -> void
    {
        gl20_glvertexattrib3d(index, x, y, z);
    }

    public static function glVertexAttrib3dv(int index, int v) -> void
    {
        gl20_glvertexattrib3dv(index, v);
    }

    public static function glVertexAttrib3f(int index, double x, double y, double z) -> void
    {
        gl20_glvertexattrib3f(index, x, y, z);
    }

    public static function glVertexAttrib3fv(int index, int v) -> void
    {
        gl20_glvertexattrib3fv(index, v);
    }

    public static function glVertexAttrib3s(int index, int x, int y, int z) -> void
    {
        gl20_glvertexattrib3s(index, x, y, z);
    }

    public static function glVertexAttrib3sv(int index, int v) -> void
    {
        gl20_glvertexattrib3sv(index, v);
    }

    public static function glVertexAttrib4Nbv(int index, int v) -> void
    {
        gl20_glvertexattrib4nbv(index, v);
    }

    public static function glVertexAttrib4Niv(int index, int v) -> void
    {
        gl20_glvertexattrib4niv(index, v);
    }

    public static function glVertexAttrib4Nsv(int index, int v) -> void
    {
        gl20_glvertexattrib4nsv(index, v);
    }

    public static function glVertexAttrib4Nub(int index, int x, int y, int z, int w) -> void
    {
        gl20_glvertexattrib4nub(index, x, y, z, w);
    }

    public static function glVertexAttrib4Nubv(int index, int v) -> void
    {
        gl20_glvertexattrib4nubv(index, v);
    }

    public static function glVertexAttrib4Nuiv(int index, int v) -> void
    {
        gl20_glvertexattrib4nuiv(index, v);
    }

    public static function glVertexAttrib4Nusv(int index, int v) -> void
    {
        gl20_glvertexattrib4nusv(index, v);
    }

    public static function glVertexAttrib4bv(int index, int v) -> void
    {
        gl20_glvertexattrib4bv(index, v);
    }

    public static function glVertexAttrib4d(int index, double x, double y, double z, double w) -> void
    {
        gl20_glvertexattrib4d(index, x, y, z, w);
    }

    public static function glVertexAttrib4dv(int index, int v) -> void
    {
        gl20_glvertexattrib4dv(index, v);
    }

    public static function glVertexAttrib4f(int index, double x, double y, double z, double w) -> void
    {
        gl20_glvertexattrib4f(index, x, y, z, w);
    }

    public static function glVertexAttrib4fv(int index, int v) -> void
    {
        gl20_glvertexattrib4fv(index, v);
    }

    public static function glVertexAttrib4iv(int index, int v) -> void
    {
        gl20_glvertexattrib4iv(index, v);
    }

    public static function glVertexAttrib4s(int index, int x, int y, int z, int w) -> void
    {
        gl20_glvertexattrib4s(index, x, y, z, w);
    }

    public static function glVertexAttrib4sv(int index, int v) -> void
    {
        gl20_glvertexattrib4sv(index, v);
    }

    public static function glVertexAttrib4ubv(int index, int v) -> void
    {
        gl20_glvertexattrib4ubv(index, v);
    }

    public static function glVertexAttrib4uiv(int index, int v) -> void
    {
        gl20_glvertexattrib4uiv(index, v);
    }

    public static function glVertexAttrib4usv(int index, int v) -> void
    {
        gl20_glvertexattrib4usv(index, v);
    }

    public static function glVertexAttribPointer(int index, int size, int type, bool normalized, int stride, int pointer) -> void
    {
        gl20_glvertexattribpointer(index, size, type, normalized, stride, pointer);
    }
}
