// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace OpenGL\Bridge;

class Bridge
{
    public static function load() -> bool
    {
        int r;

        let r = bridge_load();

        return r == 1;
    }

    public static function isAvailable(string name) -> bool
    {
        int r;

        let r = bridge_is_available(name);

        return r == 1;
    }

    public static function procAddress(string name) -> int
    {
        return bridge_proc_address(name);
    }

    public static function contextVersion() -> array
    {
        var result;

        let result = bridge_context_version();

        return result;
    }

    public static function alloc(int size) -> int
    {
        return bridge_alloc(size);
    }

    public static function free(int ptr) -> void
    {
        bridge_free(ptr);
    }

    public static function write(int ptr, int offset, string bytes) -> bool
    {
        int r;

        let r = bridge_write(ptr, offset, bytes);

        return r == 1;
    }

    public static function read(int ptr, int offset, int length) -> var
    {
        var result;

        let result = bridge_read(ptr, offset, length);

        return result;
    }
}
