// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace OpenGL\GL\GL11;

class GL11
{
    public static function glDrawArrays(int mode, int first, int count) -> void
    {
        gl11_gldrawarrays(mode, first, count);
    }

    public static function glDrawElements(int mode, int count, int type, int indices) -> void
    {
        gl11_gldrawelements(mode, count, type, indices);
    }

    public static function glGetPointerv(int pname, int params) -> void
    {
        gl11_glgetpointerv(pname, params);
    }

    public static function glPolygonOffset(double factor, double units) -> void
    {
        gl11_glpolygonoffset(factor, units);
    }

    public static function glCopyTexImage1D(int target, int level, int internalformat, int x, int y, int width, int border) -> void
    {
        gl11_glcopyteximage1d(target, level, internalformat, x, y, width, border);
    }

    public static function glCopyTexImage2D(int target, int level, int internalformat, int x, int y, int width, int height, int border) -> void
    {
        gl11_glcopyteximage2d(target, level, internalformat, x, y, width, height, border);
    }

    public static function glCopyTexSubImage1D(int target, int level, int xoffset, int x, int y, int width) -> void
    {
        gl11_glcopytexsubimage1d(target, level, xoffset, x, y, width);
    }

    public static function glCopyTexSubImage2D(int target, int level, int xoffset, int yoffset, int x, int y, int width, int height) -> void
    {
        gl11_glcopytexsubimage2d(target, level, xoffset, yoffset, x, y, width, height);
    }

    public static function glTexSubImage1D(int target, int level, int xoffset, int width, int format, int type, int pixels) -> void
    {
        gl11_gltexsubimage1d(target, level, xoffset, width, format, type, pixels);
    }

    public static function glTexSubImage2D(int target, int level, int xoffset, int yoffset, int width, int height, int format, int type, int pixels) -> void
    {
        gl11_gltexsubimage2d(target, level, xoffset, yoffset, width, height, format, type, pixels);
    }

    public static function glBindTexture(int target, int texture) -> void
    {
        gl11_glbindtexture(target, texture);
    }

    public static function glDeleteTextures(int n, int textures) -> void
    {
        gl11_gldeletetextures(n, textures);
    }

    public static function glGenTextures(int n, int textures) -> void
    {
        gl11_glgentextures(n, textures);
    }

    public static function glIsTexture(int texture) -> bool
    {
        int r;

        let r = gl11_glistexture(texture);

        return r == 1;
    }
}
