// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace OpenGL\GL\GL21;

class GL21
{
    public static function glUniformMatrix2x3fv(int location, int count, bool transpose, int value) -> void
    {
        gl21_gluniformmatrix2x3fv(location, count, transpose, value);
    }

    public static function glUniformMatrix3x2fv(int location, int count, bool transpose, int value) -> void
    {
        gl21_gluniformmatrix3x2fv(location, count, transpose, value);
    }

    public static function glUniformMatrix2x4fv(int location, int count, bool transpose, int value) -> void
    {
        gl21_gluniformmatrix2x4fv(location, count, transpose, value);
    }

    public static function glUniformMatrix4x2fv(int location, int count, bool transpose, int value) -> void
    {
        gl21_gluniformmatrix4x2fv(location, count, transpose, value);
    }

    public static function glUniformMatrix3x4fv(int location, int count, bool transpose, int value) -> void
    {
        gl21_gluniformmatrix3x4fv(location, count, transpose, value);
    }

    public static function glUniformMatrix4x3fv(int location, int count, bool transpose, int value) -> void
    {
        gl21_gluniformmatrix4x3fv(location, count, transpose, value);
    }
}
