/*
 * cgl.h — OpenGL\CGL\CGL bound 1:1.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: OpenGL.framework/Headers/{OpenGL.h,CGLCurrent.h,CGLTypes.h,CGLContext.h,CGLDevice.h,CGLIOSurface.h} (52 prototypes)
 */

#ifndef PHPGL_CGL_H
#define PHPGL_CGL_H

#include <php.h>

/*@audit block CGL\CGL OpenGL.h 47 */
/*@audit block CGL\CGL CGLCurrent.h 2 */
/*@audit block CGL\CGL CGLTypes.h 0 */
/*@audit block CGL\CGL CGLContext.h 0 */
/*@audit block CGL\CGL CGLDevice.h 2 */
/*@audit block CGL\CGL CGLIOSurface.h 1 */

/*@zep CGL\CGL CGLChoosePixelFormat(int attribs, int pix, int npix) -> int */
zend_long phpgl_cgl_cglchoosepixelformat(zval *attribs, zval *pix, zval *npix);

/*@zep CGL\CGL CGLDestroyPixelFormat(int pix) -> int */
zend_long phpgl_cgl_cgldestroypixelformat(zval *pix);

/*@zep CGL\CGL CGLDescribePixelFormat(int pix, int pix_num, int attrib, int value) -> int */
zend_long phpgl_cgl_cgldescribepixelformat(zval *pix, zval *pix_num, zval *attrib, zval *value);

/*@zep CGL\CGL CGLReleasePixelFormat(int pix) -> void */
void phpgl_cgl_cglreleasepixelformat(zval *pix);

/*@zep CGL\CGL CGLRetainPixelFormat(int pix) -> int */
zend_long phpgl_cgl_cglretainpixelformat(zval *pix);

/*@zep CGL\CGL CGLGetPixelFormatRetainCount(int pix) -> int */
zend_long phpgl_cgl_cglgetpixelformatretaincount(zval *pix);

/*@zep CGL\CGL CGLQueryRendererInfo(int display_mask, int rend, int nrend) -> int */
zend_long phpgl_cgl_cglqueryrendererinfo(zval *display_mask, zval *rend, zval *nrend);

/*@zep CGL\CGL CGLDestroyRendererInfo(int rend) -> int */
zend_long phpgl_cgl_cgldestroyrendererinfo(zval *rend);

/*@zep CGL\CGL CGLDescribeRenderer(int rend, int rend_num, int prop, int value) -> int */
zend_long phpgl_cgl_cgldescriberenderer(zval *rend, zval *rend_num, zval *prop, zval *value);

/*@zep CGL\CGL CGLCreateContext(int pix, int share, int ctx) -> int */
zend_long phpgl_cgl_cglcreatecontext(zval *pix, zval *share, zval *ctx);

/*@zep CGL\CGL CGLDestroyContext(int ctx) -> int */
zend_long phpgl_cgl_cgldestroycontext(zval *ctx);

/*@zep CGL\CGL CGLCopyContext(int src, int dst, int mask) -> int */
zend_long phpgl_cgl_cglcopycontext(zval *src, zval *dst, zval *mask);

/*@zep CGL\CGL CGLRetainContext(int ctx) -> int */
zend_long phpgl_cgl_cglretaincontext(zval *ctx);

/*@zep CGL\CGL CGLReleaseContext(int ctx) -> void */
void phpgl_cgl_cglreleasecontext(zval *ctx);

/*@zep CGL\CGL CGLGetContextRetainCount(int ctx) -> int */
zend_long phpgl_cgl_cglgetcontextretaincount(zval *ctx);

/*@zep CGL\CGL CGLGetPixelFormat(int ctx) -> int */
zend_long phpgl_cgl_cglgetpixelformat(zval *ctx);

/*@zep CGL\CGL CGLCreatePBuffer(int width, int height, int target, int internalFormat, int max_level, int pbuffer) -> int */
zend_long phpgl_cgl_cglcreatepbuffer(zval *width, zval *height, zval *target, zval *internalFormat, zval *max_level, zval *pbuffer);

/*@zep CGL\CGL CGLDestroyPBuffer(int pbuffer) -> int */
zend_long phpgl_cgl_cgldestroypbuffer(zval *pbuffer);

/*@zep CGL\CGL CGLDescribePBuffer(int obj, int width, int height, int target, int internalFormat, int mipmap) -> int */
zend_long phpgl_cgl_cgldescribepbuffer(zval *obj, zval *width, zval *height, zval *target, zval *internalFormat, zval *mipmap);

/*@zep CGL\CGL CGLTexImagePBuffer(int ctx, int pbuffer, int source) -> int */
zend_long phpgl_cgl_cglteximagepbuffer(zval *ctx, zval *pbuffer, zval *source);

/*@zep CGL\CGL CGLRetainPBuffer(int pbuffer) -> int */
zend_long phpgl_cgl_cglretainpbuffer(zval *pbuffer);

/*@zep CGL\CGL CGLReleasePBuffer(int pbuffer) -> void */
void phpgl_cgl_cglreleasepbuffer(zval *pbuffer);

/*@zep CGL\CGL CGLGetPBufferRetainCount(int pbuffer) -> int */
zend_long phpgl_cgl_cglgetpbufferretaincount(zval *pbuffer);

/*@zep CGL\CGL CGLSetOffScreen(int ctx, int width, int height, int rowbytes, int baseaddr) -> int */
zend_long phpgl_cgl_cglsetoffscreen(zval *ctx, zval *width, zval *height, zval *rowbytes, zval *baseaddr);

/*@zep CGL\CGL CGLGetOffScreen(int ctx, int width, int height, int rowbytes, int baseaddr) -> int */
zend_long phpgl_cgl_cglgetoffscreen(zval *ctx, zval *width, zval *height, zval *rowbytes, zval *baseaddr);

/*@zep CGL\CGL CGLSetFullScreen(int ctx) -> int */
zend_long phpgl_cgl_cglsetfullscreen(zval *ctx);

/*@zep CGL\CGL CGLSetFullScreenOnDisplay(int ctx, int display_mask) -> int */
zend_long phpgl_cgl_cglsetfullscreenondisplay(zval *ctx, zval *display_mask);

/*@zep CGL\CGL CGLSetPBuffer(int ctx, int pbuffer, int face, int level, int screen) -> int */
zend_long phpgl_cgl_cglsetpbuffer(zval *ctx, zval *pbuffer, zval *face, zval *level, zval *screen);

/*@zep CGL\CGL CGLGetPBuffer(int ctx, int pbuffer, int face, int level, int screen) -> int */
zend_long phpgl_cgl_cglgetpbuffer(zval *ctx, zval *pbuffer, zval *face, zval *level, zval *screen);

/*@zep CGL\CGL CGLClearDrawable(int ctx) -> int */
zend_long phpgl_cgl_cglcleardrawable(zval *ctx);

/*@zep CGL\CGL CGLFlushDrawable(int ctx) -> int */
zend_long phpgl_cgl_cglflushdrawable(zval *ctx);

/*@zep CGL\CGL CGLEnable(int ctx, int pname) -> int */
zend_long phpgl_cgl_cglenable(zval *ctx, zval *pname);

/*@zep CGL\CGL CGLDisable(int ctx, int pname) -> int */
zend_long phpgl_cgl_cgldisable(zval *ctx, zval *pname);

/*@zep CGL\CGL CGLIsEnabled(int ctx, int pname, int enable) -> int */
zend_long phpgl_cgl_cglisenabled(zval *ctx, zval *pname, zval *enable);

/*@zep CGL\CGL CGLSetParameter(int ctx, int pname, int params) -> int */
zend_long phpgl_cgl_cglsetparameter(zval *ctx, zval *pname, zval *params);

/*@zep CGL\CGL CGLGetParameter(int ctx, int pname, int params) -> int */
zend_long phpgl_cgl_cglgetparameter(zval *ctx, zval *pname, zval *params);

/*@zep CGL\CGL CGLSetVirtualScreen(int ctx, int screen) -> int */
zend_long phpgl_cgl_cglsetvirtualscreen(zval *ctx, zval *screen);

/*@zep CGL\CGL CGLGetVirtualScreen(int ctx, int screen) -> int */
zend_long phpgl_cgl_cglgetvirtualscreen(zval *ctx, zval *screen);

/*@zep CGL\CGL CGLUpdateContext(int ctx) -> int */
zend_long phpgl_cgl_cglupdatecontext(zval *ctx);

/*@zep CGL\CGL CGLSetGlobalOption(int pname, int params) -> int */
zend_long phpgl_cgl_cglsetglobaloption(zval *pname, zval *params);

/*@zep CGL\CGL CGLGetGlobalOption(int pname, int params) -> int */
zend_long phpgl_cgl_cglgetglobaloption(zval *pname, zval *params);

/*@zep CGL\CGL CGLSetOption(int pname, int param) -> int */
zend_long phpgl_cgl_cglsetoption(zval *pname, zval *param);

/*@zep CGL\CGL CGLGetOption(int pname, int param) -> int */
zend_long phpgl_cgl_cglgetoption(zval *pname, zval *param);

/*@zep CGL\CGL CGLLockContext(int ctx) -> int */
zend_long phpgl_cgl_cgllockcontext(zval *ctx);

/*@zep CGL\CGL CGLUnlockContext(int ctx) -> int */
zend_long phpgl_cgl_cglunlockcontext(zval *ctx);

/*@zep CGL\CGL CGLGetVersion(int majorvers, int minorvers) -> void */
void phpgl_cgl_cglgetversion(zval *majorvers, zval *minorvers);

/*@zep CGL\CGL CGLErrorString(int error) -> var */
void phpgl_cgl_cglerrorstring(zval *return_value, zval *error);

/*@zep CGL\CGL CGLSetCurrentContext(int ctx) -> int */
zend_long phpgl_cgl_cglsetcurrentcontext(zval *ctx);

/*@zep CGL\CGL CGLGetCurrentContext() -> int */
zend_long phpgl_cgl_cglgetcurrentcontext(void);

/*@zep CGL\CGL CGLGetShareGroup(int ctx) -> int */
zend_long phpgl_cgl_cglgetsharegroup(zval *ctx);

/*@reserved CGL\CGL cl_device_id CGLGetDeviceFromGLRenderer(GLint rendererID) — cl_device_id belongs to OpenCL, which this binding does not include */

/*@reserved CGL\CGL CGLError CGLTexImageIOSurface2D(CGLContextObj ctx, GLenum target, GLenum internal_format, GLsizei width, GLsizei height, GLenum format, GLenum type, IOSurfaceRef ioSurface, GLuint plane) — IOSurfaceRef belongs to IOSurface.framework, which this binding does not include */

#endif
