/*
 * egl.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/egl.h, EGL_VERSION_1_0 .. EGL_VERSION_1_5 (44 prototypes)
 */

#include "egl.h"
#include "egl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

zend_long phpgl_egl_eglchooseconfig(zval *dpy, zval *attrib_list, zval *configs, zval *config_size, zval *num_config)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglChooseConfig fn = (PHPGL_PFN_eglChooseConfig) phpgl_entry("eglChooseConfig", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (const EGLint *) phpgl_arg_ptr(attrib_list), (EGLConfig *) phpgl_arg_ptr(configs), (EGLint) phpgl_arg_long(config_size), (EGLint *) phpgl_arg_ptr(num_config)) ? 1 : 0;
}

zend_long phpgl_egl_eglcopybuffers(zval *dpy, zval *surface, zval *target)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglCopyBuffers fn = (PHPGL_PFN_eglCopyBuffers) phpgl_entry("eglCopyBuffers", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLSurface) phpgl_arg_ptr(surface), (EGLNativePixmapType) phpgl_arg_ptr(target)) ? 1 : 0;
}

zend_long phpgl_egl_eglcreatecontext(zval *dpy, zval *config, zval *share_context, zval *attrib_list)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglCreateContext fn = (PHPGL_PFN_eglCreateContext) phpgl_entry("eglCreateContext", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLConfig) phpgl_arg_ptr(config), (EGLContext) phpgl_arg_ptr(share_context), (const EGLint *) phpgl_arg_ptr(attrib_list));
}

zend_long phpgl_egl_eglcreatepbuffersurface(zval *dpy, zval *config, zval *attrib_list)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglCreatePbufferSurface fn = (PHPGL_PFN_eglCreatePbufferSurface) phpgl_entry("eglCreatePbufferSurface", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLConfig) phpgl_arg_ptr(config), (const EGLint *) phpgl_arg_ptr(attrib_list));
}

zend_long phpgl_egl_eglcreatepixmapsurface(zval *dpy, zval *config, zval *pixmap, zval *attrib_list)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglCreatePixmapSurface fn = (PHPGL_PFN_eglCreatePixmapSurface) phpgl_entry("eglCreatePixmapSurface", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLConfig) phpgl_arg_ptr(config), (EGLNativePixmapType) phpgl_arg_ptr(pixmap), (const EGLint *) phpgl_arg_ptr(attrib_list));
}

zend_long phpgl_egl_eglcreatewindowsurface(zval *dpy, zval *config, zval *win, zval *attrib_list)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglCreateWindowSurface fn = (PHPGL_PFN_eglCreateWindowSurface) phpgl_entry("eglCreateWindowSurface", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLConfig) phpgl_arg_ptr(config), (EGLNativeWindowType) phpgl_arg_ptr(win), (const EGLint *) phpgl_arg_ptr(attrib_list));
}

zend_long phpgl_egl_egldestroycontext(zval *dpy, zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglDestroyContext fn = (PHPGL_PFN_eglDestroyContext) phpgl_entry("eglDestroyContext", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLContext) phpgl_arg_ptr(ctx)) ? 1 : 0;
}

zend_long phpgl_egl_egldestroysurface(zval *dpy, zval *surface)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglDestroySurface fn = (PHPGL_PFN_eglDestroySurface) phpgl_entry("eglDestroySurface", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLSurface) phpgl_arg_ptr(surface)) ? 1 : 0;
}

zend_long phpgl_egl_eglgetconfigattrib(zval *dpy, zval *config, zval *attribute, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglGetConfigAttrib fn = (PHPGL_PFN_eglGetConfigAttrib) phpgl_entry("eglGetConfigAttrib", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLConfig) phpgl_arg_ptr(config), (EGLint) phpgl_arg_long(attribute), (EGLint *) phpgl_arg_ptr(value)) ? 1 : 0;
}

zend_long phpgl_egl_eglgetconfigs(zval *dpy, zval *configs, zval *config_size, zval *num_config)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglGetConfigs fn = (PHPGL_PFN_eglGetConfigs) phpgl_entry("eglGetConfigs", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLConfig *) phpgl_arg_ptr(configs), (EGLint) phpgl_arg_long(config_size), (EGLint *) phpgl_arg_ptr(num_config)) ? 1 : 0;
}

zend_long phpgl_egl_eglgetcurrentdisplay(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglGetCurrentDisplay fn = (PHPGL_PFN_eglGetCurrentDisplay) phpgl_entry("eglGetCurrentDisplay", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn();
}

zend_long phpgl_egl_eglgetcurrentsurface(zval *readdraw)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglGetCurrentSurface fn = (PHPGL_PFN_eglGetCurrentSurface) phpgl_entry("eglGetCurrentSurface", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((EGLint) phpgl_arg_long(readdraw));
}

zend_long phpgl_egl_eglgetdisplay(zval *display_id)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglGetDisplay fn = (PHPGL_PFN_eglGetDisplay) phpgl_entry("eglGetDisplay", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((EGLNativeDisplayType) phpgl_arg_ptr(display_id));
}

zend_long phpgl_egl_eglgeterror(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglGetError fn = (PHPGL_PFN_eglGetError) phpgl_entry("eglGetError", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn();
}

zend_long phpgl_egl_eglgetprocaddress(zval *procname)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglGetProcAddress fn = (PHPGL_PFN_eglGetProcAddress) phpgl_entry("eglGetProcAddress", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((const char *) phpgl_arg_string(procname));
}

zend_long phpgl_egl_eglinitialize(zval *dpy, zval *major, zval *minor)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglInitialize fn = (PHPGL_PFN_eglInitialize) phpgl_entry("eglInitialize", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLint *) phpgl_arg_ptr(major), (EGLint *) phpgl_arg_ptr(minor)) ? 1 : 0;
}

zend_long phpgl_egl_eglmakecurrent(zval *dpy, zval *draw, zval *read, zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglMakeCurrent fn = (PHPGL_PFN_eglMakeCurrent) phpgl_entry("eglMakeCurrent", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLSurface) phpgl_arg_ptr(draw), (EGLSurface) phpgl_arg_ptr(read), (EGLContext) phpgl_arg_ptr(ctx)) ? 1 : 0;
}

zend_long phpgl_egl_eglquerycontext(zval *dpy, zval *ctx, zval *attribute, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglQueryContext fn = (PHPGL_PFN_eglQueryContext) phpgl_entry("eglQueryContext", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLContext) phpgl_arg_ptr(ctx), (EGLint) phpgl_arg_long(attribute), (EGLint *) phpgl_arg_ptr(value)) ? 1 : 0;
}

void phpgl_egl_eglquerystring(zval *return_value, zval *dpy, zval *name)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglQueryString fn = (PHPGL_PFN_eglQueryString) phpgl_entry("eglQueryString", &slot, 0, 0);

    if (!fn) {
        ZVAL_NULL(return_value);

        return;
    }

    phpgl_ret_string(return_value, fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLint) phpgl_arg_long(name)));
}

zend_long phpgl_egl_eglquerysurface(zval *dpy, zval *surface, zval *attribute, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglQuerySurface fn = (PHPGL_PFN_eglQuerySurface) phpgl_entry("eglQuerySurface", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLSurface) phpgl_arg_ptr(surface), (EGLint) phpgl_arg_long(attribute), (EGLint *) phpgl_arg_ptr(value)) ? 1 : 0;
}

zend_long phpgl_egl_eglswapbuffers(zval *dpy, zval *surface)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglSwapBuffers fn = (PHPGL_PFN_eglSwapBuffers) phpgl_entry("eglSwapBuffers", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLSurface) phpgl_arg_ptr(surface)) ? 1 : 0;
}

zend_long phpgl_egl_eglterminate(zval *dpy)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglTerminate fn = (PHPGL_PFN_eglTerminate) phpgl_entry("eglTerminate", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy)) ? 1 : 0;
}

zend_long phpgl_egl_eglwaitgl(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglWaitGL fn = (PHPGL_PFN_eglWaitGL) phpgl_entry("eglWaitGL", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn() ? 1 : 0;
}

zend_long phpgl_egl_eglwaitnative(zval *engine)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglWaitNative fn = (PHPGL_PFN_eglWaitNative) phpgl_entry("eglWaitNative", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLint) phpgl_arg_long(engine)) ? 1 : 0;
}

zend_long phpgl_egl_eglbindteximage(zval *dpy, zval *surface, zval *buffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglBindTexImage fn = (PHPGL_PFN_eglBindTexImage) phpgl_entry("eglBindTexImage", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLSurface) phpgl_arg_ptr(surface), (EGLint) phpgl_arg_long(buffer)) ? 1 : 0;
}

zend_long phpgl_egl_eglreleaseteximage(zval *dpy, zval *surface, zval *buffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglReleaseTexImage fn = (PHPGL_PFN_eglReleaseTexImage) phpgl_entry("eglReleaseTexImage", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLSurface) phpgl_arg_ptr(surface), (EGLint) phpgl_arg_long(buffer)) ? 1 : 0;
}

zend_long phpgl_egl_eglsurfaceattrib(zval *dpy, zval *surface, zval *attribute, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglSurfaceAttrib fn = (PHPGL_PFN_eglSurfaceAttrib) phpgl_entry("eglSurfaceAttrib", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLSurface) phpgl_arg_ptr(surface), (EGLint) phpgl_arg_long(attribute), (EGLint) phpgl_arg_long(value)) ? 1 : 0;
}

zend_long phpgl_egl_eglswapinterval(zval *dpy, zval *interval)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglSwapInterval fn = (PHPGL_PFN_eglSwapInterval) phpgl_entry("eglSwapInterval", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLint) phpgl_arg_long(interval)) ? 1 : 0;
}

zend_long phpgl_egl_eglbindapi(zval *api)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglBindAPI fn = (PHPGL_PFN_eglBindAPI) phpgl_entry("eglBindAPI", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLenum) phpgl_arg_long(api)) ? 1 : 0;
}

zend_long phpgl_egl_eglqueryapi(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglQueryAPI fn = (PHPGL_PFN_eglQueryAPI) phpgl_entry("eglQueryAPI", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn();
}

zend_long phpgl_egl_eglcreatepbufferfromclientbuffer(zval *dpy, zval *buftype, zval *buffer, zval *config, zval *attrib_list)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglCreatePbufferFromClientBuffer fn = (PHPGL_PFN_eglCreatePbufferFromClientBuffer) phpgl_entry("eglCreatePbufferFromClientBuffer", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLenum) phpgl_arg_long(buftype), (EGLClientBuffer) phpgl_arg_ptr(buffer), (EGLConfig) phpgl_arg_ptr(config), (const EGLint *) phpgl_arg_ptr(attrib_list));
}

zend_long phpgl_egl_eglreleasethread(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglReleaseThread fn = (PHPGL_PFN_eglReleaseThread) phpgl_entry("eglReleaseThread", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn() ? 1 : 0;
}

zend_long phpgl_egl_eglwaitclient(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglWaitClient fn = (PHPGL_PFN_eglWaitClient) phpgl_entry("eglWaitClient", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn() ? 1 : 0;
}

zend_long phpgl_egl_eglgetcurrentcontext(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglGetCurrentContext fn = (PHPGL_PFN_eglGetCurrentContext) phpgl_entry("eglGetCurrentContext", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn();
}

zend_long phpgl_egl_eglcreatesync(zval *dpy, zval *type, zval *attrib_list)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglCreateSync fn = (PHPGL_PFN_eglCreateSync) phpgl_entry("eglCreateSync", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLenum) phpgl_arg_long(type), (const EGLAttrib *) phpgl_arg_ptr(attrib_list));
}

zend_long phpgl_egl_egldestroysync(zval *dpy, zval *sync)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglDestroySync fn = (PHPGL_PFN_eglDestroySync) phpgl_entry("eglDestroySync", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLSync) phpgl_arg_ptr(sync)) ? 1 : 0;
}

zend_long phpgl_egl_eglclientwaitsync(zval *dpy, zval *sync, zval *flags, zval *timeout)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglClientWaitSync fn = (PHPGL_PFN_eglClientWaitSync) phpgl_entry("eglClientWaitSync", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLSync) phpgl_arg_ptr(sync), (EGLint) phpgl_arg_long(flags), (EGLTime) phpgl_arg_long(timeout));
}

zend_long phpgl_egl_eglgetsyncattrib(zval *dpy, zval *sync, zval *attribute, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglGetSyncAttrib fn = (PHPGL_PFN_eglGetSyncAttrib) phpgl_entry("eglGetSyncAttrib", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLSync) phpgl_arg_ptr(sync), (EGLint) phpgl_arg_long(attribute), (EGLAttrib *) phpgl_arg_ptr(value)) ? 1 : 0;
}

zend_long phpgl_egl_eglcreateimage(zval *dpy, zval *ctx, zval *target, zval *buffer, zval *attrib_list)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglCreateImage fn = (PHPGL_PFN_eglCreateImage) phpgl_entry("eglCreateImage", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLContext) phpgl_arg_ptr(ctx), (EGLenum) phpgl_arg_long(target), (EGLClientBuffer) phpgl_arg_ptr(buffer), (const EGLAttrib *) phpgl_arg_ptr(attrib_list));
}

zend_long phpgl_egl_egldestroyimage(zval *dpy, zval *image)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglDestroyImage fn = (PHPGL_PFN_eglDestroyImage) phpgl_entry("eglDestroyImage", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLImage) phpgl_arg_ptr(image)) ? 1 : 0;
}

zend_long phpgl_egl_eglgetplatformdisplay(zval *platform, zval *native_display, zval *attrib_list)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglGetPlatformDisplay fn = (PHPGL_PFN_eglGetPlatformDisplay) phpgl_entry("eglGetPlatformDisplay", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((EGLenum) phpgl_arg_long(platform), (void *) phpgl_arg_ptr(native_display), (const EGLAttrib *) phpgl_arg_ptr(attrib_list));
}

zend_long phpgl_egl_eglcreateplatformwindowsurface(zval *dpy, zval *config, zval *native_window, zval *attrib_list)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglCreatePlatformWindowSurface fn = (PHPGL_PFN_eglCreatePlatformWindowSurface) phpgl_entry("eglCreatePlatformWindowSurface", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLConfig) phpgl_arg_ptr(config), (void *) phpgl_arg_ptr(native_window), (const EGLAttrib *) phpgl_arg_ptr(attrib_list));
}

zend_long phpgl_egl_eglcreateplatformpixmapsurface(zval *dpy, zval *config, zval *native_pixmap, zval *attrib_list)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglCreatePlatformPixmapSurface fn = (PHPGL_PFN_eglCreatePlatformPixmapSurface) phpgl_entry("eglCreatePlatformPixmapSurface", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLConfig) phpgl_arg_ptr(config), (void *) phpgl_arg_ptr(native_pixmap), (const EGLAttrib *) phpgl_arg_ptr(attrib_list));
}

zend_long phpgl_egl_eglwaitsync(zval *dpy, zval *sync, zval *flags)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_eglWaitSync fn = (PHPGL_PFN_eglWaitSync) phpgl_entry("eglWaitSync", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return fn((EGLDisplay) phpgl_arg_ptr(dpy), (EGLSync) phpgl_arg_ptr(sync), (EGLint) phpgl_arg_long(flags)) ? 1 : 0;
}

