/*
 * gl-11.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_1_1 (14 prototypes)
 */

#include "gl-11.h"
#include "gl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

void phpgl_gl11_gldrawarrays(zval *mode, zval *first, zval *count)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDRAWARRAYSPROC fn = (PFNGLDRAWARRAYSPROC) phpgl_entry("glDrawArrays", &slot, 1, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (GLint) phpgl_arg_long(first), (GLsizei) phpgl_arg_long(count));
}

void phpgl_gl11_gldrawelements(zval *mode, zval *count, zval *type, zval *indices)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDRAWELEMENTSPROC fn = (PFNGLDRAWELEMENTSPROC) phpgl_entry("glDrawElements", &slot, 1, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (GLsizei) phpgl_arg_long(count), (GLenum) phpgl_arg_long(type), (const void *) phpgl_arg_ptr(indices));
}

void phpgl_gl11_glgetpointerv(zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETPOINTERVPROC fn = (PFNGLGETPOINTERVPROC) phpgl_entry("glGetPointerv", &slot, 1, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (void * *) phpgl_arg_ptr(params));
}

void phpgl_gl11_glpolygonoffset(zval *factor, zval *units)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPOLYGONOFFSETPROC fn = (PFNGLPOLYGONOFFSETPROC) phpgl_entry("glPolygonOffset", &slot, 1, 1);

    if (!fn) {
        return;
    }

    fn((GLfloat) phpgl_arg_double(factor), (GLfloat) phpgl_arg_double(units));
}

void phpgl_gl11_glcopyteximage1d(zval *target, zval *level, zval *internalformat, zval *x, zval *y, zval *width, zval *border)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOPYTEXIMAGE1DPROC fn = (PFNGLCOPYTEXIMAGE1DPROC) phpgl_entry("glCopyTexImage1D", &slot, 1, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLenum) phpgl_arg_long(internalformat), (GLint) phpgl_arg_long(x), (GLint) phpgl_arg_long(y), (GLsizei) phpgl_arg_long(width), (GLint) phpgl_arg_long(border));
}

void phpgl_gl11_glcopyteximage2d(zval *target, zval *level, zval *internalformat, zval *x, zval *y, zval *width, zval *height, zval *border)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOPYTEXIMAGE2DPROC fn = (PFNGLCOPYTEXIMAGE2DPROC) phpgl_entry("glCopyTexImage2D", &slot, 1, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLenum) phpgl_arg_long(internalformat), (GLint) phpgl_arg_long(x), (GLint) phpgl_arg_long(y), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height), (GLint) phpgl_arg_long(border));
}

void phpgl_gl11_glcopytexsubimage1d(zval *target, zval *level, zval *xoffset, zval *x, zval *y, zval *width)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOPYTEXSUBIMAGE1DPROC fn = (PFNGLCOPYTEXSUBIMAGE1DPROC) phpgl_entry("glCopyTexSubImage1D", &slot, 1, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(xoffset), (GLint) phpgl_arg_long(x), (GLint) phpgl_arg_long(y), (GLsizei) phpgl_arg_long(width));
}

void phpgl_gl11_glcopytexsubimage2d(zval *target, zval *level, zval *xoffset, zval *yoffset, zval *x, zval *y, zval *width, zval *height)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOPYTEXSUBIMAGE2DPROC fn = (PFNGLCOPYTEXSUBIMAGE2DPROC) phpgl_entry("glCopyTexSubImage2D", &slot, 1, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(xoffset), (GLint) phpgl_arg_long(yoffset), (GLint) phpgl_arg_long(x), (GLint) phpgl_arg_long(y), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height));
}

void phpgl_gl11_gltexsubimage1d(zval *target, zval *level, zval *xoffset, zval *width, zval *format, zval *type, zval *pixels)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXSUBIMAGE1DPROC fn = (PFNGLTEXSUBIMAGE1DPROC) phpgl_entry("glTexSubImage1D", &slot, 1, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(xoffset), (GLsizei) phpgl_arg_long(width), (GLenum) phpgl_arg_long(format), (GLenum) phpgl_arg_long(type), (const void *) phpgl_arg_ptr(pixels));
}

void phpgl_gl11_gltexsubimage2d(zval *target, zval *level, zval *xoffset, zval *yoffset, zval *width, zval *height, zval *format, zval *type, zval *pixels)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXSUBIMAGE2DPROC fn = (PFNGLTEXSUBIMAGE2DPROC) phpgl_entry("glTexSubImage2D", &slot, 1, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(xoffset), (GLint) phpgl_arg_long(yoffset), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height), (GLenum) phpgl_arg_long(format), (GLenum) phpgl_arg_long(type), (const void *) phpgl_arg_ptr(pixels));
}

void phpgl_gl11_glbindtexture(zval *target, zval *texture)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBINDTEXTUREPROC fn = (PFNGLBINDTEXTUREPROC) phpgl_entry("glBindTexture", &slot, 1, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(texture));
}

void phpgl_gl11_gldeletetextures(zval *n, zval *textures)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDELETETEXTURESPROC fn = (PFNGLDELETETEXTURESPROC) phpgl_entry("glDeleteTextures", &slot, 1, 1);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (const GLuint *) phpgl_arg_ptr(textures));
}

void phpgl_gl11_glgentextures(zval *n, zval *textures)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGENTEXTURESPROC fn = (PFNGLGENTEXTURESPROC) phpgl_entry("glGenTextures", &slot, 1, 1);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (GLuint *) phpgl_arg_ptr(textures));
}

zend_long phpgl_gl11_glistexture(zval *texture)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLISTEXTUREPROC fn = (PFNGLISTEXTUREPROC) phpgl_entry("glIsTexture", &slot, 1, 1);

    if (!fn) {
        return 0;
    }

    return fn((GLuint) phpgl_arg_long(texture)) ? 1 : 0;
}

