/*
 * gl-15.h — OpenGL\GL\GL15 bound 1:1.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_1_5 (19 prototypes)
 */

#ifndef PHPGL_GL_15_H
#define PHPGL_GL_15_H

#include <php.h>

/*@audit block GL\GL15 GL_VERSION_1_5 19 */

/*@zep GL\GL15 glGenQueries(int n, int ids) -> void */
void phpgl_gl15_glgenqueries(zval *n, zval *ids);

/*@zep GL\GL15 glDeleteQueries(int n, int ids) -> void */
void phpgl_gl15_gldeletequeries(zval *n, zval *ids);

/*@zep GL\GL15 glIsQuery(int id) -> bool */
zend_long phpgl_gl15_glisquery(zval *id);

/*@zep GL\GL15 glBeginQuery(int target, int id) -> void */
void phpgl_gl15_glbeginquery(zval *target, zval *id);

/*@zep GL\GL15 glEndQuery(int target) -> void */
void phpgl_gl15_glendquery(zval *target);

/*@zep GL\GL15 glGetQueryiv(int target, int pname, int params) -> void */
void phpgl_gl15_glgetqueryiv(zval *target, zval *pname, zval *params);

/*@zep GL\GL15 glGetQueryObjectiv(int id, int pname, int params) -> void */
void phpgl_gl15_glgetqueryobjectiv(zval *id, zval *pname, zval *params);

/*@zep GL\GL15 glGetQueryObjectuiv(int id, int pname, int params) -> void */
void phpgl_gl15_glgetqueryobjectuiv(zval *id, zval *pname, zval *params);

/*@zep GL\GL15 glBindBuffer(int target, int buffer) -> void */
void phpgl_gl15_glbindbuffer(zval *target, zval *buffer);

/*@zep GL\GL15 glDeleteBuffers(int n, int buffers) -> void */
void phpgl_gl15_gldeletebuffers(zval *n, zval *buffers);

/*@zep GL\GL15 glGenBuffers(int n, int buffers) -> void */
void phpgl_gl15_glgenbuffers(zval *n, zval *buffers);

/*@zep GL\GL15 glIsBuffer(int buffer) -> bool */
zend_long phpgl_gl15_glisbuffer(zval *buffer);

/*@zep GL\GL15 glBufferData(int target, int size, int data, int usage) -> void */
void phpgl_gl15_glbufferdata(zval *target, zval *size, zval *data, zval *usage);

/*@zep GL\GL15 glBufferSubData(int target, int offset, int size, int data) -> void */
void phpgl_gl15_glbuffersubdata(zval *target, zval *offset, zval *size, zval *data);

/*@zep GL\GL15 glGetBufferSubData(int target, int offset, int size, int data) -> void */
void phpgl_gl15_glgetbuffersubdata(zval *target, zval *offset, zval *size, zval *data);

/*@zep GL\GL15 glMapBuffer(int target, int access) -> int */
zend_long phpgl_gl15_glmapbuffer(zval *target, zval *access);

/*@zep GL\GL15 glUnmapBuffer(int target) -> bool */
zend_long phpgl_gl15_glunmapbuffer(zval *target);

/*@zep GL\GL15 glGetBufferParameteriv(int target, int pname, int params) -> void */
void phpgl_gl15_glgetbufferparameteriv(zval *target, zval *pname, zval *params);

/*@zep GL\GL15 glGetBufferPointerv(int target, int pname, int params) -> void */
void phpgl_gl15_glgetbufferpointerv(zval *target, zval *pname, zval *params);

#endif
