/*
 * gl-14.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_1_4 (9 prototypes)
 */

#include "gl-14.h"
#include "gl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

void phpgl_gl14_glblendfuncseparate(zval *sfactorRGB, zval *dfactorRGB, zval *sfactorAlpha, zval *dfactorAlpha)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBLENDFUNCSEPARATEPROC fn = (PFNGLBLENDFUNCSEPARATEPROC) phpgl_entry("glBlendFuncSeparate", &slot, 1, 4);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(sfactorRGB), (GLenum) phpgl_arg_long(dfactorRGB), (GLenum) phpgl_arg_long(sfactorAlpha), (GLenum) phpgl_arg_long(dfactorAlpha));
}

void phpgl_gl14_glmultidrawarrays(zval *mode, zval *first, zval *count, zval *drawcount)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLMULTIDRAWARRAYSPROC fn = (PFNGLMULTIDRAWARRAYSPROC) phpgl_entry("glMultiDrawArrays", &slot, 1, 4);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (const GLint *) phpgl_arg_ptr(first), (const GLsizei *) phpgl_arg_ptr(count), (GLsizei) phpgl_arg_long(drawcount));
}

void phpgl_gl14_glmultidrawelements(zval *mode, zval *count, zval *type, zval *indices, zval *drawcount)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLMULTIDRAWELEMENTSPROC fn = (PFNGLMULTIDRAWELEMENTSPROC) phpgl_entry("glMultiDrawElements", &slot, 1, 4);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (const GLsizei *) phpgl_arg_ptr(count), (GLenum) phpgl_arg_long(type), (const void *const *) phpgl_arg_ptr(indices), (GLsizei) phpgl_arg_long(drawcount));
}

void phpgl_gl14_glpointparameterf(zval *pname, zval *param)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPOINTPARAMETERFPROC fn = (PFNGLPOINTPARAMETERFPROC) phpgl_entry("glPointParameterf", &slot, 1, 4);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (GLfloat) phpgl_arg_double(param));
}

void phpgl_gl14_glpointparameterfv(zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPOINTPARAMETERFVPROC fn = (PFNGLPOINTPARAMETERFVPROC) phpgl_entry("glPointParameterfv", &slot, 1, 4);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (const GLfloat *) phpgl_arg_ptr(params));
}

void phpgl_gl14_glpointparameteri(zval *pname, zval *param)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPOINTPARAMETERIPROC fn = (PFNGLPOINTPARAMETERIPROC) phpgl_entry("glPointParameteri", &slot, 1, 4);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (GLint) phpgl_arg_long(param));
}

void phpgl_gl14_glpointparameteriv(zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPOINTPARAMETERIVPROC fn = (PFNGLPOINTPARAMETERIVPROC) phpgl_entry("glPointParameteriv", &slot, 1, 4);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (const GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl14_glblendcolor(zval *red, zval *green, zval *blue, zval *alpha)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBLENDCOLORPROC fn = (PFNGLBLENDCOLORPROC) phpgl_entry("glBlendColor", &slot, 1, 4);

    if (!fn) {
        return;
    }

    fn((GLfloat) phpgl_arg_double(red), (GLfloat) phpgl_arg_double(green), (GLfloat) phpgl_arg_double(blue), (GLfloat) phpgl_arg_double(alpha));
}

void phpgl_gl14_glblendequation(zval *mode)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBLENDEQUATIONPROC fn = (PFNGLBLENDEQUATIONPROC) phpgl_entry("glBlendEquation", &slot, 1, 4);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode));
}

