/*
 * gl-13.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_1_3 (9 prototypes)
 */

#include "gl-13.h"
#include "gl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

void phpgl_gl13_glactivetexture(zval *texture)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLACTIVETEXTUREPROC fn = (PFNGLACTIVETEXTUREPROC) phpgl_entry("glActiveTexture", &slot, 1, 3);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(texture));
}

void phpgl_gl13_glsamplecoverage(zval *value, zval *invert)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLSAMPLECOVERAGEPROC fn = (PFNGLSAMPLECOVERAGEPROC) phpgl_entry("glSampleCoverage", &slot, 1, 3);

    if (!fn) {
        return;
    }

    fn((GLfloat) phpgl_arg_double(value), (GLboolean) phpgl_arg_bool(invert));
}

void phpgl_gl13_glcompressedteximage3d(zval *target, zval *level, zval *internalformat, zval *width, zval *height, zval *depth, zval *border, zval *imageSize, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOMPRESSEDTEXIMAGE3DPROC fn = (PFNGLCOMPRESSEDTEXIMAGE3DPROC) phpgl_entry("glCompressedTexImage3D", &slot, 1, 3);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLenum) phpgl_arg_long(internalformat), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height), (GLsizei) phpgl_arg_long(depth), (GLint) phpgl_arg_long(border), (GLsizei) phpgl_arg_long(imageSize), (const void *) phpgl_arg_ptr(data));
}

void phpgl_gl13_glcompressedteximage2d(zval *target, zval *level, zval *internalformat, zval *width, zval *height, zval *border, zval *imageSize, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOMPRESSEDTEXIMAGE2DPROC fn = (PFNGLCOMPRESSEDTEXIMAGE2DPROC) phpgl_entry("glCompressedTexImage2D", &slot, 1, 3);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLenum) phpgl_arg_long(internalformat), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height), (GLint) phpgl_arg_long(border), (GLsizei) phpgl_arg_long(imageSize), (const void *) phpgl_arg_ptr(data));
}

void phpgl_gl13_glcompressedteximage1d(zval *target, zval *level, zval *internalformat, zval *width, zval *border, zval *imageSize, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOMPRESSEDTEXIMAGE1DPROC fn = (PFNGLCOMPRESSEDTEXIMAGE1DPROC) phpgl_entry("glCompressedTexImage1D", &slot, 1, 3);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLenum) phpgl_arg_long(internalformat), (GLsizei) phpgl_arg_long(width), (GLint) phpgl_arg_long(border), (GLsizei) phpgl_arg_long(imageSize), (const void *) phpgl_arg_ptr(data));
}

void phpgl_gl13_glcompressedtexsubimage3d(zval *target, zval *level, zval *xoffset, zval *yoffset, zval *zoffset, zval *width, zval *height, zval *depth, zval *format, zval *imageSize, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC fn = (PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC) phpgl_entry("glCompressedTexSubImage3D", &slot, 1, 3);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(xoffset), (GLint) phpgl_arg_long(yoffset), (GLint) phpgl_arg_long(zoffset), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height), (GLsizei) phpgl_arg_long(depth), (GLenum) phpgl_arg_long(format), (GLsizei) phpgl_arg_long(imageSize), (const void *) phpgl_arg_ptr(data));
}

void phpgl_gl13_glcompressedtexsubimage2d(zval *target, zval *level, zval *xoffset, zval *yoffset, zval *width, zval *height, zval *format, zval *imageSize, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC fn = (PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC) phpgl_entry("glCompressedTexSubImage2D", &slot, 1, 3);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(xoffset), (GLint) phpgl_arg_long(yoffset), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height), (GLenum) phpgl_arg_long(format), (GLsizei) phpgl_arg_long(imageSize), (const void *) phpgl_arg_ptr(data));
}

void phpgl_gl13_glcompressedtexsubimage1d(zval *target, zval *level, zval *xoffset, zval *width, zval *format, zval *imageSize, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC fn = (PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC) phpgl_entry("glCompressedTexSubImage1D", &slot, 1, 3);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(xoffset), (GLsizei) phpgl_arg_long(width), (GLenum) phpgl_arg_long(format), (GLsizei) phpgl_arg_long(imageSize), (const void *) phpgl_arg_ptr(data));
}

void phpgl_gl13_glgetcompressedteximage(zval *target, zval *level, zval *img)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETCOMPRESSEDTEXIMAGEPROC fn = (PFNGLGETCOMPRESSEDTEXIMAGEPROC) phpgl_entry("glGetCompressedTexImage", &slot, 1, 3);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (void *) phpgl_arg_ptr(img));
}

