/*
 * gl-10.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_1_0 (48 prototypes)
 */

#include "gl-10.h"
#include "gl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

void phpgl_gl10_glcullface(zval *mode)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCULLFACEPROC fn = (PFNGLCULLFACEPROC) phpgl_entry("glCullFace", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode));
}

void phpgl_gl10_glfrontface(zval *mode)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLFRONTFACEPROC fn = (PFNGLFRONTFACEPROC) phpgl_entry("glFrontFace", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode));
}

void phpgl_gl10_glhint(zval *target, zval *mode)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLHINTPROC fn = (PFNGLHINTPROC) phpgl_entry("glHint", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(mode));
}

void phpgl_gl10_gllinewidth(zval *width)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLLINEWIDTHPROC fn = (PFNGLLINEWIDTHPROC) phpgl_entry("glLineWidth", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLfloat) phpgl_arg_double(width));
}

void phpgl_gl10_glpointsize(zval *size)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPOINTSIZEPROC fn = (PFNGLPOINTSIZEPROC) phpgl_entry("glPointSize", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLfloat) phpgl_arg_double(size));
}

void phpgl_gl10_glpolygonmode(zval *face, zval *mode)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPOLYGONMODEPROC fn = (PFNGLPOLYGONMODEPROC) phpgl_entry("glPolygonMode", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(face), (GLenum) phpgl_arg_long(mode));
}

void phpgl_gl10_glscissor(zval *x, zval *y, zval *width, zval *height)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLSCISSORPROC fn = (PFNGLSCISSORPROC) phpgl_entry("glScissor", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(x), (GLint) phpgl_arg_long(y), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height));
}

void phpgl_gl10_gltexparameterf(zval *target, zval *pname, zval *param)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXPARAMETERFPROC fn = (PFNGLTEXPARAMETERFPROC) phpgl_entry("glTexParameterf", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (GLfloat) phpgl_arg_double(param));
}

void phpgl_gl10_gltexparameterfv(zval *target, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXPARAMETERFVPROC fn = (PFNGLTEXPARAMETERFVPROC) phpgl_entry("glTexParameterfv", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (const GLfloat *) phpgl_arg_ptr(params));
}

void phpgl_gl10_gltexparameteri(zval *target, zval *pname, zval *param)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXPARAMETERIPROC fn = (PFNGLTEXPARAMETERIPROC) phpgl_entry("glTexParameteri", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (GLint) phpgl_arg_long(param));
}

void phpgl_gl10_gltexparameteriv(zval *target, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXPARAMETERIVPROC fn = (PFNGLTEXPARAMETERIVPROC) phpgl_entry("glTexParameteriv", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (const GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl10_glteximage1d(zval *target, zval *level, zval *internalformat, zval *width, zval *border, zval *format, zval *type, zval *pixels)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXIMAGE1DPROC fn = (PFNGLTEXIMAGE1DPROC) phpgl_entry("glTexImage1D", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(internalformat), (GLsizei) phpgl_arg_long(width), (GLint) phpgl_arg_long(border), (GLenum) phpgl_arg_long(format), (GLenum) phpgl_arg_long(type), (const void *) phpgl_arg_ptr(pixels));
}

void phpgl_gl10_glteximage2d(zval *target, zval *level, zval *internalformat, zval *width, zval *height, zval *border, zval *format, zval *type, zval *pixels)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXIMAGE2DPROC fn = (PFNGLTEXIMAGE2DPROC) phpgl_entry("glTexImage2D", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(internalformat), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height), (GLint) phpgl_arg_long(border), (GLenum) phpgl_arg_long(format), (GLenum) phpgl_arg_long(type), (const void *) phpgl_arg_ptr(pixels));
}

void phpgl_gl10_gldrawbuffer(zval *buf)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDRAWBUFFERPROC fn = (PFNGLDRAWBUFFERPROC) phpgl_entry("glDrawBuffer", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(buf));
}

void phpgl_gl10_glclear(zval *mask)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCLEARPROC fn = (PFNGLCLEARPROC) phpgl_entry("glClear", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLbitfield) phpgl_arg_long(mask));
}

void phpgl_gl10_glclearcolor(zval *red, zval *green, zval *blue, zval *alpha)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCLEARCOLORPROC fn = (PFNGLCLEARCOLORPROC) phpgl_entry("glClearColor", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLfloat) phpgl_arg_double(red), (GLfloat) phpgl_arg_double(green), (GLfloat) phpgl_arg_double(blue), (GLfloat) phpgl_arg_double(alpha));
}

void phpgl_gl10_glclearstencil(zval *s)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCLEARSTENCILPROC fn = (PFNGLCLEARSTENCILPROC) phpgl_entry("glClearStencil", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(s));
}

void phpgl_gl10_glcleardepth(zval *depth)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCLEARDEPTHPROC fn = (PFNGLCLEARDEPTHPROC) phpgl_entry("glClearDepth", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLdouble) phpgl_arg_double(depth));
}

void phpgl_gl10_glstencilmask(zval *mask)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLSTENCILMASKPROC fn = (PFNGLSTENCILMASKPROC) phpgl_entry("glStencilMask", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(mask));
}

void phpgl_gl10_glcolormask(zval *red, zval *green, zval *blue, zval *alpha)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOLORMASKPROC fn = (PFNGLCOLORMASKPROC) phpgl_entry("glColorMask", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLboolean) phpgl_arg_bool(red), (GLboolean) phpgl_arg_bool(green), (GLboolean) phpgl_arg_bool(blue), (GLboolean) phpgl_arg_bool(alpha));
}

void phpgl_gl10_gldepthmask(zval *flag)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDEPTHMASKPROC fn = (PFNGLDEPTHMASKPROC) phpgl_entry("glDepthMask", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLboolean) phpgl_arg_bool(flag));
}

void phpgl_gl10_gldisable(zval *cap)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDISABLEPROC fn = (PFNGLDISABLEPROC) phpgl_entry("glDisable", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(cap));
}

void phpgl_gl10_glenable(zval *cap)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLENABLEPROC fn = (PFNGLENABLEPROC) phpgl_entry("glEnable", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(cap));
}

void phpgl_gl10_glfinish(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLFINISHPROC fn = (PFNGLFINISHPROC) phpgl_entry("glFinish", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn();
}

void phpgl_gl10_glflush(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLFLUSHPROC fn = (PFNGLFLUSHPROC) phpgl_entry("glFlush", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn();
}

void phpgl_gl10_glblendfunc(zval *sfactor, zval *dfactor)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBLENDFUNCPROC fn = (PFNGLBLENDFUNCPROC) phpgl_entry("glBlendFunc", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(sfactor), (GLenum) phpgl_arg_long(dfactor));
}

void phpgl_gl10_gllogicop(zval *opcode)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLLOGICOPPROC fn = (PFNGLLOGICOPPROC) phpgl_entry("glLogicOp", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(opcode));
}

void phpgl_gl10_glstencilfunc(zval *func, zval *ref, zval *mask)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLSTENCILFUNCPROC fn = (PFNGLSTENCILFUNCPROC) phpgl_entry("glStencilFunc", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(func), (GLint) phpgl_arg_long(ref), (GLuint) phpgl_arg_long(mask));
}

void phpgl_gl10_glstencilop(zval *fail, zval *zfail, zval *zpass)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLSTENCILOPPROC fn = (PFNGLSTENCILOPPROC) phpgl_entry("glStencilOp", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(fail), (GLenum) phpgl_arg_long(zfail), (GLenum) phpgl_arg_long(zpass));
}

void phpgl_gl10_gldepthfunc(zval *func)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDEPTHFUNCPROC fn = (PFNGLDEPTHFUNCPROC) phpgl_entry("glDepthFunc", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(func));
}

void phpgl_gl10_glpixelstoref(zval *pname, zval *param)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPIXELSTOREFPROC fn = (PFNGLPIXELSTOREFPROC) phpgl_entry("glPixelStoref", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (GLfloat) phpgl_arg_double(param));
}

void phpgl_gl10_glpixelstorei(zval *pname, zval *param)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPIXELSTOREIPROC fn = (PFNGLPIXELSTOREIPROC) phpgl_entry("glPixelStorei", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (GLint) phpgl_arg_long(param));
}

void phpgl_gl10_glreadbuffer(zval *src)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLREADBUFFERPROC fn = (PFNGLREADBUFFERPROC) phpgl_entry("glReadBuffer", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(src));
}

void phpgl_gl10_glreadpixels(zval *x, zval *y, zval *width, zval *height, zval *format, zval *type, zval *pixels)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLREADPIXELSPROC fn = (PFNGLREADPIXELSPROC) phpgl_entry("glReadPixels", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(x), (GLint) phpgl_arg_long(y), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height), (GLenum) phpgl_arg_long(format), (GLenum) phpgl_arg_long(type), (void *) phpgl_arg_ptr(pixels));
}

void phpgl_gl10_glgetbooleanv(zval *pname, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETBOOLEANVPROC fn = (PFNGLGETBOOLEANVPROC) phpgl_entry("glGetBooleanv", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (GLboolean *) phpgl_arg_ptr(data));
}

void phpgl_gl10_glgetdoublev(zval *pname, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETDOUBLEVPROC fn = (PFNGLGETDOUBLEVPROC) phpgl_entry("glGetDoublev", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (GLdouble *) phpgl_arg_ptr(data));
}

zend_long phpgl_gl10_glgeterror(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETERRORPROC fn = (PFNGLGETERRORPROC) phpgl_entry("glGetError", &slot, 1, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn();
}

void phpgl_gl10_glgetfloatv(zval *pname, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETFLOATVPROC fn = (PFNGLGETFLOATVPROC) phpgl_entry("glGetFloatv", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (GLfloat *) phpgl_arg_ptr(data));
}

void phpgl_gl10_glgetintegerv(zval *pname, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETINTEGERVPROC fn = (PFNGLGETINTEGERVPROC) phpgl_entry("glGetIntegerv", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(data));
}

void phpgl_gl10_glgetstring(zval *return_value, zval *name)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETSTRINGPROC fn = (PFNGLGETSTRINGPROC) phpgl_entry("glGetString", &slot, 1, 0);

    if (!fn) {
        ZVAL_NULL(return_value);

        return;
    }

    phpgl_ret_ubytes(return_value, fn((GLenum) phpgl_arg_long(name)));
}

void phpgl_gl10_glgetteximage(zval *target, zval *level, zval *format, zval *type, zval *pixels)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETTEXIMAGEPROC fn = (PFNGLGETTEXIMAGEPROC) phpgl_entry("glGetTexImage", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLenum) phpgl_arg_long(format), (GLenum) phpgl_arg_long(type), (void *) phpgl_arg_ptr(pixels));
}

void phpgl_gl10_glgettexparameterfv(zval *target, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETTEXPARAMETERFVPROC fn = (PFNGLGETTEXPARAMETERFVPROC) phpgl_entry("glGetTexParameterfv", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (GLfloat *) phpgl_arg_ptr(params));
}

void phpgl_gl10_glgettexparameteriv(zval *target, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETTEXPARAMETERIVPROC fn = (PFNGLGETTEXPARAMETERIVPROC) phpgl_entry("glGetTexParameteriv", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl10_glgettexlevelparameterfv(zval *target, zval *level, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETTEXLEVELPARAMETERFVPROC fn = (PFNGLGETTEXLEVELPARAMETERFVPROC) phpgl_entry("glGetTexLevelParameterfv", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLenum) phpgl_arg_long(pname), (GLfloat *) phpgl_arg_ptr(params));
}

void phpgl_gl10_glgettexlevelparameteriv(zval *target, zval *level, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETTEXLEVELPARAMETERIVPROC fn = (PFNGLGETTEXLEVELPARAMETERIVPROC) phpgl_entry("glGetTexLevelParameteriv", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

zend_long phpgl_gl10_glisenabled(zval *cap)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLISENABLEDPROC fn = (PFNGLISENABLEDPROC) phpgl_entry("glIsEnabled", &slot, 1, 0);

    if (!fn) {
        return 0;
    }

    return fn((GLenum) phpgl_arg_long(cap)) ? 1 : 0;
}

void phpgl_gl10_gldepthrange(zval *n, zval *f)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDEPTHRANGEPROC fn = (PFNGLDEPTHRANGEPROC) phpgl_entry("glDepthRange", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLdouble) phpgl_arg_double(n), (GLdouble) phpgl_arg_double(f));
}

void phpgl_gl10_glviewport(zval *x, zval *y, zval *width, zval *height)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVIEWPORTPROC fn = (PFNGLVIEWPORTPROC) phpgl_entry("glViewport", &slot, 1, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(x), (GLint) phpgl_arg_long(y), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height));
}

