/*
 * gl-11.h — OpenGL\GL\GL11 bound 1:1.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_1_1 (14 prototypes)
 */

#ifndef PHPGL_GL_11_H
#define PHPGL_GL_11_H

#include <php.h>

/*@audit block GL\GL11 GL_VERSION_1_1 14 */

/*@zep GL\GL11 glDrawArrays(int mode, int first, int count) -> void */
void phpgl_gl11_gldrawarrays(zval *mode, zval *first, zval *count);

/*@zep GL\GL11 glDrawElements(int mode, int count, int type, int indices) -> void */
void phpgl_gl11_gldrawelements(zval *mode, zval *count, zval *type, zval *indices);

/*@zep GL\GL11 glGetPointerv(int pname, int params) -> void */
void phpgl_gl11_glgetpointerv(zval *pname, zval *params);

/*@zep GL\GL11 glPolygonOffset(double factor, double units) -> void */
void phpgl_gl11_glpolygonoffset(zval *factor, zval *units);

/*@zep GL\GL11 glCopyTexImage1D(int target, int level, int internalformat, int x, int y, int width, int border) -> void */
void phpgl_gl11_glcopyteximage1d(zval *target, zval *level, zval *internalformat, zval *x, zval *y, zval *width, zval *border);

/*@zep GL\GL11 glCopyTexImage2D(int target, int level, int internalformat, int x, int y, int width, int height, int border) -> void */
void phpgl_gl11_glcopyteximage2d(zval *target, zval *level, zval *internalformat, zval *x, zval *y, zval *width, zval *height, zval *border);

/*@zep GL\GL11 glCopyTexSubImage1D(int target, int level, int xoffset, int x, int y, int width) -> void */
void phpgl_gl11_glcopytexsubimage1d(zval *target, zval *level, zval *xoffset, zval *x, zval *y, zval *width);

/*@zep GL\GL11 glCopyTexSubImage2D(int target, int level, int xoffset, int yoffset, int x, int y, int width, int height) -> void */
void phpgl_gl11_glcopytexsubimage2d(zval *target, zval *level, zval *xoffset, zval *yoffset, zval *x, zval *y, zval *width, zval *height);

/*@zep GL\GL11 glTexSubImage1D(int target, int level, int xoffset, int width, int format, int type, int pixels) -> void */
void phpgl_gl11_gltexsubimage1d(zval *target, zval *level, zval *xoffset, zval *width, zval *format, zval *type, zval *pixels);

/*@zep GL\GL11 glTexSubImage2D(int target, int level, int xoffset, int yoffset, int width, int height, int format, int type, int pixels) -> void */
void phpgl_gl11_gltexsubimage2d(zval *target, zval *level, zval *xoffset, zval *yoffset, zval *width, zval *height, zval *format, zval *type, zval *pixels);

/*@zep GL\GL11 glBindTexture(int target, int texture) -> void */
void phpgl_gl11_glbindtexture(zval *target, zval *texture);

/*@zep GL\GL11 glDeleteTextures(int n, int textures) -> void */
void phpgl_gl11_gldeletetextures(zval *n, zval *textures);

/*@zep GL\GL11 glGenTextures(int n, int textures) -> void */
void phpgl_gl11_glgentextures(zval *n, zval *textures);

/*@zep GL\GL11 glIsTexture(int texture) -> bool */
zend_long phpgl_gl11_glistexture(zval *texture);

#endif
