/*
 * gl-12.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_1_2 (4 prototypes)
 */

#include "gl-12.h"
#include "gl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

void phpgl_gl12_gldrawrangeelements(zval *mode, zval *start, zval *end, zval *count, zval *type, zval *indices)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDRAWRANGEELEMENTSPROC fn = (PFNGLDRAWRANGEELEMENTSPROC) phpgl_entry("glDrawRangeElements", &slot, 1, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (GLuint) phpgl_arg_long(start), (GLuint) phpgl_arg_long(end), (GLsizei) phpgl_arg_long(count), (GLenum) phpgl_arg_long(type), (const void *) phpgl_arg_ptr(indices));
}

void phpgl_gl12_glteximage3d(zval *target, zval *level, zval *internalformat, zval *width, zval *height, zval *depth, zval *border, zval *format, zval *type, zval *pixels)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXIMAGE3DPROC fn = (PFNGLTEXIMAGE3DPROC) phpgl_entry("glTexImage3D", &slot, 1, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(internalformat), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height), (GLsizei) phpgl_arg_long(depth), (GLint) phpgl_arg_long(border), (GLenum) phpgl_arg_long(format), (GLenum) phpgl_arg_long(type), (const void *) phpgl_arg_ptr(pixels));
}

void phpgl_gl12_gltexsubimage3d(zval *target, zval *level, zval *xoffset, zval *yoffset, zval *zoffset, zval *width, zval *height, zval *depth, zval *format, zval *type, zval *pixels)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXSUBIMAGE3DPROC fn = (PFNGLTEXSUBIMAGE3DPROC) phpgl_entry("glTexSubImage3D", &slot, 1, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(xoffset), (GLint) phpgl_arg_long(yoffset), (GLint) phpgl_arg_long(zoffset), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height), (GLsizei) phpgl_arg_long(depth), (GLenum) phpgl_arg_long(format), (GLenum) phpgl_arg_long(type), (const void *) phpgl_arg_ptr(pixels));
}

void phpgl_gl12_glcopytexsubimage3d(zval *target, zval *level, zval *xoffset, zval *yoffset, zval *zoffset, zval *x, zval *y, zval *width, zval *height)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOPYTEXSUBIMAGE3DPROC fn = (PFNGLCOPYTEXSUBIMAGE3DPROC) phpgl_entry("glCopyTexSubImage3D", &slot, 1, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(xoffset), (GLint) phpgl_arg_long(yoffset), (GLint) phpgl_arg_long(zoffset), (GLint) phpgl_arg_long(x), (GLint) phpgl_arg_long(y), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height));
}

