/*
 * gl-21.h — OpenGL\GL\GL21 bound 1:1.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_2_1 (6 prototypes)
 */

#ifndef PHPGL_GL_21_H
#define PHPGL_GL_21_H

#include <php.h>

/*@audit block GL\GL21 GL_VERSION_2_1 6 */

/*@zep GL\GL21 glUniformMatrix2x3fv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl21_gluniformmatrix2x3fv(zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL21 glUniformMatrix3x2fv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl21_gluniformmatrix3x2fv(zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL21 glUniformMatrix2x4fv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl21_gluniformmatrix2x4fv(zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL21 glUniformMatrix4x2fv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl21_gluniformmatrix4x2fv(zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL21 glUniformMatrix3x4fv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl21_gluniformmatrix3x4fv(zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL21 glUniformMatrix4x3fv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl21_gluniformmatrix4x3fv(zval *location, zval *count, zval *transpose, zval *value);

#endif
