/*
 * gl-21.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_2_1 (6 prototypes)
 */

#include "gl-21.h"
#include "gl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

void phpgl_gl21_gluniformmatrix2x3fv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX2X3FVPROC fn = (PFNGLUNIFORMMATRIX2X3FVPROC) phpgl_entry("glUniformMatrix2x3fv", &slot, 2, 1);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl21_gluniformmatrix3x2fv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX3X2FVPROC fn = (PFNGLUNIFORMMATRIX3X2FVPROC) phpgl_entry("glUniformMatrix3x2fv", &slot, 2, 1);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl21_gluniformmatrix2x4fv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX2X4FVPROC fn = (PFNGLUNIFORMMATRIX2X4FVPROC) phpgl_entry("glUniformMatrix2x4fv", &slot, 2, 1);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl21_gluniformmatrix4x2fv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX4X2FVPROC fn = (PFNGLUNIFORMMATRIX4X2FVPROC) phpgl_entry("glUniformMatrix4x2fv", &slot, 2, 1);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl21_gluniformmatrix3x4fv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX3X4FVPROC fn = (PFNGLUNIFORMMATRIX3X4FVPROC) phpgl_entry("glUniformMatrix3x4fv", &slot, 2, 1);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl21_gluniformmatrix4x3fv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX4X3FVPROC fn = (PFNGLUNIFORMMATRIX4X3FVPROC) phpgl_entry("glUniformMatrix4x3fv", &slot, 2, 1);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

