/*
 * gl-31.h — OpenGL\GL\GL31 bound 1:1.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_3_1 (12 prototypes)
 */

#ifndef PHPGL_GL_31_H
#define PHPGL_GL_31_H

#include <php.h>

/*@audit block GL\GL31 GL_VERSION_3_1 12 */

/*@zep GL\GL31 glDrawArraysInstanced(int mode, int first, int count, int instancecount) -> void */
void phpgl_gl31_gldrawarraysinstanced(zval *mode, zval *first, zval *count, zval *instancecount);

/*@zep GL\GL31 glDrawElementsInstanced(int mode, int count, int type, int indices, int instancecount) -> void */
void phpgl_gl31_gldrawelementsinstanced(zval *mode, zval *count, zval *type, zval *indices, zval *instancecount);

/*@zep GL\GL31 glTexBuffer(int target, int internalformat, int buffer) -> void */
void phpgl_gl31_gltexbuffer(zval *target, zval *internalformat, zval *buffer);

/*@zep GL\GL31 glPrimitiveRestartIndex(int index) -> void */
void phpgl_gl31_glprimitiverestartindex(zval *index);

/*@zep GL\GL31 glCopyBufferSubData(int readTarget, int writeTarget, int readOffset, int writeOffset, int size) -> void */
void phpgl_gl31_glcopybuffersubdata(zval *readTarget, zval *writeTarget, zval *readOffset, zval *writeOffset, zval *size);

/*@zep GL\GL31 glGetUniformIndices(int program, int uniformCount, array uniformNames, int uniformIndices) -> void */
void phpgl_gl31_glgetuniformindices(zval *program, zval *uniformCount, zval *uniformNames, zval *uniformIndices);

/*@zep GL\GL31 glGetActiveUniformsiv(int program, int uniformCount, int uniformIndices, int pname, int params) -> void */
void phpgl_gl31_glgetactiveuniformsiv(zval *program, zval *uniformCount, zval *uniformIndices, zval *pname, zval *params);

/*@zep GL\GL31 glGetActiveUniformName(int program, int uniformIndex, int bufSize, int length, int uniformName) -> void */
void phpgl_gl31_glgetactiveuniformname(zval *program, zval *uniformIndex, zval *bufSize, zval *length, zval *uniformName);

/*@zep GL\GL31 glGetUniformBlockIndex(int program, string uniformBlockName) -> int */
zend_long phpgl_gl31_glgetuniformblockindex(zval *program, zval *uniformBlockName);

/*@zep GL\GL31 glGetActiveUniformBlockiv(int program, int uniformBlockIndex, int pname, int params) -> void */
void phpgl_gl31_glgetactiveuniformblockiv(zval *program, zval *uniformBlockIndex, zval *pname, zval *params);

/*@zep GL\GL31 glGetActiveUniformBlockName(int program, int uniformBlockIndex, int bufSize, int length, int uniformBlockName) -> void */
void phpgl_gl31_glgetactiveuniformblockname(zval *program, zval *uniformBlockIndex, zval *bufSize, zval *length, zval *uniformBlockName);

/*@zep GL\GL31 glUniformBlockBinding(int program, int uniformBlockIndex, int uniformBlockBinding) -> void */
void phpgl_gl31_gluniformblockbinding(zval *program, zval *uniformBlockIndex, zval *uniformBlockBinding);

#endif
