/*
 * gl-32.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_3_2 (19 prototypes)
 */

#include "gl-32.h"
#include "gl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

void phpgl_gl32_gldrawelementsbasevertex(zval *mode, zval *count, zval *type, zval *indices, zval *basevertex)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDRAWELEMENTSBASEVERTEXPROC fn = (PFNGLDRAWELEMENTSBASEVERTEXPROC) phpgl_entry("glDrawElementsBaseVertex", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (GLsizei) phpgl_arg_long(count), (GLenum) phpgl_arg_long(type), (const void *) phpgl_arg_ptr(indices), (GLint) phpgl_arg_long(basevertex));
}

void phpgl_gl32_gldrawrangeelementsbasevertex(zval *mode, zval *start, zval *end, zval *count, zval *type, zval *indices, zval *basevertex)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC fn = (PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC) phpgl_entry("glDrawRangeElementsBaseVertex", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (GLuint) phpgl_arg_long(start), (GLuint) phpgl_arg_long(end), (GLsizei) phpgl_arg_long(count), (GLenum) phpgl_arg_long(type), (const void *) phpgl_arg_ptr(indices), (GLint) phpgl_arg_long(basevertex));
}

void phpgl_gl32_gldrawelementsinstancedbasevertex(zval *mode, zval *count, zval *type, zval *indices, zval *instancecount, zval *basevertex)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC fn = (PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC) phpgl_entry("glDrawElementsInstancedBaseVertex", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (GLsizei) phpgl_arg_long(count), (GLenum) phpgl_arg_long(type), (const void *) phpgl_arg_ptr(indices), (GLsizei) phpgl_arg_long(instancecount), (GLint) phpgl_arg_long(basevertex));
}

void phpgl_gl32_glmultidrawelementsbasevertex(zval *mode, zval *count, zval *type, zval *indices, zval *drawcount, zval *basevertex)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC fn = (PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC) phpgl_entry("glMultiDrawElementsBaseVertex", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (const GLsizei *) phpgl_arg_ptr(count), (GLenum) phpgl_arg_long(type), (const void *const *) phpgl_arg_ptr(indices), (GLsizei) phpgl_arg_long(drawcount), (const GLint *) phpgl_arg_ptr(basevertex));
}

void phpgl_gl32_glprovokingvertex(zval *mode)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROVOKINGVERTEXPROC fn = (PFNGLPROVOKINGVERTEXPROC) phpgl_entry("glProvokingVertex", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode));
}

zend_long phpgl_gl32_glfencesync(zval *condition, zval *flags)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLFENCESYNCPROC fn = (PFNGLFENCESYNCPROC) phpgl_entry("glFenceSync", &slot, 3, 2);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((GLenum) phpgl_arg_long(condition), (GLbitfield) phpgl_arg_long(flags));
}

zend_long phpgl_gl32_glissync(zval *sync)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLISSYNCPROC fn = (PFNGLISSYNCPROC) phpgl_entry("glIsSync", &slot, 3, 2);

    if (!fn) {
        return 0;
    }

    return fn((GLsync) phpgl_arg_ptr(sync)) ? 1 : 0;
}

void phpgl_gl32_gldeletesync(zval *sync)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDELETESYNCPROC fn = (PFNGLDELETESYNCPROC) phpgl_entry("glDeleteSync", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLsync) phpgl_arg_ptr(sync));
}

zend_long phpgl_gl32_glclientwaitsync(zval *sync, zval *flags, zval *timeout)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCLIENTWAITSYNCPROC fn = (PFNGLCLIENTWAITSYNCPROC) phpgl_entry("glClientWaitSync", &slot, 3, 2);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((GLsync) phpgl_arg_ptr(sync), (GLbitfield) phpgl_arg_long(flags), (GLuint64) phpgl_arg_long(timeout));
}

void phpgl_gl32_glwaitsync(zval *sync, zval *flags, zval *timeout)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLWAITSYNCPROC fn = (PFNGLWAITSYNCPROC) phpgl_entry("glWaitSync", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLsync) phpgl_arg_ptr(sync), (GLbitfield) phpgl_arg_long(flags), (GLuint64) phpgl_arg_long(timeout));
}

void phpgl_gl32_glgetinteger64v(zval *pname, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETINTEGER64VPROC fn = (PFNGLGETINTEGER64VPROC) phpgl_entry("glGetInteger64v", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (GLint64 *) phpgl_arg_ptr(data));
}

void phpgl_gl32_glgetsynciv(zval *sync, zval *pname, zval *count, zval *length, zval *values)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETSYNCIVPROC fn = (PFNGLGETSYNCIVPROC) phpgl_entry("glGetSynciv", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLsync) phpgl_arg_ptr(sync), (GLenum) phpgl_arg_long(pname), (GLsizei) phpgl_arg_long(count), (GLsizei *) phpgl_arg_ptr(length), (GLint *) phpgl_arg_ptr(values));
}

void phpgl_gl32_glgetinteger64i_v(zval *target, zval *index, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETINTEGER64I_VPROC fn = (PFNGLGETINTEGER64I_VPROC) phpgl_entry("glGetInteger64i_v", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(index), (GLint64 *) phpgl_arg_ptr(data));
}

void phpgl_gl32_glgetbufferparameteri64v(zval *target, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETBUFFERPARAMETERI64VPROC fn = (PFNGLGETBUFFERPARAMETERI64VPROC) phpgl_entry("glGetBufferParameteri64v", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (GLint64 *) phpgl_arg_ptr(params));
}

void phpgl_gl32_glframebuffertexture(zval *target, zval *attachment, zval *texture, zval *level)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLFRAMEBUFFERTEXTUREPROC fn = (PFNGLFRAMEBUFFERTEXTUREPROC) phpgl_entry("glFramebufferTexture", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(attachment), (GLuint) phpgl_arg_long(texture), (GLint) phpgl_arg_long(level));
}

void phpgl_gl32_glteximage2dmultisample(zval *target, zval *samples, zval *internalformat, zval *width, zval *height, zval *fixedsamplelocations)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXIMAGE2DMULTISAMPLEPROC fn = (PFNGLTEXIMAGE2DMULTISAMPLEPROC) phpgl_entry("glTexImage2DMultisample", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLsizei) phpgl_arg_long(samples), (GLenum) phpgl_arg_long(internalformat), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height), (GLboolean) phpgl_arg_bool(fixedsamplelocations));
}

void phpgl_gl32_glteximage3dmultisample(zval *target, zval *samples, zval *internalformat, zval *width, zval *height, zval *depth, zval *fixedsamplelocations)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXIMAGE3DMULTISAMPLEPROC fn = (PFNGLTEXIMAGE3DMULTISAMPLEPROC) phpgl_entry("glTexImage3DMultisample", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLsizei) phpgl_arg_long(samples), (GLenum) phpgl_arg_long(internalformat), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height), (GLsizei) phpgl_arg_long(depth), (GLboolean) phpgl_arg_bool(fixedsamplelocations));
}

void phpgl_gl32_glgetmultisamplefv(zval *pname, zval *index, zval *val)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETMULTISAMPLEFVPROC fn = (PFNGLGETMULTISAMPLEFVPROC) phpgl_entry("glGetMultisamplefv", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (GLuint) phpgl_arg_long(index), (GLfloat *) phpgl_arg_ptr(val));
}

void phpgl_gl32_glsamplemaski(zval *maskNumber, zval *mask)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLSAMPLEMASKIPROC fn = (PFNGLSAMPLEMASKIPROC) phpgl_entry("glSampleMaski", &slot, 3, 2);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(maskNumber), (GLbitfield) phpgl_arg_long(mask));
}

