/*
 * gl-30.h — OpenGL\GL\GL30 bound 1:1.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_3_0 (84 prototypes)
 */

#ifndef PHPGL_GL_30_H
#define PHPGL_GL_30_H

#include <php.h>

/*@audit block GL\GL30 GL_VERSION_3_0 84 */

/*@zep GL\GL30 glColorMaski(int index, bool r, bool g, bool b, bool a) -> void */
void phpgl_gl30_glcolormaski(zval *index, zval *r, zval *g, zval *b, zval *a);

/*@zep GL\GL30 glGetBooleani_v(int target, int index, int data) -> void */
void phpgl_gl30_glgetbooleani_v(zval *target, zval *index, zval *data);

/*@zep GL\GL30 glGetIntegeri_v(int target, int index, int data) -> void */
void phpgl_gl30_glgetintegeri_v(zval *target, zval *index, zval *data);

/*@zep GL\GL30 glEnablei(int target, int index) -> void */
void phpgl_gl30_glenablei(zval *target, zval *index);

/*@zep GL\GL30 glDisablei(int target, int index) -> void */
void phpgl_gl30_gldisablei(zval *target, zval *index);

/*@zep GL\GL30 glIsEnabledi(int target, int index) -> bool */
zend_long phpgl_gl30_glisenabledi(zval *target, zval *index);

/*@zep GL\GL30 glBeginTransformFeedback(int primitiveMode) -> void */
void phpgl_gl30_glbegintransformfeedback(zval *primitiveMode);

/*@zep GL\GL30 glEndTransformFeedback() -> void */
void phpgl_gl30_glendtransformfeedback(void);

/*@zep GL\GL30 glBindBufferRange(int target, int index, int buffer, int offset, int size) -> void */
void phpgl_gl30_glbindbufferrange(zval *target, zval *index, zval *buffer, zval *offset, zval *size);

/*@zep GL\GL30 glBindBufferBase(int target, int index, int buffer) -> void */
void phpgl_gl30_glbindbufferbase(zval *target, zval *index, zval *buffer);

/*@zep GL\GL30 glTransformFeedbackVaryings(int program, int count, array varyings, int bufferMode) -> void */
void phpgl_gl30_gltransformfeedbackvaryings(zval *program, zval *count, zval *varyings, zval *bufferMode);

/*@zep GL\GL30 glGetTransformFeedbackVarying(int program, int index, int bufSize, int length, int size, int type, int name) -> void */
void phpgl_gl30_glgettransformfeedbackvarying(zval *program, zval *index, zval *bufSize, zval *length, zval *size, zval *type, zval *name);

/*@zep GL\GL30 glClampColor(int target, int clamp) -> void */
void phpgl_gl30_glclampcolor(zval *target, zval *clamp);

/*@zep GL\GL30 glBeginConditionalRender(int id, int mode) -> void */
void phpgl_gl30_glbeginconditionalrender(zval *id, zval *mode);

/*@zep GL\GL30 glEndConditionalRender() -> void */
void phpgl_gl30_glendconditionalrender(void);

/*@zep GL\GL30 glVertexAttribIPointer(int index, int size, int type, int stride, int pointer) -> void */
void phpgl_gl30_glvertexattribipointer(zval *index, zval *size, zval *type, zval *stride, zval *pointer);

/*@zep GL\GL30 glGetVertexAttribIiv(int index, int pname, int params) -> void */
void phpgl_gl30_glgetvertexattribiiv(zval *index, zval *pname, zval *params);

/*@zep GL\GL30 glGetVertexAttribIuiv(int index, int pname, int params) -> void */
void phpgl_gl30_glgetvertexattribiuiv(zval *index, zval *pname, zval *params);

/*@zep GL\GL30 glVertexAttribI1i(int index, int x) -> void */
void phpgl_gl30_glvertexattribi1i(zval *index, zval *x);

/*@zep GL\GL30 glVertexAttribI2i(int index, int x, int y) -> void */
void phpgl_gl30_glvertexattribi2i(zval *index, zval *x, zval *y);

/*@zep GL\GL30 glVertexAttribI3i(int index, int x, int y, int z) -> void */
void phpgl_gl30_glvertexattribi3i(zval *index, zval *x, zval *y, zval *z);

/*@zep GL\GL30 glVertexAttribI4i(int index, int x, int y, int z, int w) -> void */
void phpgl_gl30_glvertexattribi4i(zval *index, zval *x, zval *y, zval *z, zval *w);

/*@zep GL\GL30 glVertexAttribI1ui(int index, int x) -> void */
void phpgl_gl30_glvertexattribi1ui(zval *index, zval *x);

/*@zep GL\GL30 glVertexAttribI2ui(int index, int x, int y) -> void */
void phpgl_gl30_glvertexattribi2ui(zval *index, zval *x, zval *y);

/*@zep GL\GL30 glVertexAttribI3ui(int index, int x, int y, int z) -> void */
void phpgl_gl30_glvertexattribi3ui(zval *index, zval *x, zval *y, zval *z);

/*@zep GL\GL30 glVertexAttribI4ui(int index, int x, int y, int z, int w) -> void */
void phpgl_gl30_glvertexattribi4ui(zval *index, zval *x, zval *y, zval *z, zval *w);

/*@zep GL\GL30 glVertexAttribI1iv(int index, int v) -> void */
void phpgl_gl30_glvertexattribi1iv(zval *index, zval *v);

/*@zep GL\GL30 glVertexAttribI2iv(int index, int v) -> void */
void phpgl_gl30_glvertexattribi2iv(zval *index, zval *v);

/*@zep GL\GL30 glVertexAttribI3iv(int index, int v) -> void */
void phpgl_gl30_glvertexattribi3iv(zval *index, zval *v);

/*@zep GL\GL30 glVertexAttribI4iv(int index, int v) -> void */
void phpgl_gl30_glvertexattribi4iv(zval *index, zval *v);

/*@zep GL\GL30 glVertexAttribI1uiv(int index, int v) -> void */
void phpgl_gl30_glvertexattribi1uiv(zval *index, zval *v);

/*@zep GL\GL30 glVertexAttribI2uiv(int index, int v) -> void */
void phpgl_gl30_glvertexattribi2uiv(zval *index, zval *v);

/*@zep GL\GL30 glVertexAttribI3uiv(int index, int v) -> void */
void phpgl_gl30_glvertexattribi3uiv(zval *index, zval *v);

/*@zep GL\GL30 glVertexAttribI4uiv(int index, int v) -> void */
void phpgl_gl30_glvertexattribi4uiv(zval *index, zval *v);

/*@zep GL\GL30 glVertexAttribI4bv(int index, int v) -> void */
void phpgl_gl30_glvertexattribi4bv(zval *index, zval *v);

/*@zep GL\GL30 glVertexAttribI4sv(int index, int v) -> void */
void phpgl_gl30_glvertexattribi4sv(zval *index, zval *v);

/*@zep GL\GL30 glVertexAttribI4ubv(int index, int v) -> void */
void phpgl_gl30_glvertexattribi4ubv(zval *index, zval *v);

/*@zep GL\GL30 glVertexAttribI4usv(int index, int v) -> void */
void phpgl_gl30_glvertexattribi4usv(zval *index, zval *v);

/*@zep GL\GL30 glGetUniformuiv(int program, int location, int params) -> void */
void phpgl_gl30_glgetuniformuiv(zval *program, zval *location, zval *params);

/*@zep GL\GL30 glBindFragDataLocation(int program, int color, string name) -> void */
void phpgl_gl30_glbindfragdatalocation(zval *program, zval *color, zval *name);

/*@zep GL\GL30 glGetFragDataLocation(int program, string name) -> int */
zend_long phpgl_gl30_glgetfragdatalocation(zval *program, zval *name);

/*@zep GL\GL30 glUniform1ui(int location, int v0) -> void */
void phpgl_gl30_gluniform1ui(zval *location, zval *v0);

/*@zep GL\GL30 glUniform2ui(int location, int v0, int v1) -> void */
void phpgl_gl30_gluniform2ui(zval *location, zval *v0, zval *v1);

/*@zep GL\GL30 glUniform3ui(int location, int v0, int v1, int v2) -> void */
void phpgl_gl30_gluniform3ui(zval *location, zval *v0, zval *v1, zval *v2);

/*@zep GL\GL30 glUniform4ui(int location, int v0, int v1, int v2, int v3) -> void */
void phpgl_gl30_gluniform4ui(zval *location, zval *v0, zval *v1, zval *v2, zval *v3);

/*@zep GL\GL30 glUniform1uiv(int location, int count, int value) -> void */
void phpgl_gl30_gluniform1uiv(zval *location, zval *count, zval *value);

/*@zep GL\GL30 glUniform2uiv(int location, int count, int value) -> void */
void phpgl_gl30_gluniform2uiv(zval *location, zval *count, zval *value);

/*@zep GL\GL30 glUniform3uiv(int location, int count, int value) -> void */
void phpgl_gl30_gluniform3uiv(zval *location, zval *count, zval *value);

/*@zep GL\GL30 glUniform4uiv(int location, int count, int value) -> void */
void phpgl_gl30_gluniform4uiv(zval *location, zval *count, zval *value);

/*@zep GL\GL30 glTexParameterIiv(int target, int pname, int params) -> void */
void phpgl_gl30_gltexparameteriiv(zval *target, zval *pname, zval *params);

/*@zep GL\GL30 glTexParameterIuiv(int target, int pname, int params) -> void */
void phpgl_gl30_gltexparameteriuiv(zval *target, zval *pname, zval *params);

/*@zep GL\GL30 glGetTexParameterIiv(int target, int pname, int params) -> void */
void phpgl_gl30_glgettexparameteriiv(zval *target, zval *pname, zval *params);

/*@zep GL\GL30 glGetTexParameterIuiv(int target, int pname, int params) -> void */
void phpgl_gl30_glgettexparameteriuiv(zval *target, zval *pname, zval *params);

/*@zep GL\GL30 glClearBufferiv(int buffer, int drawbuffer, int value) -> void */
void phpgl_gl30_glclearbufferiv(zval *buffer, zval *drawbuffer, zval *value);

/*@zep GL\GL30 glClearBufferuiv(int buffer, int drawbuffer, int value) -> void */
void phpgl_gl30_glclearbufferuiv(zval *buffer, zval *drawbuffer, zval *value);

/*@zep GL\GL30 glClearBufferfv(int buffer, int drawbuffer, int value) -> void */
void phpgl_gl30_glclearbufferfv(zval *buffer, zval *drawbuffer, zval *value);

/*@zep GL\GL30 glClearBufferfi(int buffer, int drawbuffer, double depth, int stencil) -> void */
void phpgl_gl30_glclearbufferfi(zval *buffer, zval *drawbuffer, zval *depth, zval *stencil);

/*@zep GL\GL30 glGetStringi(int name, int index) -> var */
void phpgl_gl30_glgetstringi(zval *return_value, zval *name, zval *index);

/*@zep GL\GL30 glIsRenderbuffer(int renderbuffer) -> bool */
zend_long phpgl_gl30_glisrenderbuffer(zval *renderbuffer);

/*@zep GL\GL30 glBindRenderbuffer(int target, int renderbuffer) -> void */
void phpgl_gl30_glbindrenderbuffer(zval *target, zval *renderbuffer);

/*@zep GL\GL30 glDeleteRenderbuffers(int n, int renderbuffers) -> void */
void phpgl_gl30_gldeleterenderbuffers(zval *n, zval *renderbuffers);

/*@zep GL\GL30 glGenRenderbuffers(int n, int renderbuffers) -> void */
void phpgl_gl30_glgenrenderbuffers(zval *n, zval *renderbuffers);

/*@zep GL\GL30 glRenderbufferStorage(int target, int internalformat, int width, int height) -> void */
void phpgl_gl30_glrenderbufferstorage(zval *target, zval *internalformat, zval *width, zval *height);

/*@zep GL\GL30 glGetRenderbufferParameteriv(int target, int pname, int params) -> void */
void phpgl_gl30_glgetrenderbufferparameteriv(zval *target, zval *pname, zval *params);

/*@zep GL\GL30 glIsFramebuffer(int framebuffer) -> bool */
zend_long phpgl_gl30_glisframebuffer(zval *framebuffer);

/*@zep GL\GL30 glBindFramebuffer(int target, int framebuffer) -> void */
void phpgl_gl30_glbindframebuffer(zval *target, zval *framebuffer);

/*@zep GL\GL30 glDeleteFramebuffers(int n, int framebuffers) -> void */
void phpgl_gl30_gldeleteframebuffers(zval *n, zval *framebuffers);

/*@zep GL\GL30 glGenFramebuffers(int n, int framebuffers) -> void */
void phpgl_gl30_glgenframebuffers(zval *n, zval *framebuffers);

/*@zep GL\GL30 glCheckFramebufferStatus(int target) -> int */
zend_long phpgl_gl30_glcheckframebufferstatus(zval *target);

/*@zep GL\GL30 glFramebufferTexture1D(int target, int attachment, int textarget, int texture, int level) -> void */
void phpgl_gl30_glframebuffertexture1d(zval *target, zval *attachment, zval *textarget, zval *texture, zval *level);

/*@zep GL\GL30 glFramebufferTexture2D(int target, int attachment, int textarget, int texture, int level) -> void */
void phpgl_gl30_glframebuffertexture2d(zval *target, zval *attachment, zval *textarget, zval *texture, zval *level);

/*@zep GL\GL30 glFramebufferTexture3D(int target, int attachment, int textarget, int texture, int level, int zoffset) -> void */
void phpgl_gl30_glframebuffertexture3d(zval *target, zval *attachment, zval *textarget, zval *texture, zval *level, zval *zoffset);

/*@zep GL\GL30 glFramebufferRenderbuffer(int target, int attachment, int renderbuffertarget, int renderbuffer) -> void */
void phpgl_gl30_glframebufferrenderbuffer(zval *target, zval *attachment, zval *renderbuffertarget, zval *renderbuffer);

/*@zep GL\GL30 glGetFramebufferAttachmentParameteriv(int target, int attachment, int pname, int params) -> void */
void phpgl_gl30_glgetframebufferattachmentparameteriv(zval *target, zval *attachment, zval *pname, zval *params);

/*@zep GL\GL30 glGenerateMipmap(int target) -> void */
void phpgl_gl30_glgeneratemipmap(zval *target);

/*@zep GL\GL30 glBlitFramebuffer(int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, int mask, int filter) -> void */
void phpgl_gl30_glblitframebuffer(zval *srcX0, zval *srcY0, zval *srcX1, zval *srcY1, zval *dstX0, zval *dstY0, zval *dstX1, zval *dstY1, zval *mask, zval *filter);

/*@zep GL\GL30 glRenderbufferStorageMultisample(int target, int samples, int internalformat, int width, int height) -> void */
void phpgl_gl30_glrenderbufferstoragemultisample(zval *target, zval *samples, zval *internalformat, zval *width, zval *height);

/*@zep GL\GL30 glFramebufferTextureLayer(int target, int attachment, int texture, int level, int layer) -> void */
void phpgl_gl30_glframebuffertexturelayer(zval *target, zval *attachment, zval *texture, zval *level, zval *layer);

/*@zep GL\GL30 glMapBufferRange(int target, int offset, int length, int access) -> int */
zend_long phpgl_gl30_glmapbufferrange(zval *target, zval *offset, zval *length, zval *access);

/*@zep GL\GL30 glFlushMappedBufferRange(int target, int offset, int length) -> void */
void phpgl_gl30_glflushmappedbufferrange(zval *target, zval *offset, zval *length);

/*@zep GL\GL30 glBindVertexArray(int array) -> void */
void phpgl_gl30_glbindvertexarray(zval *array);

/*@zep GL\GL30 glDeleteVertexArrays(int n, int arrays) -> void */
void phpgl_gl30_gldeletevertexarrays(zval *n, zval *arrays);

/*@zep GL\GL30 glGenVertexArrays(int n, int arrays) -> void */
void phpgl_gl30_glgenvertexarrays(zval *n, zval *arrays);

/*@zep GL\GL30 glIsVertexArray(int array) -> bool */
zend_long phpgl_gl30_glisvertexarray(zval *array);

#endif
