/*
 * gl-30.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_3_0 (84 prototypes)
 */

#include "gl-30.h"
#include "gl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

void phpgl_gl30_glcolormaski(zval *index, zval *r, zval *g, zval *b, zval *a)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOLORMASKIPROC fn = (PFNGLCOLORMASKIPROC) phpgl_entry("glColorMaski", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLboolean) phpgl_arg_bool(r), (GLboolean) phpgl_arg_bool(g), (GLboolean) phpgl_arg_bool(b), (GLboolean) phpgl_arg_bool(a));
}

void phpgl_gl30_glgetbooleani_v(zval *target, zval *index, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETBOOLEANI_VPROC fn = (PFNGLGETBOOLEANI_VPROC) phpgl_entry("glGetBooleani_v", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(index), (GLboolean *) phpgl_arg_ptr(data));
}

void phpgl_gl30_glgetintegeri_v(zval *target, zval *index, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETINTEGERI_VPROC fn = (PFNGLGETINTEGERI_VPROC) phpgl_entry("glGetIntegeri_v", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(index), (GLint *) phpgl_arg_ptr(data));
}

void phpgl_gl30_glenablei(zval *target, zval *index)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLENABLEIPROC fn = (PFNGLENABLEIPROC) phpgl_entry("glEnablei", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(index));
}

void phpgl_gl30_gldisablei(zval *target, zval *index)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDISABLEIPROC fn = (PFNGLDISABLEIPROC) phpgl_entry("glDisablei", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(index));
}

zend_long phpgl_gl30_glisenabledi(zval *target, zval *index)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLISENABLEDIPROC fn = (PFNGLISENABLEDIPROC) phpgl_entry("glIsEnabledi", &slot, 3, 0);

    if (!fn) {
        return 0;
    }

    return fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(index)) ? 1 : 0;
}

void phpgl_gl30_glbegintransformfeedback(zval *primitiveMode)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBEGINTRANSFORMFEEDBACKPROC fn = (PFNGLBEGINTRANSFORMFEEDBACKPROC) phpgl_entry("glBeginTransformFeedback", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(primitiveMode));
}

void phpgl_gl30_glendtransformfeedback(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLENDTRANSFORMFEEDBACKPROC fn = (PFNGLENDTRANSFORMFEEDBACKPROC) phpgl_entry("glEndTransformFeedback", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn();
}

void phpgl_gl30_glbindbufferrange(zval *target, zval *index, zval *buffer, zval *offset, zval *size)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBINDBUFFERRANGEPROC fn = (PFNGLBINDBUFFERRANGEPROC) phpgl_entry("glBindBufferRange", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(index), (GLuint) phpgl_arg_long(buffer), (GLintptr) phpgl_arg_long(offset), (GLsizeiptr) phpgl_arg_long(size));
}

void phpgl_gl30_glbindbufferbase(zval *target, zval *index, zval *buffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBINDBUFFERBASEPROC fn = (PFNGLBINDBUFFERBASEPROC) phpgl_entry("glBindBufferBase", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(index), (GLuint) phpgl_arg_long(buffer));
}

void phpgl_gl30_gltransformfeedbackvaryings(zval *program, zval *count, zval *varyings, zval *bufferMode)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    char **strv = NULL;
    int strv_n = 0;
    PFNGLTRANSFORMFEEDBACKVARYINGSPROC fn = (PFNGLTRANSFORMFEEDBACKVARYINGSPROC) phpgl_entry("glTransformFeedbackVaryings", &slot, 3, 0);

    if (!fn) {
        return;
    }

    strv = phpgl_arg_strv(varyings, &strv_n);
    if (phpgl_arg_long(count) > (zend_long) strv_n) {
        php_error_docref(NULL, E_WARNING,
            "glTransformFeedbackVaryings: count exceeds the number of strings given");
        phpgl_free_strv(strv, strv_n);

        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLsizei) phpgl_arg_long(count), (const GLchar *const *) strv, (GLenum) phpgl_arg_long(bufferMode));
    phpgl_free_strv(strv, strv_n);
}

void phpgl_gl30_glgettransformfeedbackvarying(zval *program, zval *index, zval *bufSize, zval *length, zval *size, zval *type, zval *name)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETTRANSFORMFEEDBACKVARYINGPROC fn = (PFNGLGETTRANSFORMFEEDBACKVARYINGPROC) phpgl_entry("glGetTransformFeedbackVarying", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLuint) phpgl_arg_long(index), (GLsizei) phpgl_arg_long(bufSize), (GLsizei *) phpgl_arg_ptr(length), (GLsizei *) phpgl_arg_ptr(size), (GLenum *) phpgl_arg_ptr(type), (GLchar *) phpgl_arg_ptr(name));
}

void phpgl_gl30_glclampcolor(zval *target, zval *clamp)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCLAMPCOLORPROC fn = (PFNGLCLAMPCOLORPROC) phpgl_entry("glClampColor", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(clamp));
}

void phpgl_gl30_glbeginconditionalrender(zval *id, zval *mode)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBEGINCONDITIONALRENDERPROC fn = (PFNGLBEGINCONDITIONALRENDERPROC) phpgl_entry("glBeginConditionalRender", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(id), (GLenum) phpgl_arg_long(mode));
}

void phpgl_gl30_glendconditionalrender(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLENDCONDITIONALRENDERPROC fn = (PFNGLENDCONDITIONALRENDERPROC) phpgl_entry("glEndConditionalRender", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn();
}

void phpgl_gl30_glvertexattribipointer(zval *index, zval *size, zval *type, zval *stride, zval *pointer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBIPOINTERPROC fn = (PFNGLVERTEXATTRIBIPOINTERPROC) phpgl_entry("glVertexAttribIPointer", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLint) phpgl_arg_long(size), (GLenum) phpgl_arg_long(type), (GLsizei) phpgl_arg_long(stride), (const void *) phpgl_arg_ptr(pointer));
}

void phpgl_gl30_glgetvertexattribiiv(zval *index, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETVERTEXATTRIBIIVPROC fn = (PFNGLGETVERTEXATTRIBIIVPROC) phpgl_entry("glGetVertexAttribIiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl30_glgetvertexattribiuiv(zval *index, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETVERTEXATTRIBIUIVPROC fn = (PFNGLGETVERTEXATTRIBIUIVPROC) phpgl_entry("glGetVertexAttribIuiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLenum) phpgl_arg_long(pname), (GLuint *) phpgl_arg_ptr(params));
}

void phpgl_gl30_glvertexattribi1i(zval *index, zval *x)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI1IPROC fn = (PFNGLVERTEXATTRIBI1IPROC) phpgl_entry("glVertexAttribI1i", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLint) phpgl_arg_long(x));
}

void phpgl_gl30_glvertexattribi2i(zval *index, zval *x, zval *y)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI2IPROC fn = (PFNGLVERTEXATTRIBI2IPROC) phpgl_entry("glVertexAttribI2i", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLint) phpgl_arg_long(x), (GLint) phpgl_arg_long(y));
}

void phpgl_gl30_glvertexattribi3i(zval *index, zval *x, zval *y, zval *z)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI3IPROC fn = (PFNGLVERTEXATTRIBI3IPROC) phpgl_entry("glVertexAttribI3i", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLint) phpgl_arg_long(x), (GLint) phpgl_arg_long(y), (GLint) phpgl_arg_long(z));
}

void phpgl_gl30_glvertexattribi4i(zval *index, zval *x, zval *y, zval *z, zval *w)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI4IPROC fn = (PFNGLVERTEXATTRIBI4IPROC) phpgl_entry("glVertexAttribI4i", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLint) phpgl_arg_long(x), (GLint) phpgl_arg_long(y), (GLint) phpgl_arg_long(z), (GLint) phpgl_arg_long(w));
}

void phpgl_gl30_glvertexattribi1ui(zval *index, zval *x)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI1UIPROC fn = (PFNGLVERTEXATTRIBI1UIPROC) phpgl_entry("glVertexAttribI1ui", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLuint) phpgl_arg_long(x));
}

void phpgl_gl30_glvertexattribi2ui(zval *index, zval *x, zval *y)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI2UIPROC fn = (PFNGLVERTEXATTRIBI2UIPROC) phpgl_entry("glVertexAttribI2ui", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLuint) phpgl_arg_long(x), (GLuint) phpgl_arg_long(y));
}

void phpgl_gl30_glvertexattribi3ui(zval *index, zval *x, zval *y, zval *z)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI3UIPROC fn = (PFNGLVERTEXATTRIBI3UIPROC) phpgl_entry("glVertexAttribI3ui", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLuint) phpgl_arg_long(x), (GLuint) phpgl_arg_long(y), (GLuint) phpgl_arg_long(z));
}

void phpgl_gl30_glvertexattribi4ui(zval *index, zval *x, zval *y, zval *z, zval *w)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI4UIPROC fn = (PFNGLVERTEXATTRIBI4UIPROC) phpgl_entry("glVertexAttribI4ui", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLuint) phpgl_arg_long(x), (GLuint) phpgl_arg_long(y), (GLuint) phpgl_arg_long(z), (GLuint) phpgl_arg_long(w));
}

void phpgl_gl30_glvertexattribi1iv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI1IVPROC fn = (PFNGLVERTEXATTRIBI1IVPROC) phpgl_entry("glVertexAttribI1iv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLint *) phpgl_arg_ptr(v));
}

void phpgl_gl30_glvertexattribi2iv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI2IVPROC fn = (PFNGLVERTEXATTRIBI2IVPROC) phpgl_entry("glVertexAttribI2iv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLint *) phpgl_arg_ptr(v));
}

void phpgl_gl30_glvertexattribi3iv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI3IVPROC fn = (PFNGLVERTEXATTRIBI3IVPROC) phpgl_entry("glVertexAttribI3iv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLint *) phpgl_arg_ptr(v));
}

void phpgl_gl30_glvertexattribi4iv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI4IVPROC fn = (PFNGLVERTEXATTRIBI4IVPROC) phpgl_entry("glVertexAttribI4iv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLint *) phpgl_arg_ptr(v));
}

void phpgl_gl30_glvertexattribi1uiv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI1UIVPROC fn = (PFNGLVERTEXATTRIBI1UIVPROC) phpgl_entry("glVertexAttribI1uiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLuint *) phpgl_arg_ptr(v));
}

void phpgl_gl30_glvertexattribi2uiv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI2UIVPROC fn = (PFNGLVERTEXATTRIBI2UIVPROC) phpgl_entry("glVertexAttribI2uiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLuint *) phpgl_arg_ptr(v));
}

void phpgl_gl30_glvertexattribi3uiv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI3UIVPROC fn = (PFNGLVERTEXATTRIBI3UIVPROC) phpgl_entry("glVertexAttribI3uiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLuint *) phpgl_arg_ptr(v));
}

void phpgl_gl30_glvertexattribi4uiv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI4UIVPROC fn = (PFNGLVERTEXATTRIBI4UIVPROC) phpgl_entry("glVertexAttribI4uiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLuint *) phpgl_arg_ptr(v));
}

void phpgl_gl30_glvertexattribi4bv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI4BVPROC fn = (PFNGLVERTEXATTRIBI4BVPROC) phpgl_entry("glVertexAttribI4bv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLbyte *) phpgl_arg_ptr(v));
}

void phpgl_gl30_glvertexattribi4sv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI4SVPROC fn = (PFNGLVERTEXATTRIBI4SVPROC) phpgl_entry("glVertexAttribI4sv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLshort *) phpgl_arg_ptr(v));
}

void phpgl_gl30_glvertexattribi4ubv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI4UBVPROC fn = (PFNGLVERTEXATTRIBI4UBVPROC) phpgl_entry("glVertexAttribI4ubv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLubyte *) phpgl_arg_ptr(v));
}

void phpgl_gl30_glvertexattribi4usv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBI4USVPROC fn = (PFNGLVERTEXATTRIBI4USVPROC) phpgl_entry("glVertexAttribI4usv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLushort *) phpgl_arg_ptr(v));
}

void phpgl_gl30_glgetuniformuiv(zval *program, zval *location, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETUNIFORMUIVPROC fn = (PFNGLGETUNIFORMUIVPROC) phpgl_entry("glGetUniformuiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLuint *) phpgl_arg_ptr(params));
}

void phpgl_gl30_glbindfragdatalocation(zval *program, zval *color, zval *name)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBINDFRAGDATALOCATIONPROC fn = (PFNGLBINDFRAGDATALOCATIONPROC) phpgl_entry("glBindFragDataLocation", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLuint) phpgl_arg_long(color), (const GLchar *) phpgl_arg_string(name));
}

zend_long phpgl_gl30_glgetfragdatalocation(zval *program, zval *name)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETFRAGDATALOCATIONPROC fn = (PFNGLGETFRAGDATALOCATIONPROC) phpgl_entry("glGetFragDataLocation", &slot, 3, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((GLuint) phpgl_arg_long(program), (const GLchar *) phpgl_arg_string(name));
}

void phpgl_gl30_gluniform1ui(zval *location, zval *v0)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM1UIPROC fn = (PFNGLUNIFORM1UIPROC) phpgl_entry("glUniform1ui", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLuint) phpgl_arg_long(v0));
}

void phpgl_gl30_gluniform2ui(zval *location, zval *v0, zval *v1)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM2UIPROC fn = (PFNGLUNIFORM2UIPROC) phpgl_entry("glUniform2ui", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLuint) phpgl_arg_long(v0), (GLuint) phpgl_arg_long(v1));
}

void phpgl_gl30_gluniform3ui(zval *location, zval *v0, zval *v1, zval *v2)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM3UIPROC fn = (PFNGLUNIFORM3UIPROC) phpgl_entry("glUniform3ui", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLuint) phpgl_arg_long(v0), (GLuint) phpgl_arg_long(v1), (GLuint) phpgl_arg_long(v2));
}

void phpgl_gl30_gluniform4ui(zval *location, zval *v0, zval *v1, zval *v2, zval *v3)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM4UIPROC fn = (PFNGLUNIFORM4UIPROC) phpgl_entry("glUniform4ui", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLuint) phpgl_arg_long(v0), (GLuint) phpgl_arg_long(v1), (GLuint) phpgl_arg_long(v2), (GLuint) phpgl_arg_long(v3));
}

void phpgl_gl30_gluniform1uiv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM1UIVPROC fn = (PFNGLUNIFORM1UIVPROC) phpgl_entry("glUniform1uiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLuint *) phpgl_arg_ptr(value));
}

void phpgl_gl30_gluniform2uiv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM2UIVPROC fn = (PFNGLUNIFORM2UIVPROC) phpgl_entry("glUniform2uiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLuint *) phpgl_arg_ptr(value));
}

void phpgl_gl30_gluniform3uiv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM3UIVPROC fn = (PFNGLUNIFORM3UIVPROC) phpgl_entry("glUniform3uiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLuint *) phpgl_arg_ptr(value));
}

void phpgl_gl30_gluniform4uiv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM4UIVPROC fn = (PFNGLUNIFORM4UIVPROC) phpgl_entry("glUniform4uiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLuint *) phpgl_arg_ptr(value));
}

void phpgl_gl30_gltexparameteriiv(zval *target, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXPARAMETERIIVPROC fn = (PFNGLTEXPARAMETERIIVPROC) phpgl_entry("glTexParameterIiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (const GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl30_gltexparameteriuiv(zval *target, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXPARAMETERIUIVPROC fn = (PFNGLTEXPARAMETERIUIVPROC) phpgl_entry("glTexParameterIuiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (const GLuint *) phpgl_arg_ptr(params));
}

void phpgl_gl30_glgettexparameteriiv(zval *target, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETTEXPARAMETERIIVPROC fn = (PFNGLGETTEXPARAMETERIIVPROC) phpgl_entry("glGetTexParameterIiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl30_glgettexparameteriuiv(zval *target, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETTEXPARAMETERIUIVPROC fn = (PFNGLGETTEXPARAMETERIUIVPROC) phpgl_entry("glGetTexParameterIuiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (GLuint *) phpgl_arg_ptr(params));
}

void phpgl_gl30_glclearbufferiv(zval *buffer, zval *drawbuffer, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCLEARBUFFERIVPROC fn = (PFNGLCLEARBUFFERIVPROC) phpgl_entry("glClearBufferiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(buffer), (GLint) phpgl_arg_long(drawbuffer), (const GLint *) phpgl_arg_ptr(value));
}

void phpgl_gl30_glclearbufferuiv(zval *buffer, zval *drawbuffer, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCLEARBUFFERUIVPROC fn = (PFNGLCLEARBUFFERUIVPROC) phpgl_entry("glClearBufferuiv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(buffer), (GLint) phpgl_arg_long(drawbuffer), (const GLuint *) phpgl_arg_ptr(value));
}

void phpgl_gl30_glclearbufferfv(zval *buffer, zval *drawbuffer, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCLEARBUFFERFVPROC fn = (PFNGLCLEARBUFFERFVPROC) phpgl_entry("glClearBufferfv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(buffer), (GLint) phpgl_arg_long(drawbuffer), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl30_glclearbufferfi(zval *buffer, zval *drawbuffer, zval *depth, zval *stencil)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCLEARBUFFERFIPROC fn = (PFNGLCLEARBUFFERFIPROC) phpgl_entry("glClearBufferfi", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(buffer), (GLint) phpgl_arg_long(drawbuffer), (GLfloat) phpgl_arg_double(depth), (GLint) phpgl_arg_long(stencil));
}

void phpgl_gl30_glgetstringi(zval *return_value, zval *name, zval *index)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETSTRINGIPROC fn = (PFNGLGETSTRINGIPROC) phpgl_entry("glGetStringi", &slot, 3, 0);

    if (!fn) {
        ZVAL_NULL(return_value);

        return;
    }

    phpgl_ret_ubytes(return_value, fn((GLenum) phpgl_arg_long(name), (GLuint) phpgl_arg_long(index)));
}

zend_long phpgl_gl30_glisrenderbuffer(zval *renderbuffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLISRENDERBUFFERPROC fn = (PFNGLISRENDERBUFFERPROC) phpgl_entry("glIsRenderbuffer", &slot, 3, 0);

    if (!fn) {
        return 0;
    }

    return fn((GLuint) phpgl_arg_long(renderbuffer)) ? 1 : 0;
}

void phpgl_gl30_glbindrenderbuffer(zval *target, zval *renderbuffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBINDRENDERBUFFERPROC fn = (PFNGLBINDRENDERBUFFERPROC) phpgl_entry("glBindRenderbuffer", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(renderbuffer));
}

void phpgl_gl30_gldeleterenderbuffers(zval *n, zval *renderbuffers)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDELETERENDERBUFFERSPROC fn = (PFNGLDELETERENDERBUFFERSPROC) phpgl_entry("glDeleteRenderbuffers", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (const GLuint *) phpgl_arg_ptr(renderbuffers));
}

void phpgl_gl30_glgenrenderbuffers(zval *n, zval *renderbuffers)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGENRENDERBUFFERSPROC fn = (PFNGLGENRENDERBUFFERSPROC) phpgl_entry("glGenRenderbuffers", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (GLuint *) phpgl_arg_ptr(renderbuffers));
}

void phpgl_gl30_glrenderbufferstorage(zval *target, zval *internalformat, zval *width, zval *height)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLRENDERBUFFERSTORAGEPROC fn = (PFNGLRENDERBUFFERSTORAGEPROC) phpgl_entry("glRenderbufferStorage", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(internalformat), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height));
}

void phpgl_gl30_glgetrenderbufferparameteriv(zval *target, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETRENDERBUFFERPARAMETERIVPROC fn = (PFNGLGETRENDERBUFFERPARAMETERIVPROC) phpgl_entry("glGetRenderbufferParameteriv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

zend_long phpgl_gl30_glisframebuffer(zval *framebuffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLISFRAMEBUFFERPROC fn = (PFNGLISFRAMEBUFFERPROC) phpgl_entry("glIsFramebuffer", &slot, 3, 0);

    if (!fn) {
        return 0;
    }

    return fn((GLuint) phpgl_arg_long(framebuffer)) ? 1 : 0;
}

void phpgl_gl30_glbindframebuffer(zval *target, zval *framebuffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBINDFRAMEBUFFERPROC fn = (PFNGLBINDFRAMEBUFFERPROC) phpgl_entry("glBindFramebuffer", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(framebuffer));
}

void phpgl_gl30_gldeleteframebuffers(zval *n, zval *framebuffers)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDELETEFRAMEBUFFERSPROC fn = (PFNGLDELETEFRAMEBUFFERSPROC) phpgl_entry("glDeleteFramebuffers", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (const GLuint *) phpgl_arg_ptr(framebuffers));
}

void phpgl_gl30_glgenframebuffers(zval *n, zval *framebuffers)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGENFRAMEBUFFERSPROC fn = (PFNGLGENFRAMEBUFFERSPROC) phpgl_entry("glGenFramebuffers", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (GLuint *) phpgl_arg_ptr(framebuffers));
}

zend_long phpgl_gl30_glcheckframebufferstatus(zval *target)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCHECKFRAMEBUFFERSTATUSPROC fn = (PFNGLCHECKFRAMEBUFFERSTATUSPROC) phpgl_entry("glCheckFramebufferStatus", &slot, 3, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((GLenum) phpgl_arg_long(target));
}

void phpgl_gl30_glframebuffertexture1d(zval *target, zval *attachment, zval *textarget, zval *texture, zval *level)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLFRAMEBUFFERTEXTURE1DPROC fn = (PFNGLFRAMEBUFFERTEXTURE1DPROC) phpgl_entry("glFramebufferTexture1D", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(attachment), (GLenum) phpgl_arg_long(textarget), (GLuint) phpgl_arg_long(texture), (GLint) phpgl_arg_long(level));
}

void phpgl_gl30_glframebuffertexture2d(zval *target, zval *attachment, zval *textarget, zval *texture, zval *level)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLFRAMEBUFFERTEXTURE2DPROC fn = (PFNGLFRAMEBUFFERTEXTURE2DPROC) phpgl_entry("glFramebufferTexture2D", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(attachment), (GLenum) phpgl_arg_long(textarget), (GLuint) phpgl_arg_long(texture), (GLint) phpgl_arg_long(level));
}

void phpgl_gl30_glframebuffertexture3d(zval *target, zval *attachment, zval *textarget, zval *texture, zval *level, zval *zoffset)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLFRAMEBUFFERTEXTURE3DPROC fn = (PFNGLFRAMEBUFFERTEXTURE3DPROC) phpgl_entry("glFramebufferTexture3D", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(attachment), (GLenum) phpgl_arg_long(textarget), (GLuint) phpgl_arg_long(texture), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(zoffset));
}

void phpgl_gl30_glframebufferrenderbuffer(zval *target, zval *attachment, zval *renderbuffertarget, zval *renderbuffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLFRAMEBUFFERRENDERBUFFERPROC fn = (PFNGLFRAMEBUFFERRENDERBUFFERPROC) phpgl_entry("glFramebufferRenderbuffer", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(attachment), (GLenum) phpgl_arg_long(renderbuffertarget), (GLuint) phpgl_arg_long(renderbuffer));
}

void phpgl_gl30_glgetframebufferattachmentparameteriv(zval *target, zval *attachment, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC fn = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC) phpgl_entry("glGetFramebufferAttachmentParameteriv", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(attachment), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl30_glgeneratemipmap(zval *target)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGENERATEMIPMAPPROC fn = (PFNGLGENERATEMIPMAPPROC) phpgl_entry("glGenerateMipmap", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target));
}

void phpgl_gl30_glblitframebuffer(zval *srcX0, zval *srcY0, zval *srcX1, zval *srcY1, zval *dstX0, zval *dstY0, zval *dstX1, zval *dstY1, zval *mask, zval *filter)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBLITFRAMEBUFFERPROC fn = (PFNGLBLITFRAMEBUFFERPROC) phpgl_entry("glBlitFramebuffer", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(srcX0), (GLint) phpgl_arg_long(srcY0), (GLint) phpgl_arg_long(srcX1), (GLint) phpgl_arg_long(srcY1), (GLint) phpgl_arg_long(dstX0), (GLint) phpgl_arg_long(dstY0), (GLint) phpgl_arg_long(dstX1), (GLint) phpgl_arg_long(dstY1), (GLbitfield) phpgl_arg_long(mask), (GLenum) phpgl_arg_long(filter));
}

void phpgl_gl30_glrenderbufferstoragemultisample(zval *target, zval *samples, zval *internalformat, zval *width, zval *height)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC fn = (PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC) phpgl_entry("glRenderbufferStorageMultisample", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLsizei) phpgl_arg_long(samples), (GLenum) phpgl_arg_long(internalformat), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height));
}

void phpgl_gl30_glframebuffertexturelayer(zval *target, zval *attachment, zval *texture, zval *level, zval *layer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLFRAMEBUFFERTEXTURELAYERPROC fn = (PFNGLFRAMEBUFFERTEXTURELAYERPROC) phpgl_entry("glFramebufferTextureLayer", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(attachment), (GLuint) phpgl_arg_long(texture), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(layer));
}

zend_long phpgl_gl30_glmapbufferrange(zval *target, zval *offset, zval *length, zval *access)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLMAPBUFFERRANGEPROC fn = (PFNGLMAPBUFFERRANGEPROC) phpgl_entry("glMapBufferRange", &slot, 3, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((GLenum) phpgl_arg_long(target), (GLintptr) phpgl_arg_long(offset), (GLsizeiptr) phpgl_arg_long(length), (GLbitfield) phpgl_arg_long(access));
}

void phpgl_gl30_glflushmappedbufferrange(zval *target, zval *offset, zval *length)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLFLUSHMAPPEDBUFFERRANGEPROC fn = (PFNGLFLUSHMAPPEDBUFFERRANGEPROC) phpgl_entry("glFlushMappedBufferRange", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLintptr) phpgl_arg_long(offset), (GLsizeiptr) phpgl_arg_long(length));
}

void phpgl_gl30_glbindvertexarray(zval *array)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBINDVERTEXARRAYPROC fn = (PFNGLBINDVERTEXARRAYPROC) phpgl_entry("glBindVertexArray", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(array));
}

void phpgl_gl30_gldeletevertexarrays(zval *n, zval *arrays)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDELETEVERTEXARRAYSPROC fn = (PFNGLDELETEVERTEXARRAYSPROC) phpgl_entry("glDeleteVertexArrays", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (const GLuint *) phpgl_arg_ptr(arrays));
}

void phpgl_gl30_glgenvertexarrays(zval *n, zval *arrays)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGENVERTEXARRAYSPROC fn = (PFNGLGENVERTEXARRAYSPROC) phpgl_entry("glGenVertexArrays", &slot, 3, 0);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (GLuint *) phpgl_arg_ptr(arrays));
}

zend_long phpgl_gl30_glisvertexarray(zval *array)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLISVERTEXARRAYPROC fn = (PFNGLISVERTEXARRAYPROC) phpgl_entry("glIsVertexArray", &slot, 3, 0);

    if (!fn) {
        return 0;
    }

    return fn((GLuint) phpgl_arg_long(array)) ? 1 : 0;
}

