/*
 * gl-33.h — OpenGL\GL\GL33 bound 1:1.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_3_3 (28 prototypes)
 */

#ifndef PHPGL_GL_33_H
#define PHPGL_GL_33_H

#include <php.h>

/*@audit block GL\GL33 GL_VERSION_3_3 28 */

/*@zep GL\GL33 glBindFragDataLocationIndexed(int program, int colorNumber, int index, string name) -> void */
void phpgl_gl33_glbindfragdatalocationindexed(zval *program, zval *colorNumber, zval *index, zval *name);

/*@zep GL\GL33 glGetFragDataIndex(int program, string name) -> int */
zend_long phpgl_gl33_glgetfragdataindex(zval *program, zval *name);

/*@zep GL\GL33 glGenSamplers(int count, int samplers) -> void */
void phpgl_gl33_glgensamplers(zval *count, zval *samplers);

/*@zep GL\GL33 glDeleteSamplers(int count, int samplers) -> void */
void phpgl_gl33_gldeletesamplers(zval *count, zval *samplers);

/*@zep GL\GL33 glIsSampler(int sampler) -> bool */
zend_long phpgl_gl33_glissampler(zval *sampler);

/*@zep GL\GL33 glBindSampler(int unit, int sampler) -> void */
void phpgl_gl33_glbindsampler(zval *unit, zval *sampler);

/*@zep GL\GL33 glSamplerParameteri(int sampler, int pname, int param) -> void */
void phpgl_gl33_glsamplerparameteri(zval *sampler, zval *pname, zval *param);

/*@zep GL\GL33 glSamplerParameteriv(int sampler, int pname, int param) -> void */
void phpgl_gl33_glsamplerparameteriv(zval *sampler, zval *pname, zval *param);

/*@zep GL\GL33 glSamplerParameterf(int sampler, int pname, double param) -> void */
void phpgl_gl33_glsamplerparameterf(zval *sampler, zval *pname, zval *param);

/*@zep GL\GL33 glSamplerParameterfv(int sampler, int pname, int param) -> void */
void phpgl_gl33_glsamplerparameterfv(zval *sampler, zval *pname, zval *param);

/*@zep GL\GL33 glSamplerParameterIiv(int sampler, int pname, int param) -> void */
void phpgl_gl33_glsamplerparameteriiv(zval *sampler, zval *pname, zval *param);

/*@zep GL\GL33 glSamplerParameterIuiv(int sampler, int pname, int param) -> void */
void phpgl_gl33_glsamplerparameteriuiv(zval *sampler, zval *pname, zval *param);

/*@zep GL\GL33 glGetSamplerParameteriv(int sampler, int pname, int params) -> void */
void phpgl_gl33_glgetsamplerparameteriv(zval *sampler, zval *pname, zval *params);

/*@zep GL\GL33 glGetSamplerParameterIiv(int sampler, int pname, int params) -> void */
void phpgl_gl33_glgetsamplerparameteriiv(zval *sampler, zval *pname, zval *params);

/*@zep GL\GL33 glGetSamplerParameterfv(int sampler, int pname, int params) -> void */
void phpgl_gl33_glgetsamplerparameterfv(zval *sampler, zval *pname, zval *params);

/*@zep GL\GL33 glGetSamplerParameterIuiv(int sampler, int pname, int params) -> void */
void phpgl_gl33_glgetsamplerparameteriuiv(zval *sampler, zval *pname, zval *params);

/*@zep GL\GL33 glQueryCounter(int id, int target) -> void */
void phpgl_gl33_glquerycounter(zval *id, zval *target);

/*@zep GL\GL33 glGetQueryObjecti64v(int id, int pname, int params) -> void */
void phpgl_gl33_glgetqueryobjecti64v(zval *id, zval *pname, zval *params);

/*@zep GL\GL33 glGetQueryObjectui64v(int id, int pname, int params) -> void */
void phpgl_gl33_glgetqueryobjectui64v(zval *id, zval *pname, zval *params);

/*@zep GL\GL33 glVertexAttribDivisor(int index, int divisor) -> void */
void phpgl_gl33_glvertexattribdivisor(zval *index, zval *divisor);

/*@zep GL\GL33 glVertexAttribP1ui(int index, int type, bool normalized, int value) -> void */
void phpgl_gl33_glvertexattribp1ui(zval *index, zval *type, zval *normalized, zval *value);

/*@zep GL\GL33 glVertexAttribP1uiv(int index, int type, bool normalized, int value) -> void */
void phpgl_gl33_glvertexattribp1uiv(zval *index, zval *type, zval *normalized, zval *value);

/*@zep GL\GL33 glVertexAttribP2ui(int index, int type, bool normalized, int value) -> void */
void phpgl_gl33_glvertexattribp2ui(zval *index, zval *type, zval *normalized, zval *value);

/*@zep GL\GL33 glVertexAttribP2uiv(int index, int type, bool normalized, int value) -> void */
void phpgl_gl33_glvertexattribp2uiv(zval *index, zval *type, zval *normalized, zval *value);

/*@zep GL\GL33 glVertexAttribP3ui(int index, int type, bool normalized, int value) -> void */
void phpgl_gl33_glvertexattribp3ui(zval *index, zval *type, zval *normalized, zval *value);

/*@zep GL\GL33 glVertexAttribP3uiv(int index, int type, bool normalized, int value) -> void */
void phpgl_gl33_glvertexattribp3uiv(zval *index, zval *type, zval *normalized, zval *value);

/*@zep GL\GL33 glVertexAttribP4ui(int index, int type, bool normalized, int value) -> void */
void phpgl_gl33_glvertexattribp4ui(zval *index, zval *type, zval *normalized, zval *value);

/*@zep GL\GL33 glVertexAttribP4uiv(int index, int type, bool normalized, int value) -> void */
void phpgl_gl33_glvertexattribp4uiv(zval *index, zval *type, zval *normalized, zval *value);

#endif
