/*
 * gl-32.h — OpenGL\GL\GL32 bound 1:1.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_3_2 (19 prototypes)
 */

#ifndef PHPGL_GL_32_H
#define PHPGL_GL_32_H

#include <php.h>

/*@audit block GL\GL32 GL_VERSION_3_2 19 */

/*@zep GL\GL32 glDrawElementsBaseVertex(int mode, int count, int type, int indices, int basevertex) -> void */
void phpgl_gl32_gldrawelementsbasevertex(zval *mode, zval *count, zval *type, zval *indices, zval *basevertex);

/*@zep GL\GL32 glDrawRangeElementsBaseVertex(int mode, int start, int end, int count, int type, int indices, int basevertex) -> void */
void phpgl_gl32_gldrawrangeelementsbasevertex(zval *mode, zval *start, zval *end, zval *count, zval *type, zval *indices, zval *basevertex);

/*@zep GL\GL32 glDrawElementsInstancedBaseVertex(int mode, int count, int type, int indices, int instancecount, int basevertex) -> void */
void phpgl_gl32_gldrawelementsinstancedbasevertex(zval *mode, zval *count, zval *type, zval *indices, zval *instancecount, zval *basevertex);

/*@zep GL\GL32 glMultiDrawElementsBaseVertex(int mode, int count, int type, int indices, int drawcount, int basevertex) -> void */
void phpgl_gl32_glmultidrawelementsbasevertex(zval *mode, zval *count, zval *type, zval *indices, zval *drawcount, zval *basevertex);

/*@zep GL\GL32 glProvokingVertex(int mode) -> void */
void phpgl_gl32_glprovokingvertex(zval *mode);

/*@zep GL\GL32 glFenceSync(int condition, int flags) -> int */
zend_long phpgl_gl32_glfencesync(zval *condition, zval *flags);

/*@zep GL\GL32 glIsSync(int sync) -> bool */
zend_long phpgl_gl32_glissync(zval *sync);

/*@zep GL\GL32 glDeleteSync(int sync) -> void */
void phpgl_gl32_gldeletesync(zval *sync);

/*@zep GL\GL32 glClientWaitSync(int sync, int flags, int timeout) -> int */
zend_long phpgl_gl32_glclientwaitsync(zval *sync, zval *flags, zval *timeout);

/*@zep GL\GL32 glWaitSync(int sync, int flags, int timeout) -> void */
void phpgl_gl32_glwaitsync(zval *sync, zval *flags, zval *timeout);

/*@zep GL\GL32 glGetInteger64v(int pname, int data) -> void */
void phpgl_gl32_glgetinteger64v(zval *pname, zval *data);

/*@zep GL\GL32 glGetSynciv(int sync, int pname, int count, int length, int values) -> void */
void phpgl_gl32_glgetsynciv(zval *sync, zval *pname, zval *count, zval *length, zval *values);

/*@zep GL\GL32 glGetInteger64i_v(int target, int index, int data) -> void */
void phpgl_gl32_glgetinteger64i_v(zval *target, zval *index, zval *data);

/*@zep GL\GL32 glGetBufferParameteri64v(int target, int pname, int params) -> void */
void phpgl_gl32_glgetbufferparameteri64v(zval *target, zval *pname, zval *params);

/*@zep GL\GL32 glFramebufferTexture(int target, int attachment, int texture, int level) -> void */
void phpgl_gl32_glframebuffertexture(zval *target, zval *attachment, zval *texture, zval *level);

/*@zep GL\GL32 glTexImage2DMultisample(int target, int samples, int internalformat, int width, int height, bool fixedsamplelocations) -> void */
void phpgl_gl32_glteximage2dmultisample(zval *target, zval *samples, zval *internalformat, zval *width, zval *height, zval *fixedsamplelocations);

/*@zep GL\GL32 glTexImage3DMultisample(int target, int samples, int internalformat, int width, int height, int depth, bool fixedsamplelocations) -> void */
void phpgl_gl32_glteximage3dmultisample(zval *target, zval *samples, zval *internalformat, zval *width, zval *height, zval *depth, zval *fixedsamplelocations);

/*@zep GL\GL32 glGetMultisamplefv(int pname, int index, int val) -> void */
void phpgl_gl32_glgetmultisamplefv(zval *pname, zval *index, zval *val);

/*@zep GL\GL32 glSampleMaski(int maskNumber, int mask) -> void */
void phpgl_gl32_glsamplemaski(zval *maskNumber, zval *mask);

#endif
