/*
 * gl-40.h — OpenGL\GL\GL40 bound 1:1.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_4_0 (46 prototypes)
 */

#ifndef PHPGL_GL_40_H
#define PHPGL_GL_40_H

#include <php.h>

/*@audit block GL\GL40 GL_VERSION_4_0 46 */

/*@zep GL\GL40 glMinSampleShading(double value) -> void */
void phpgl_gl40_glminsampleshading(zval *value);

/*@zep GL\GL40 glBlendEquationi(int buf, int mode) -> void */
void phpgl_gl40_glblendequationi(zval *buf, zval *mode);

/*@zep GL\GL40 glBlendEquationSeparatei(int buf, int modeRGB, int modeAlpha) -> void */
void phpgl_gl40_glblendequationseparatei(zval *buf, zval *modeRGB, zval *modeAlpha);

/*@zep GL\GL40 glBlendFunci(int buf, int src, int dst) -> void */
void phpgl_gl40_glblendfunci(zval *buf, zval *src, zval *dst);

/*@zep GL\GL40 glBlendFuncSeparatei(int buf, int srcRGB, int dstRGB, int srcAlpha, int dstAlpha) -> void */
void phpgl_gl40_glblendfuncseparatei(zval *buf, zval *srcRGB, zval *dstRGB, zval *srcAlpha, zval *dstAlpha);

/*@zep GL\GL40 glDrawArraysIndirect(int mode, int indirect) -> void */
void phpgl_gl40_gldrawarraysindirect(zval *mode, zval *indirect);

/*@zep GL\GL40 glDrawElementsIndirect(int mode, int type, int indirect) -> void */
void phpgl_gl40_gldrawelementsindirect(zval *mode, zval *type, zval *indirect);

/*@zep GL\GL40 glUniform1d(int location, double x) -> void */
void phpgl_gl40_gluniform1d(zval *location, zval *x);

/*@zep GL\GL40 glUniform2d(int location, double x, double y) -> void */
void phpgl_gl40_gluniform2d(zval *location, zval *x, zval *y);

/*@zep GL\GL40 glUniform3d(int location, double x, double y, double z) -> void */
void phpgl_gl40_gluniform3d(zval *location, zval *x, zval *y, zval *z);

/*@zep GL\GL40 glUniform4d(int location, double x, double y, double z, double w) -> void */
void phpgl_gl40_gluniform4d(zval *location, zval *x, zval *y, zval *z, zval *w);

/*@zep GL\GL40 glUniform1dv(int location, int count, int value) -> void */
void phpgl_gl40_gluniform1dv(zval *location, zval *count, zval *value);

/*@zep GL\GL40 glUniform2dv(int location, int count, int value) -> void */
void phpgl_gl40_gluniform2dv(zval *location, zval *count, zval *value);

/*@zep GL\GL40 glUniform3dv(int location, int count, int value) -> void */
void phpgl_gl40_gluniform3dv(zval *location, zval *count, zval *value);

/*@zep GL\GL40 glUniform4dv(int location, int count, int value) -> void */
void phpgl_gl40_gluniform4dv(zval *location, zval *count, zval *value);

/*@zep GL\GL40 glUniformMatrix2dv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl40_gluniformmatrix2dv(zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL40 glUniformMatrix3dv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl40_gluniformmatrix3dv(zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL40 glUniformMatrix4dv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl40_gluniformmatrix4dv(zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL40 glUniformMatrix2x3dv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl40_gluniformmatrix2x3dv(zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL40 glUniformMatrix2x4dv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl40_gluniformmatrix2x4dv(zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL40 glUniformMatrix3x2dv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl40_gluniformmatrix3x2dv(zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL40 glUniformMatrix3x4dv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl40_gluniformmatrix3x4dv(zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL40 glUniformMatrix4x2dv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl40_gluniformmatrix4x2dv(zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL40 glUniformMatrix4x3dv(int location, int count, bool transpose, int value) -> void */
void phpgl_gl40_gluniformmatrix4x3dv(zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL40 glGetUniformdv(int program, int location, int params) -> void */
void phpgl_gl40_glgetuniformdv(zval *program, zval *location, zval *params);

/*@zep GL\GL40 glGetSubroutineUniformLocation(int program, int shadertype, string name) -> int */
zend_long phpgl_gl40_glgetsubroutineuniformlocation(zval *program, zval *shadertype, zval *name);

/*@zep GL\GL40 glGetSubroutineIndex(int program, int shadertype, string name) -> int */
zend_long phpgl_gl40_glgetsubroutineindex(zval *program, zval *shadertype, zval *name);

/*@zep GL\GL40 glGetActiveSubroutineUniformiv(int program, int shadertype, int index, int pname, int values) -> void */
void phpgl_gl40_glgetactivesubroutineuniformiv(zval *program, zval *shadertype, zval *index, zval *pname, zval *values);

/*@zep GL\GL40 glGetActiveSubroutineUniformName(int program, int shadertype, int index, int bufSize, int length, int name) -> void */
void phpgl_gl40_glgetactivesubroutineuniformname(zval *program, zval *shadertype, zval *index, zval *bufSize, zval *length, zval *name);

/*@zep GL\GL40 glGetActiveSubroutineName(int program, int shadertype, int index, int bufSize, int length, int name) -> void */
void phpgl_gl40_glgetactivesubroutinename(zval *program, zval *shadertype, zval *index, zval *bufSize, zval *length, zval *name);

/*@zep GL\GL40 glUniformSubroutinesuiv(int shadertype, int count, int indices) -> void */
void phpgl_gl40_gluniformsubroutinesuiv(zval *shadertype, zval *count, zval *indices);

/*@zep GL\GL40 glGetUniformSubroutineuiv(int shadertype, int location, int params) -> void */
void phpgl_gl40_glgetuniformsubroutineuiv(zval *shadertype, zval *location, zval *params);

/*@zep GL\GL40 glGetProgramStageiv(int program, int shadertype, int pname, int values) -> void */
void phpgl_gl40_glgetprogramstageiv(zval *program, zval *shadertype, zval *pname, zval *values);

/*@zep GL\GL40 glPatchParameteri(int pname, int value) -> void */
void phpgl_gl40_glpatchparameteri(zval *pname, zval *value);

/*@zep GL\GL40 glPatchParameterfv(int pname, int values) -> void */
void phpgl_gl40_glpatchparameterfv(zval *pname, zval *values);

/*@zep GL\GL40 glBindTransformFeedback(int target, int id) -> void */
void phpgl_gl40_glbindtransformfeedback(zval *target, zval *id);

/*@zep GL\GL40 glDeleteTransformFeedbacks(int n, int ids) -> void */
void phpgl_gl40_gldeletetransformfeedbacks(zval *n, zval *ids);

/*@zep GL\GL40 glGenTransformFeedbacks(int n, int ids) -> void */
void phpgl_gl40_glgentransformfeedbacks(zval *n, zval *ids);

/*@zep GL\GL40 glIsTransformFeedback(int id) -> bool */
zend_long phpgl_gl40_glistransformfeedback(zval *id);

/*@zep GL\GL40 glPauseTransformFeedback() -> void */
void phpgl_gl40_glpausetransformfeedback(void);

/*@zep GL\GL40 glResumeTransformFeedback() -> void */
void phpgl_gl40_glresumetransformfeedback(void);

/*@zep GL\GL40 glDrawTransformFeedback(int mode, int id) -> void */
void phpgl_gl40_gldrawtransformfeedback(zval *mode, zval *id);

/*@zep GL\GL40 glDrawTransformFeedbackStream(int mode, int id, int stream) -> void */
void phpgl_gl40_gldrawtransformfeedbackstream(zval *mode, zval *id, zval *stream);

/*@zep GL\GL40 glBeginQueryIndexed(int target, int index, int id) -> void */
void phpgl_gl40_glbeginqueryindexed(zval *target, zval *index, zval *id);

/*@zep GL\GL40 glEndQueryIndexed(int target, int index) -> void */
void phpgl_gl40_glendqueryindexed(zval *target, zval *index);

/*@zep GL\GL40 glGetQueryIndexediv(int target, int index, int pname, int params) -> void */
void phpgl_gl40_glgetqueryindexediv(zval *target, zval *index, zval *pname, zval *params);

#endif
