// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace OpenGL\GL\GL14;

class GL14
{
    public static function glBlendFuncSeparate(int sfactorRGB, int dfactorRGB, int sfactorAlpha, int dfactorAlpha) -> void
    {
        gl14_glblendfuncseparate(sfactorRGB, dfactorRGB, sfactorAlpha, dfactorAlpha);
    }

    public static function glMultiDrawArrays(int mode, int first, int count, int drawcount) -> void
    {
        gl14_glmultidrawarrays(mode, first, count, drawcount);
    }

    public static function glMultiDrawElements(int mode, int count, int type, int indices, int drawcount) -> void
    {
        gl14_glmultidrawelements(mode, count, type, indices, drawcount);
    }

    public static function glPointParameterf(int pname, double param) -> void
    {
        gl14_glpointparameterf(pname, param);
    }

    public static function glPointParameterfv(int pname, int params) -> void
    {
        gl14_glpointparameterfv(pname, params);
    }

    public static function glPointParameteri(int pname, int param) -> void
    {
        gl14_glpointparameteri(pname, param);
    }

    public static function glPointParameteriv(int pname, int params) -> void
    {
        gl14_glpointparameteriv(pname, params);
    }

    public static function glBlendColor(double red, double green, double blue, double alpha) -> void
    {
        gl14_glblendcolor(red, green, blue, alpha);
    }

    public static function glBlendEquation(int mode) -> void
    {
        gl14_glblendequation(mode);
    }
}
