<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class Gl10GlreadpixelsOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 7) {
            throw new CompilerException("'gl10_glreadpixels' requires exactly 7 parameters", $expression);
        }

        $context->headersManager->add('src/gl-10');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        $context->codePrinter->output('phpgl_gl10_glreadpixels(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ', ' . $resolvedParams[2] . ', ' . $resolvedParams[3] . ', ' . $resolvedParams[4] . ', ' . $resolvedParams[5] . ', ' . $resolvedParams[6] . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
