<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class Gl40GlpausetransformfeedbackOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (isset($expression['parameters']) && count($expression['parameters']) !== 0) {
            throw new CompilerException("'gl40_glpausetransformfeedback' requires zero parameters", $expression);
        }

        $context->headersManager->add('src/gl-40');


        $context->codePrinter->output('phpgl_gl40_glpausetransformfeedback(' . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
