#!/usr/bin/env php
<?php
/*
 * Whole-package structure check: the things that are true of this repo and
 * would be quietly wrong if a wave forgot one of them.
 *
 *   - config.json and composer.json agree on the version, and both say 0.8.0
 *   - composer.json declares both os-families and excludes Windows
 *   - every class named by an annotation has a .zep, and its method count
 *     matches its @zep count
 *   - every src/*.c is in extra-sources and every extra-sources entry exists
 *   - the vendored headers are present with a provenance README
 *   - no generated file was hand-edited out of its GENERATED banner
 *   - the per-class counts are the ones the design fixed (D1)
 *
 * Prints STRUCTURE_OK.
 */

declare(strict_types=1);

require __DIR__ . '/lib/harness.php';

$root = dirname(__DIR__, 2);
$expect = new Expect('structure-check');

/** The surface D1 fixed, per class. Changing a number here is a design change. */
const EXPECTED = [
    'GL\\GL10' => 48,
    'GL\\GL11' => 14,
    'GL\\GL12' => 4,
    'GL\\GL13' => 9,
    'GL\\GL14' => 9,
    'GL\\GL15' => 19,
    'GL\\GL20' => 93,
    'GL\\GL21' => 6,
    'GL\\GL30' => 84,
    'GL\\GL31' => 12,
    'GL\\GL32' => 19,
    'GL\\GL33' => 28,
    'GL\\GL40' => 46,
    'GL\\GL41' => 88,
    'EGL\\EGL' => 44,
    'Bridge\\Bridge' => 8,
];

// ---- versions
$config = json_decode((string) file_get_contents($root . '/config.json'), true);
$composer = json_decode((string) file_get_contents($root . '/composer.json'), true);
$expect->that(is_array($config), 'config.json is not valid JSON');
$expect->that(is_array($composer), 'composer.json is not valid JSON');
$expect->that(($config['version'] ?? null) === '0.8.0', 'config.json version is not 0.8.0');
$expect->that(($composer['version'] ?? null) === '0.8.0', 'composer.json version is not 0.8.0');
$expect->that(($config['extension-name'] ?? null) === 'opengl', 'config.json extension-name is not "opengl"');
$expect->that(($composer['name'] ?? null) === 'php-io-extensions/opengl', 'composer.json name is wrong');

$families = $composer['php-ext']['os-families'] ?? [];
sort($families);
$expect->that($families === ['darwin', 'linux'], 'composer.json os-families is not [darwin, linux]');
$expect->that(
    !in_array('windows', $families, true),
    'composer.json lists windows; this extension has no Windows half'
);

// ---- vendored headers
foreach (['glcorearb.h', 'egl.h', 'README.md'] as $f) {
    $expect->that(is_file("{$root}/scripts/khronos/{$f}"), "scripts/khronos/{$f} is missing");
}

// ---- annotations -> classes
$bound = [];
$reserved = [];
foreach (glob("{$root}/src/*.h") ?: [] as $header) {
    foreach (file($header, FILE_IGNORE_NEW_LINES) ?: [] as $line) {
        if (preg_match('#/\*\s*@reserved\s+([A-Za-z0-9_\\\\]+)\s+#', $line, $m)) {
            $reserved[$m[1]] = ($reserved[$m[1]] ?? 0) + 1;
            continue;
        }
        if (preg_match('#/\*\s*@zep(?:-construct)?\s+([A-Za-z0-9_\\\\]+)\s+#', $line, $m)) {
            $bound[$m[1]] = ($bound[$m[1]] ?? 0) + 1;
        }
    }
}
$expect->that($bound !== [], 'no annotations found under src/');

foreach (EXPECTED as $classPath => $count) {
    $expect->that(
        ($bound[$classPath] ?? 0) === $count,
        "{$classPath} binds " . ($bound[$classPath] ?? 0) . " method(s), the design fixed {$count}"
    );
}

// CGL only exists where OpenGL.framework does, so its counts are checked but
// its absence is not an error on Linux. Two of its 52 prototypes are
// reserved (foreign types), so 50 bind.
if (isset($bound['CGL\\CGL'])) {
    $expect->that($bound['CGL\\CGL'] === 50, 'CGL\\CGL binds ' . $bound['CGL\\CGL'] . ' method(s), expected 50');
    $expect->that(($reserved['CGL\\CGL'] ?? 0) === 2, 'CGL\\CGL reserves ' . ($reserved['CGL\\CGL'] ?? 0) . ' prototype(s), expected 2');
}

foreach ($bound as $classPath => $count) {
    $segments = explode('\\', $classPath);
    $class = end($segments);
    if (count($segments) >= 2 && $segments[count($segments) - 1] === $segments[count($segments) - 2]) {
        array_pop($segments);
    }
    $zep = $root . '/opengl/' . implode('/', array_map('strtolower', $segments))
        . '/' . strtolower($class) . '.zep';
    if (!is_file($zep)) {
        $expect->that(false, "{$classPath} has no generated .zep at " . substr($zep, strlen($root) + 1));
        continue;
    }
    $src = (string) file_get_contents($zep);
    $methods = preg_match_all('/public static function /', $src);
    $expect->that(
        $methods === $count,
        "{$classPath}: {$count} annotation(s) but {$methods} method(s) in the .zep"
    );
    $expect->that(
        str_contains($src, 'GENERATED by scripts/gen-zep.php'),
        "{$classPath}: the .zep lost its GENERATED banner"
    );
}

// ---- extra-sources
$listed = $config['extra-sources'] ?? [];
$onDisk = array_map(
    static fn (string $p): string => 'src/' . basename($p),
    glob("{$root}/src/*.c") ?: []
);
sort($listed);
sort($onDisk);
$expect->that($listed === $onDisk, 'config.json extra-sources does not match src/*.c on disk');

// ---- generated banners
foreach (glob("{$root}/src/gl-*.[ch]") ?: [] as $f) {
    $head = (string) file_get_contents($f, false, null, 0, 400);
    $expect->that(
        str_contains($head, 'GENERATED by scripts/gen-gl-src.php'),
        basename($f) . ' lost its GENERATED banner'
    );
}

// ---- the proof runs on both boxes from one file, and branches on the
//      platform in exactly one place (the banner and the report line read
//      PHP_OS_FAMILY without branching on it, which is not a decision).
$proof = (string) file_get_contents($root . '/examples/proof_headless.php');
$expect->that(
    preg_match_all('/PHP_OS_FAMILY\s*===/', $proof) === 1,
    'proof_headless.php branches on PHP_OS_FAMILY somewhere other than createContext()'
);
$expect->that(
    str_contains($proof, 'PROOF_HEADLESS_OK'),
    'proof_headless.php has no success token'
);

$expect->finish('STRUCTURE_OK');
