/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: 42119cf89eae4b83d68cebc641ba21de02f56159 */

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glGetError, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glGetString, 0, 1, IS_STRING, 1)
	ZEND_ARG_TYPE_INFO(0, name, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glGetIntegerv, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, pname, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(1, data, IS_ARRAY, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glFlush, 0, 0, IS_VOID, 0)
ZEND_END_ARG_INFO()

#define arginfo_glFinish arginfo_glFlush

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glCreateShader, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, type, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glShaderSource, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, shader, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, strings, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glCompileShader, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, shader, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glGetShaderiv, 0, 3, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, shader, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, pname, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(1, params, IS_LONG, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glGetShaderInfoLog, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, shader, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_glDeleteShader arginfo_glCompileShader

#define arginfo_glCreateProgram arginfo_glGetError

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glAttachShader, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, program, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, shader, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glBindAttribLocation, 0, 3, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, program, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glLinkProgram, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, program, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glGetProgramiv, 0, 3, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, program, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, pname, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(1, params, IS_LONG, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glGetProgramInfoLog, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, program, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_glUseProgram arginfo_glLinkProgram

#define arginfo_glDeleteProgram arginfo_glLinkProgram

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glGetUniformLocation, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, program, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_glGetAttribLocation arginfo_glGetUniformLocation

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glUniform1i, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, location, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glUniform1f, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, location, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v0, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glUniform2f, 0, 3, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, location, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v0, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, v1, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glUniform4f, 0, 5, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, location, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v0, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, v1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, v2, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, v3, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glUniformMatrix4fv, 0, 3, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, location, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, transpose, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glGenVertexArrays, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, n, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glBindVertexArray, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, array, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glDeleteVertexArrays, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, arrays, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

#define arginfo_glGenBuffers arginfo_glGenVertexArrays

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glBindBuffer, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, buffer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glBufferData, 0, 4, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, size, IS_LONG, 0)
	ZEND_ARG_TYPE_MASK(0, data, MAY_BE_STRING|MAY_BE_LONG|MAY_BE_NULL, NULL)
	ZEND_ARG_TYPE_INFO(0, usage, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glBufferSubData, 0, 4, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, offset, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, size, IS_LONG, 0)
	ZEND_ARG_TYPE_MASK(0, data, MAY_BE_STRING|MAY_BE_LONG, NULL)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glDeleteBuffers, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, buffers, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glEnableVertexAttribArray, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_glDisableVertexAttribArray arginfo_glEnableVertexAttribArray

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glVertexAttribPointer, 0, 6, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, size, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, type, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, normalized, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, stride, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, pointer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glMapBufferRange, 0, 4, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, offset, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, length, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, access, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glUnmapBuffer, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_glFenceSync, 0, 2, GLsync, 1)
	ZEND_ARG_TYPE_INFO(0, condition, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, flags, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glClientWaitSync, 0, 3, IS_LONG, 0)
	ZEND_ARG_OBJ_INFO(0, sync, GLsync, 0)
	ZEND_ARG_TYPE_INFO(0, flags, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, timeout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glDeleteSync, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, sync, GLsync, 0)
ZEND_END_ARG_INFO()

#define arginfo_glGenTextures arginfo_glGenVertexArrays

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glBindTexture, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, texture, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glTexImage2D, 0, 9, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, level, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, internalformat, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, border, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, format, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, type, IS_LONG, 0)
	ZEND_ARG_TYPE_MASK(0, pixels, MAY_BE_STRING|MAY_BE_LONG|MAY_BE_NULL, NULL)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glTexSubImage2D, 0, 9, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, level, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, xoffset, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, yoffset, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, format, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, type, IS_LONG, 0)
	ZEND_ARG_TYPE_MASK(0, pixels, MAY_BE_STRING|MAY_BE_LONG, NULL)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glTexParameteri, 0, 3, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, pname, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, param, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glActiveTexture, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, texture, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glDeleteTextures, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, textures, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glPixelStorei, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, pname, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, param, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_glGenFramebuffers arginfo_glGenVertexArrays

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glBindFramebuffer, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, framebuffer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glFramebufferTexture2D, 0, 5, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, attachment, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, textarget, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, texture, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, level, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glCheckFramebufferStatus, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glDeleteFramebuffers, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, framebuffers, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

#define arginfo_glGenRenderbuffers arginfo_glGenVertexArrays

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glBindRenderbuffer, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, renderbuffer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glRenderbufferStorage, 0, 4, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, internalformat, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glRenderbufferStorageMultisample, 0, 5, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, samples, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, internalformat, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glFramebufferRenderbuffer, 0, 4, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, attachment, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, renderbuffertarget, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, renderbuffer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glDeleteRenderbuffers, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, renderbuffers, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glBlitFramebuffer, 0, 10, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, srcX0, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, srcY0, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, srcX1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, srcY1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dstX0, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dstY0, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dstX1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dstY1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, mask, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, filter, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glDrawBuffers, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, bufs, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glReadBuffer, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, src, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glReadPixels, 0, 7, IS_STRING, 1)
	ZEND_ARG_TYPE_INFO(0, x, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, y, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, format, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, type, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, pixels, IS_LONG, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glViewport, 0, 4, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, x, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, y, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_glScissor arginfo_glViewport

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glEnable, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, cap, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_glDisable arginfo_glEnable

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glBlendFunc, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, sfactor, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dfactor, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glBlendFuncSeparate, 0, 4, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, srcRGB, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dstRGB, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, srcAlpha, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dstAlpha, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glBlendEquation, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, mode, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glColorMask, 0, 4, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, red, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, green, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, blue, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, alpha, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glClearColor, 0, 4, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, red, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, green, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, blue, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, alpha, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glClearStencil, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, s, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glClear, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, mask, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glStencilFunc, 0, 3, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, func, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, ref, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, mask, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glStencilOp, 0, 3, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, sfail, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dpfail, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dppass, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glStencilOpSeparate, 0, 4, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, face, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, sfail, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dpfail, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dppass, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_glStencilMask arginfo_glClear

#define arginfo_glCullFace arginfo_glBlendEquation

#define arginfo_glFrontFace arginfo_glBlendEquation

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glDrawArrays, 0, 3, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, mode, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, first, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, count, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_glDrawElements, 0, 4, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, mode, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, count, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, type, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, indices, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_GLsync___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_GLsync_pointer arginfo_glGetError

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_GLsync_fromPointer, 0, 1, IS_STATIC, 0)
	ZEND_ARG_TYPE_INFO(0, pointer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_FUNCTION(glGetError);
ZEND_FUNCTION(glGetString);
ZEND_FUNCTION(glGetIntegerv);
ZEND_FUNCTION(glFlush);
ZEND_FUNCTION(glFinish);
ZEND_FUNCTION(glCreateShader);
ZEND_FUNCTION(glShaderSource);
ZEND_FUNCTION(glCompileShader);
ZEND_FUNCTION(glGetShaderiv);
ZEND_FUNCTION(glGetShaderInfoLog);
ZEND_FUNCTION(glDeleteShader);
ZEND_FUNCTION(glCreateProgram);
ZEND_FUNCTION(glAttachShader);
ZEND_FUNCTION(glBindAttribLocation);
ZEND_FUNCTION(glLinkProgram);
ZEND_FUNCTION(glGetProgramiv);
ZEND_FUNCTION(glGetProgramInfoLog);
ZEND_FUNCTION(glUseProgram);
ZEND_FUNCTION(glDeleteProgram);
ZEND_FUNCTION(glGetUniformLocation);
ZEND_FUNCTION(glGetAttribLocation);
ZEND_FUNCTION(glUniform1i);
ZEND_FUNCTION(glUniform1f);
ZEND_FUNCTION(glUniform2f);
ZEND_FUNCTION(glUniform4f);
ZEND_FUNCTION(glUniformMatrix4fv);
ZEND_FUNCTION(glGenVertexArrays);
ZEND_FUNCTION(glBindVertexArray);
ZEND_FUNCTION(glDeleteVertexArrays);
ZEND_FUNCTION(glGenBuffers);
ZEND_FUNCTION(glBindBuffer);
ZEND_FUNCTION(glBufferData);
ZEND_FUNCTION(glBufferSubData);
ZEND_FUNCTION(glDeleteBuffers);
ZEND_FUNCTION(glEnableVertexAttribArray);
ZEND_FUNCTION(glDisableVertexAttribArray);
ZEND_FUNCTION(glVertexAttribPointer);
ZEND_FUNCTION(glMapBufferRange);
ZEND_FUNCTION(glUnmapBuffer);
ZEND_FUNCTION(glFenceSync);
ZEND_FUNCTION(glClientWaitSync);
ZEND_FUNCTION(glDeleteSync);
ZEND_FUNCTION(glGenTextures);
ZEND_FUNCTION(glBindTexture);
ZEND_FUNCTION(glTexImage2D);
ZEND_FUNCTION(glTexSubImage2D);
ZEND_FUNCTION(glTexParameteri);
ZEND_FUNCTION(glActiveTexture);
ZEND_FUNCTION(glDeleteTextures);
ZEND_FUNCTION(glPixelStorei);
ZEND_FUNCTION(glGenFramebuffers);
ZEND_FUNCTION(glBindFramebuffer);
ZEND_FUNCTION(glFramebufferTexture2D);
ZEND_FUNCTION(glCheckFramebufferStatus);
ZEND_FUNCTION(glDeleteFramebuffers);
ZEND_FUNCTION(glGenRenderbuffers);
ZEND_FUNCTION(glBindRenderbuffer);
ZEND_FUNCTION(glRenderbufferStorage);
ZEND_FUNCTION(glRenderbufferStorageMultisample);
ZEND_FUNCTION(glFramebufferRenderbuffer);
ZEND_FUNCTION(glDeleteRenderbuffers);
ZEND_FUNCTION(glBlitFramebuffer);
ZEND_FUNCTION(glDrawBuffers);
ZEND_FUNCTION(glReadBuffer);
ZEND_FUNCTION(glReadPixels);
ZEND_FUNCTION(glViewport);
ZEND_FUNCTION(glScissor);
ZEND_FUNCTION(glEnable);
ZEND_FUNCTION(glDisable);
ZEND_FUNCTION(glBlendFunc);
ZEND_FUNCTION(glBlendFuncSeparate);
ZEND_FUNCTION(glBlendEquation);
ZEND_FUNCTION(glColorMask);
ZEND_FUNCTION(glClearColor);
ZEND_FUNCTION(glClearStencil);
ZEND_FUNCTION(glClear);
ZEND_FUNCTION(glStencilFunc);
ZEND_FUNCTION(glStencilOp);
ZEND_FUNCTION(glStencilOpSeparate);
ZEND_FUNCTION(glStencilMask);
ZEND_FUNCTION(glCullFace);
ZEND_FUNCTION(glFrontFace);
ZEND_FUNCTION(glDrawArrays);
ZEND_FUNCTION(glDrawElements);
ZEND_METHOD(GLsync, __construct);
ZEND_METHOD(GLsync, pointer);
ZEND_METHOD(GLsync, fromPointer);

static const zend_function_entry ext_functions[] = {
	ZEND_FE(glGetError, arginfo_glGetError)
	ZEND_FE(glGetString, arginfo_glGetString)
	ZEND_FE(glGetIntegerv, arginfo_glGetIntegerv)
	ZEND_FE(glFlush, arginfo_glFlush)
	ZEND_FE(glFinish, arginfo_glFinish)
	ZEND_FE(glCreateShader, arginfo_glCreateShader)
	ZEND_FE(glShaderSource, arginfo_glShaderSource)
	ZEND_FE(glCompileShader, arginfo_glCompileShader)
	ZEND_FE(glGetShaderiv, arginfo_glGetShaderiv)
	ZEND_FE(glGetShaderInfoLog, arginfo_glGetShaderInfoLog)
	ZEND_FE(glDeleteShader, arginfo_glDeleteShader)
	ZEND_FE(glCreateProgram, arginfo_glCreateProgram)
	ZEND_FE(glAttachShader, arginfo_glAttachShader)
	ZEND_FE(glBindAttribLocation, arginfo_glBindAttribLocation)
	ZEND_FE(glLinkProgram, arginfo_glLinkProgram)
	ZEND_FE(glGetProgramiv, arginfo_glGetProgramiv)
	ZEND_FE(glGetProgramInfoLog, arginfo_glGetProgramInfoLog)
	ZEND_FE(glUseProgram, arginfo_glUseProgram)
	ZEND_FE(glDeleteProgram, arginfo_glDeleteProgram)
	ZEND_FE(glGetUniformLocation, arginfo_glGetUniformLocation)
	ZEND_FE(glGetAttribLocation, arginfo_glGetAttribLocation)
	ZEND_FE(glUniform1i, arginfo_glUniform1i)
	ZEND_FE(glUniform1f, arginfo_glUniform1f)
	ZEND_FE(glUniform2f, arginfo_glUniform2f)
	ZEND_FE(glUniform4f, arginfo_glUniform4f)
	ZEND_FE(glUniformMatrix4fv, arginfo_glUniformMatrix4fv)
	ZEND_FE(glGenVertexArrays, arginfo_glGenVertexArrays)
	ZEND_FE(glBindVertexArray, arginfo_glBindVertexArray)
	ZEND_FE(glDeleteVertexArrays, arginfo_glDeleteVertexArrays)
	ZEND_FE(glGenBuffers, arginfo_glGenBuffers)
	ZEND_FE(glBindBuffer, arginfo_glBindBuffer)
	ZEND_FE(glBufferData, arginfo_glBufferData)
	ZEND_FE(glBufferSubData, arginfo_glBufferSubData)
	ZEND_FE(glDeleteBuffers, arginfo_glDeleteBuffers)
	ZEND_FE(glEnableVertexAttribArray, arginfo_glEnableVertexAttribArray)
	ZEND_FE(glDisableVertexAttribArray, arginfo_glDisableVertexAttribArray)
	ZEND_FE(glVertexAttribPointer, arginfo_glVertexAttribPointer)
	ZEND_FE(glMapBufferRange, arginfo_glMapBufferRange)
	ZEND_FE(glUnmapBuffer, arginfo_glUnmapBuffer)
	ZEND_FE(glFenceSync, arginfo_glFenceSync)
	ZEND_FE(glClientWaitSync, arginfo_glClientWaitSync)
	ZEND_FE(glDeleteSync, arginfo_glDeleteSync)
	ZEND_FE(glGenTextures, arginfo_glGenTextures)
	ZEND_FE(glBindTexture, arginfo_glBindTexture)
	ZEND_FE(glTexImage2D, arginfo_glTexImage2D)
	ZEND_FE(glTexSubImage2D, arginfo_glTexSubImage2D)
	ZEND_FE(glTexParameteri, arginfo_glTexParameteri)
	ZEND_FE(glActiveTexture, arginfo_glActiveTexture)
	ZEND_FE(glDeleteTextures, arginfo_glDeleteTextures)
	ZEND_FE(glPixelStorei, arginfo_glPixelStorei)
	ZEND_FE(glGenFramebuffers, arginfo_glGenFramebuffers)
	ZEND_FE(glBindFramebuffer, arginfo_glBindFramebuffer)
	ZEND_FE(glFramebufferTexture2D, arginfo_glFramebufferTexture2D)
	ZEND_FE(glCheckFramebufferStatus, arginfo_glCheckFramebufferStatus)
	ZEND_FE(glDeleteFramebuffers, arginfo_glDeleteFramebuffers)
	ZEND_FE(glGenRenderbuffers, arginfo_glGenRenderbuffers)
	ZEND_FE(glBindRenderbuffer, arginfo_glBindRenderbuffer)
	ZEND_FE(glRenderbufferStorage, arginfo_glRenderbufferStorage)
	ZEND_FE(glRenderbufferStorageMultisample, arginfo_glRenderbufferStorageMultisample)
	ZEND_FE(glFramebufferRenderbuffer, arginfo_glFramebufferRenderbuffer)
	ZEND_FE(glDeleteRenderbuffers, arginfo_glDeleteRenderbuffers)
	ZEND_FE(glBlitFramebuffer, arginfo_glBlitFramebuffer)
	ZEND_FE(glDrawBuffers, arginfo_glDrawBuffers)
	ZEND_FE(glReadBuffer, arginfo_glReadBuffer)
	ZEND_FE(glReadPixels, arginfo_glReadPixels)
	ZEND_FE(glViewport, arginfo_glViewport)
	ZEND_FE(glScissor, arginfo_glScissor)
	ZEND_FE(glEnable, arginfo_glEnable)
	ZEND_FE(glDisable, arginfo_glDisable)
	ZEND_FE(glBlendFunc, arginfo_glBlendFunc)
	ZEND_FE(glBlendFuncSeparate, arginfo_glBlendFuncSeparate)
	ZEND_FE(glBlendEquation, arginfo_glBlendEquation)
	ZEND_FE(glColorMask, arginfo_glColorMask)
	ZEND_FE(glClearColor, arginfo_glClearColor)
	ZEND_FE(glClearStencil, arginfo_glClearStencil)
	ZEND_FE(glClear, arginfo_glClear)
	ZEND_FE(glStencilFunc, arginfo_glStencilFunc)
	ZEND_FE(glStencilOp, arginfo_glStencilOp)
	ZEND_FE(glStencilOpSeparate, arginfo_glStencilOpSeparate)
	ZEND_FE(glStencilMask, arginfo_glStencilMask)
	ZEND_FE(glCullFace, arginfo_glCullFace)
	ZEND_FE(glFrontFace, arginfo_glFrontFace)
	ZEND_FE(glDrawArrays, arginfo_glDrawArrays)
	ZEND_FE(glDrawElements, arginfo_glDrawElements)
	ZEND_FE_END
};

static const zend_function_entry class_GLsync_methods[] = {
	ZEND_ME(GLsync, __construct, arginfo_class_GLsync___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(GLsync, pointer, arginfo_class_GLsync_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(GLsync, fromPointer, arginfo_class_GLsync_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static void register_gl_symbols(int module_number)
{
	REGISTER_LONG_CONSTANT("GL_NO_ERROR", GL_NO_ERROR, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_VERSION", GL_VERSION, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_RENDERER", GL_RENDERER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_VENDOR", GL_VENDOR, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_SHADING_LANGUAGE_VERSION", GL_SHADING_LANGUAGE_VERSION, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_MAX_SAMPLES", GL_MAX_SAMPLES, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_VIEWPORT", GL_VIEWPORT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_SCISSOR_BOX", GL_SCISSOR_BOX, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_MAX_VIEWPORT_DIMS", GL_MAX_VIEWPORT_DIMS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_MAX_TEXTURE_SIZE", GL_MAX_TEXTURE_SIZE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_VERTEX_SHADER", GL_VERTEX_SHADER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_FRAGMENT_SHADER", GL_FRAGMENT_SHADER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_COMPILE_STATUS", GL_COMPILE_STATUS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_LINK_STATUS", GL_LINK_STATUS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_INFO_LOG_LENGTH", GL_INFO_LOG_LENGTH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_TRUE", GL_TRUE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_FALSE", GL_FALSE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_ARRAY_BUFFER", GL_ARRAY_BUFFER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_ELEMENT_ARRAY_BUFFER", GL_ELEMENT_ARRAY_BUFFER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_PIXEL_PACK_BUFFER", GL_PIXEL_PACK_BUFFER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_PIXEL_UNPACK_BUFFER", GL_PIXEL_UNPACK_BUFFER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_STATIC_DRAW", GL_STATIC_DRAW, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_DYNAMIC_DRAW", GL_DYNAMIC_DRAW, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_STREAM_DRAW", GL_STREAM_DRAW, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_STREAM_READ", GL_STREAM_READ, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_FLOAT", GL_FLOAT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_UNSIGNED_BYTE", GL_UNSIGNED_BYTE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_UNSIGNED_SHORT", GL_UNSIGNED_SHORT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_UNSIGNED_INT", GL_UNSIGNED_INT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_MAP_READ_BIT", GL_MAP_READ_BIT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_MAP_WRITE_BIT", GL_MAP_WRITE_BIT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_MAP_INVALIDATE_RANGE_BIT", GL_MAP_INVALIDATE_RANGE_BIT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_MAP_INVALIDATE_BUFFER_BIT", GL_MAP_INVALIDATE_BUFFER_BIT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_SYNC_GPU_COMMANDS_COMPLETE", GL_SYNC_GPU_COMMANDS_COMPLETE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_SYNC_FLUSH_COMMANDS_BIT", GL_SYNC_FLUSH_COMMANDS_BIT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_ALREADY_SIGNALED", GL_ALREADY_SIGNALED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_CONDITION_SATISFIED", GL_CONDITION_SATISFIED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_TIMEOUT_EXPIRED", GL_TIMEOUT_EXPIRED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_WAIT_FAILED", GL_WAIT_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_BUFFER_SIZE", GL_BUFFER_SIZE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_TEXTURE_2D", GL_TEXTURE_2D, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_TEXTURE0", GL_TEXTURE0, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_RGBA", GL_RGBA, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_RGBA8", GL_RGBA8, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_RGB", GL_RGB, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_RED", GL_RED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_R8", GL_R8, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_DEPTH24_STENCIL8", GL_DEPTH24_STENCIL8, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_TEXTURE_MIN_FILTER", GL_TEXTURE_MIN_FILTER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_TEXTURE_MAG_FILTER", GL_TEXTURE_MAG_FILTER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_TEXTURE_WRAP_S", GL_TEXTURE_WRAP_S, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_TEXTURE_WRAP_T", GL_TEXTURE_WRAP_T, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_NEAREST", GL_NEAREST, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_LINEAR", GL_LINEAR, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_CLAMP_TO_EDGE", GL_CLAMP_TO_EDGE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_UNPACK_ALIGNMENT", GL_UNPACK_ALIGNMENT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_UNPACK_ROW_LENGTH", GL_UNPACK_ROW_LENGTH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_PACK_ALIGNMENT", GL_PACK_ALIGNMENT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_PACK_ROW_LENGTH", GL_PACK_ROW_LENGTH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_UNPACK_SKIP_ROWS", GL_UNPACK_SKIP_ROWS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_UNPACK_SKIP_PIXELS", GL_UNPACK_SKIP_PIXELS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_PACK_SKIP_ROWS", GL_PACK_SKIP_ROWS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_PACK_SKIP_PIXELS", GL_PACK_SKIP_PIXELS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_FRAMEBUFFER", GL_FRAMEBUFFER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_READ_FRAMEBUFFER", GL_READ_FRAMEBUFFER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_DRAW_FRAMEBUFFER", GL_DRAW_FRAMEBUFFER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_RENDERBUFFER", GL_RENDERBUFFER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_COLOR_ATTACHMENT0", GL_COLOR_ATTACHMENT0, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_DEPTH_STENCIL_ATTACHMENT", GL_DEPTH_STENCIL_ATTACHMENT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_FRAMEBUFFER_COMPLETE", GL_FRAMEBUFFER_COMPLETE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_COLOR_BUFFER_BIT", GL_COLOR_BUFFER_BIT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_DEPTH_BUFFER_BIT", GL_DEPTH_BUFFER_BIT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_STENCIL_BUFFER_BIT", GL_STENCIL_BUFFER_BIT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_PIXEL_PACK_BUFFER_BINDING", GL_PIXEL_PACK_BUFFER_BINDING, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_DRAW_FRAMEBUFFER_BINDING", GL_DRAW_FRAMEBUFFER_BINDING, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_READ_FRAMEBUFFER_BINDING", GL_READ_FRAMEBUFFER_BINDING, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_BLEND", GL_BLEND, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_SCISSOR_TEST", GL_SCISSOR_TEST, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_STENCIL_TEST", GL_STENCIL_TEST, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_DEPTH_TEST", GL_DEPTH_TEST, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_CULL_FACE", GL_CULL_FACE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_SRC_ALPHA", GL_SRC_ALPHA, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_ONE_MINUS_SRC_ALPHA", GL_ONE_MINUS_SRC_ALPHA, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_ONE", GL_ONE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_ZERO", GL_ZERO, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_FUNC_ADD", GL_FUNC_ADD, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_ALWAYS", GL_ALWAYS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_NEVER", GL_NEVER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_EQUAL", GL_EQUAL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_NOTEQUAL", GL_NOTEQUAL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_KEEP", GL_KEEP, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_REPLACE", GL_REPLACE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_INVERT", GL_INVERT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_INCR_WRAP", GL_INCR_WRAP, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_DECR_WRAP", GL_DECR_WRAP, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_FRONT", GL_FRONT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_BACK", GL_BACK, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_FRONT_AND_BACK", GL_FRONT_AND_BACK, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_CW", GL_CW, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_CCW", GL_CCW, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_TRIANGLES", GL_TRIANGLES, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_TRIANGLE_STRIP", GL_TRIANGLE_STRIP, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_TRIANGLE_FAN", GL_TRIANGLE_FAN, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_LINES", GL_LINES, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GL_POINTS", GL_POINTS, CONST_PERSISTENT);
}

static zend_class_entry *register_class_GLsync(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "GLsync", class_GLsync_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}
