// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace OpenGL\GL\GL31;

class GL31
{
    public static function glDrawArraysInstanced(int mode, int first, int count, int instancecount) -> void
    {
        gl31_gldrawarraysinstanced(mode, first, count, instancecount);
    }

    public static function glDrawElementsInstanced(int mode, int count, int type, int indices, int instancecount) -> void
    {
        gl31_gldrawelementsinstanced(mode, count, type, indices, instancecount);
    }

    public static function glTexBuffer(int target, int internalformat, int buffer) -> void
    {
        gl31_gltexbuffer(target, internalformat, buffer);
    }

    public static function glPrimitiveRestartIndex(int index) -> void
    {
        gl31_glprimitiverestartindex(index);
    }

    public static function glCopyBufferSubData(int readTarget, int writeTarget, int readOffset, int writeOffset, int size) -> void
    {
        gl31_glcopybuffersubdata(readTarget, writeTarget, readOffset, writeOffset, size);
    }

    public static function glGetUniformIndices(int program, int uniformCount, array uniformNames, int uniformIndices) -> void
    {
        gl31_glgetuniformindices(program, uniformCount, uniformNames, uniformIndices);
    }

    public static function glGetActiveUniformsiv(int program, int uniformCount, int uniformIndices, int pname, int params) -> void
    {
        gl31_glgetactiveuniformsiv(program, uniformCount, uniformIndices, pname, params);
    }

    public static function glGetActiveUniformName(int program, int uniformIndex, int bufSize, int length, int uniformName) -> void
    {
        gl31_glgetactiveuniformname(program, uniformIndex, bufSize, length, uniformName);
    }

    public static function glGetUniformBlockIndex(int program, string uniformBlockName) -> int
    {
        return gl31_glgetuniformblockindex(program, uniformBlockName);
    }

    public static function glGetActiveUniformBlockiv(int program, int uniformBlockIndex, int pname, int params) -> void
    {
        gl31_glgetactiveuniformblockiv(program, uniformBlockIndex, pname, params);
    }

    public static function glGetActiveUniformBlockName(int program, int uniformBlockIndex, int bufSize, int length, int uniformBlockName) -> void
    {
        gl31_glgetactiveuniformblockname(program, uniformBlockIndex, bufSize, length, uniformBlockName);
    }

    public static function glUniformBlockBinding(int program, int uniformBlockIndex, int uniformBlockBinding) -> void
    {
        gl31_gluniformblockbinding(program, uniformBlockIndex, uniformBlockBinding);
    }
}
