#!/usr/bin/env php
<?php
/**
 * gen-gl-src.php — translate the vendored Khronos headers (and, on Darwin,
 * the live OpenGL.framework CGL headers) into src/*.h and src/*.c.
 *
 * Nothing in src/gl-*.{h,c}, src/egl.{h,c}, src/cgl.{h,c},
 * src/gl-types.{h} or src/phpgl-registry.{h,c} is hand-written. The headers
 * are the single source of truth for what exists; this script is the single
 * source of truth for how it crosses into PHP. The annotations it emits are
 * then the input to scripts/gen-zep.php.
 *
 * What it emits, per bound prototype:
 *
 *   - one binding annotation line in src/<file>.h, immediately above
 *   - one C prototype, whose body in src/<file>.c resolves the entry point
 *     through the Bridge loader and makes exactly one call through it.
 *
 * Surface (design decision D1):
 *   glcorearb.h GL_VERSION_1_0 .. GL_VERSION_4_1 -> OpenGL\GL\GL10\GL10 ..
 *   OpenGL\GL\GL41\GL41, one static class per version block, method name =
 *   the GL function name verbatim. Blocks 4.2 .. 4.6 are a deferred wave and
 *   are not emitted. Extension blocks (GL_ARB_..., GL_NV_..., ...) are out
 *   of scope entirely.
 *   egl.h EGL_VERSION_1_0 .. 1_5 -> OpenGL\EGL\EGL.
 *   OpenGL.framework CGL -> OpenGL\CGL\CGL.
 *
 * Marshalling (design decision D2) — the whole table, no per-function
 * judgement anywhere:
 *
 *   GLenum GLint GLuint GLsizei GLbitfield GLintptr GLsizeiptr GLint64
 *   GLuint64 GLshort GLushort GLbyte GLubyte GLsync          -> int
 *   GLfloat GLdouble GLclampf GLclampd                       -> double
 *   GLboolean                                                -> bool
 *   const GLchar *                                           -> string
 *   const GLchar *const *                                    -> array
 *   const GLubyte * (return only)                            -> var
 *   every other pointer, in or out, const or not             -> int
 *                                                               (raw pointer
 *                                                               bits, 0 =
 *                                                               NULL)
 *
 * A prototype this table cannot express becomes a visible @reserved line,
 * counted by the audit toward its class's header total — never a silent
 * absence. Exactly two kinds qualify (see reservationFor): a callback
 * parameter, and a type owned by a framework this binding does not include.
 * Anything ELSE the table does not cover is a hard failure that names the
 * type, so a new scalar spelling cannot quietly shrink the surface.
 *
 * Usage:  php scripts/gen-gl-src.php [--check]
 *   --check  generate into memory and diff against the tree; exit non-zero
 *            on any difference (idempotence guard).
 */

declare(strict_types=1);

const GENERATED_MARK = 'GENERATED by scripts/gen-gl-src.php';

/** Version blocks bound by this wave. 4.2 .. 4.6 are deferred; see the OKF. */
const GL_MAX_MAJOR = 4;
const GL_MAX_MINOR = 1;

/**
 * Live CGL headers, Darwin only. Preferred order: SDK, then the system.
 *
 * The design named the first four; CGLDevice.h and CGLIOSurface.h are here
 * because they declare three more CGL functions, and a function that is
 * neither bound nor reserved nor counted is exactly the silent omission the
 * house rule forbids.
 */
const CGL_HEADER_FILES = [
    'OpenGL.h', 'CGLCurrent.h', 'CGLTypes.h', 'CGLContext.h',
    'CGLDevice.h', 'CGLIOSurface.h',
];

/**
 * Types that belong to a framework this binding deliberately does not
 * include. The pointer rule would happily send them across as bits, but this
 * extension will not fabricate the ABI of a framework it has no seam with,
 * so a prototype using one is reserved with its reason rather than bound.
 *
 * CGLShareGroupObj is NOT here: it is declared in CGLDevice.h itself and is
 * an ordinary CGL opaque handle, so the pointer rule covers it and it binds
 * like CGLContextObj does.
 */
const FOREIGN_TYPES = [
    'cl_device_id' => 'OpenCL',
    'IOSurfaceRef' => 'IOSurface.framework',
];

/** C keywords a header parameter name may collide with. */
const C_RESERVED = [
    'auto', 'break', 'case', 'char', 'const', 'continue', 'default', 'do',
    'double', 'else', 'enum', 'extern', 'float', 'for', 'goto', 'if',
    'inline', 'int', 'long', 'register', 'restrict', 'return', 'short',
    'signed', 'sizeof', 'static', 'struct', 'switch', 'typedef', 'union',
    'unsigned', 'void', 'volatile', 'while', 'near', 'far', 'this',
];

function fail(string $msg): never
{
    fwrite(STDERR, "gen-gl-src: {$msg}\n");
    exit(1);
}

function cName(string $name): string
{
    return in_array(strtolower($name), C_RESERVED, true) ? $name . '_' : $name;
}

// ---------------------------------------------------------------- type table

/**
 * @return array{zep: string, cast: string}|null  null = unsupported
 */
function mapParam(string $type): ?array
{
    $type = preg_replace('/\s+/', ' ', trim($type));

    static $ints = [
        'GLenum', 'GLint', 'GLuint', 'GLsizei', 'GLbitfield', 'GLintptr',
        'GLsizeiptr', 'GLint64', 'GLuint64', 'GLshort', 'GLushort', 'GLbyte',
        'GLubyte', 'GLfixed', 'GLhalf',
        'EGLint', 'EGLenum', 'EGLTime', 'EGLBoolean',
        'GLsizeiptrARB', 'GLintptrARB',
    ];
    static $doubles = ['GLfloat', 'GLdouble', 'GLclampf', 'GLclampd'];

    if (in_array($type, $ints, true)) {
        return ['zep' => 'int', 'cast' => "({$type}) phpgl_arg_long(%s)"];
    }
    if (in_array($type, $doubles, true)) {
        return ['zep' => 'double', 'cast' => "({$type}) phpgl_arg_double(%s)"];
    }
    if ($type === 'GLboolean') {
        return ['zep' => 'bool', 'cast' => '(GLboolean) phpgl_arg_bool(%s)'];
    }
    if ($type === 'const GLchar *') {
        return ['zep' => 'string', 'cast' => '(const GLchar *) phpgl_arg_string(%s)'];
    }
    if ($type === 'const char *') {
        return ['zep' => 'string', 'cast' => '(const char *) phpgl_arg_string(%s)'];
    }
    if ($type === 'const GLchar *const *') {
        // Handled separately by the strv path; the cast is never used.
        return ['zep' => 'array', 'cast' => ''];
    }
    // GLsync and every opaque EGL/CGL handle are pointers under the skin.
    if ($type === 'GLsync' || preg_match('/(Obj|EGLDisplay|EGLConfig|EGLContext|EGLSurface|EGLSync|EGLImage|EGLClientBuffer|EGLNativeDisplayType|EGLNativeWindowType|EGLNativePixmapType)$/', $type)) {
        return ['zep' => 'int', 'cast' => "({$type}) phpgl_arg_ptr(%s)"];
    }
    if (str_ends_with($type, '*')) {
        return ['zep' => 'int', 'cast' => "({$type}) phpgl_arg_ptr(%s)"];
    }
    // CGL and EGL enums are plain ints under the skin.
    if (preg_match('/^(CGL[A-Za-z]+|EGL[A-Za-z]+)$/', $type)) {
        return ['zep' => 'int', 'cast' => "({$type}) phpgl_arg_long(%s)"];
    }

    return null;
}

/**
 * @return array{zep: string, emit: string}|null
 *   emit is a printf template taking the full call expression.
 */
function mapReturn(string $type): ?array
{
    $type = preg_replace('/\s+/', ' ', trim($type));

    if ($type === 'void') {
        return ['zep' => 'void', 'emit' => "    %s;"];
    }
    if ($type === 'GLboolean') {
        return ['zep' => 'bool', 'emit' => "    return %s ? 1 : 0;"];
    }
    if ($type === 'EGLBoolean') {
        return ['zep' => 'bool', 'emit' => "    return %s ? 1 : 0;"];
    }
    if (in_array($type, ['GLenum', 'GLint', 'GLuint', 'GLsizei', 'GLbitfield', 'EGLint', 'EGLenum', 'CGLError'], true)) {
        return ['zep' => 'int', 'emit' => "    return (zend_long) %s;"];
    }
    if ($type === 'const GLubyte *') {
        return ['zep' => 'var', 'emit' => "    phpgl_ret_ubytes(return_value, %s);"];
    }
    if ($type === 'const char *') {
        return ['zep' => 'var', 'emit' => "    phpgl_ret_string(return_value, %s);"];
    }
    if ($type === 'GLsync' || str_ends_with($type, '*') || str_ends_with($type, 'Obj')
        || $type === '__eglMustCastToProperFunctionPointerType'
        || preg_match('/^EGL(Display|Context|Surface|Config|Sync|Image|ClientBuffer)$/', $type)) {
        return ['zep' => 'int', 'emit' => "    return (zend_long) (uintptr_t) %s;"];
    }

    return null;
}

// ---------------------------------------------------------------- GL parsing

/**
 * @return array{protos: list<array<string,mixed>>, typedefs: list<string>, blocks: array<string,int>}
 */
function parseGl(string $path): array
{
    $lines = file($path, FILE_IGNORE_NEW_LINES);
    if ($lines === false) {
        fail("cannot read {$path}");
    }

    $protos = [];
    $baseTypedefs = [];
    $pfnTypedefs = [];
    $blocks = [];
    $cur = null;
    $curVer = null;

    foreach ($lines as $i => $line) {
        if (preg_match('/^#ifndef (GL_VERSION_(\d+)_(\d+))$/', $line, $m)) {
            $cur = $m[1];
            $curVer = [(int) $m[2], (int) $m[3]];
            if (versionGt($curVer, [GL_MAX_MAJOR, GL_MAX_MINOR])) {
                $cur = null;
            } else {
                $blocks[$m[1]] = 0;
            }
            continue;
        }
        if (preg_match('~^#endif /\* GL_VERSION_\d+_\d+ \*/~', $line)) {
            $cur = null;
            $curVer = null;
            continue;
        }
        if ($cur === null) {
            continue;
        }

        if (preg_match('/^typedef .*\bGL[A-Za-z0-9_]*;$/', $line) && !str_contains($line, 'APIENTRYP')) {
            $baseTypedefs[] = $line;
            continue;
        }
        if (preg_match('/^typedef .*\(APIENTRYP (PFNGL\w+)\).*;$/', $line, $m)) {
            $pfnTypedefs[$m[1]] = $line;
            continue;
        }
        if (!str_starts_with($line, 'GLAPI ')) {
            continue;
        }
        if (!preg_match('/^GLAPI\s+(.+?)\s*APIENTRY\s+(\w+)\s*\((.*)\);$/', $line, $m)) {
            fail("{$path}:" . ($i + 1) . " unparseable GLAPI line: {$line}");
        }
        [, $ret, $name, $args] = $m;
        $pfn = 'PFNGL' . strtoupper(substr($name, 2)) . 'PROC';
        $protos[] = [
            'family' => 'gl',
            'block' => $cur,
            'major' => $curVer[0],
            'minor' => $curVer[1],
            'ret' => trim($ret),
            'name' => $name,
            'args' => splitArgs($args, $name, $path, $i + 1),
            'pfn' => $pfn,
            'line' => $i + 1,
        ];
        $blocks[$cur]++;
    }

    // Every bound prototype must have the header's own PFN typedef (D1).
    $kept = [];
    foreach ($protos as $p) {
        if (!isset($pfnTypedefs[$p['pfn']])) {
            fail("{$p['name']}: the vendored header has no {$p['pfn']} typedef");
        }
        $kept[$p['pfn']] = $pfnTypedefs[$p['pfn']];
    }

    return [
        'protos' => $protos,
        'typedefs' => array_merge($baseTypedefs, array_values($kept)),
        'blocks' => $blocks,
    ];
}

function versionGt(array $a, array $b): bool
{
    return $a[0] > $b[0] || ($a[0] === $b[0] && $a[1] > $b[1]);
}

/**
 * @return list<array{type: string, name: string}>
 */
function splitArgs(string $args, string $fn, string $path, int $line): array
{
    $args = trim($args);
    if ($args === '' || $args === 'void') {
        return [];
    }
    $out = [];
    foreach (explode(',', $args) as $a) {
        $a = trim($a);
        if (!preg_match('/^(.*?)(\*?\s*)(\w+)$/', $a, $m)) {
            fail("{$path}:{$line} {$fn}: unparseable parameter '{$a}'");
        }
        $type = preg_replace('/\s+/', ' ', trim($m[1] . ' ' . trim($m[2])));
        $out[] = ['type' => $type, 'name' => $m[3]];
    }

    return $out;
}

// --------------------------------------------------------------- EGL parsing

function parseEgl(string $path): array
{
    $lines = file($path, FILE_IGNORE_NEW_LINES);
    if ($lines === false) {
        fail("cannot read {$path}");
    }

    $protos = [];
    $blocks = [];
    $cur = null;

    foreach ($lines as $i => $line) {
        if (preg_match('/^#ifndef (EGL_VERSION_(\d+)_(\d+))$/', $line, $m)) {
            $cur = $m[1];
            $blocks[$cur] = 0;
            continue;
        }
        if (preg_match('~^#endif /\* EGL_VERSION_\d+_\d+ \*/~', $line)) {
            $cur = null;
            continue;
        }
        if ($cur === null || !str_starts_with($line, 'EGLAPI ')) {
            continue;
        }
        if (!preg_match('/^EGLAPI\s+(.+?)\s*EGLAPIENTRY\s+(\w+)\s*\((.*)\);$/', $line, $m)) {
            fail("{$path}:" . ($i + 1) . " unparseable EGLAPI line: {$line}");
        }
        [, $ret, $name, $args] = $m;
        $protos[] = [
            'family' => 'egl',
            'block' => $cur,
            'major' => 0,
            'minor' => 0,
            'ret' => trim($ret),
            'name' => $name,
            'args' => splitArgs($args, $name, $path, $i + 1),
            'pfn' => 'PHPGL_PFN_' . $name,
            'line' => $i + 1,
        ];
        $blocks[$cur]++;
    }

    return ['protos' => $protos, 'blocks' => $blocks];
}

// --------------------------------------------------------------- CGL parsing

/** @return string|null the directory holding the live CGL headers */
function cglHeaderDir(): ?string
{
    $candidates = [];
    $sdk = trim((string) @shell_exec('xcrun --show-sdk-path 2>/dev/null'));
    if ($sdk !== '') {
        $candidates[] = $sdk . '/System/Library/Frameworks/OpenGL.framework/Headers';
    }
    $candidates[] = '/System/Library/Frameworks/OpenGL.framework/Headers';
    foreach ($candidates as $dir) {
        if (is_file($dir . '/OpenGL.h')) {
            return $dir;
        }
    }

    return null;
}

/**
 * Blank out comments and preprocessor lines, keeping newlines so a
 * statement's line number survives.
 */
function cglStrip(string $src): string
{
    // Block comments.
    $src = preg_replace_callback('~/\*.*?\*/~s', static function (array $m): string {
        return str_repeat(' ', strlen($m[0]) - substr_count($m[0], "\n"))
            . str_repeat("\n", substr_count($m[0], "\n"));
    }, $src);
    // Line comments.
    $src = preg_replace('~//[^\n]*~', '', $src);
    // Preprocessor lines (possibly continued with a trailing backslash).
    $src = preg_replace('/^[ \t]*#(?:[^\n\\\\]|\\\\.)*$/m', '', $src);

    return $src;
}

/**
 * CGL declarations are C statements, and at least one of them
 * (CGLTexImageIOSurface2D) is wrapped across two lines. So statements are
 * accumulated to their semicolon rather than matched per line.
 */
function parseCgl(string $dir): array
{
    $protos = [];
    $blocks = [];

    foreach (CGL_HEADER_FILES as $file) {
        $path = $dir . '/' . $file;
        $blocks[$file] = 0;
        $src = file_get_contents($path);
        if ($src === false) {
            fail("cannot read {$path}");
        }
        $src = cglStrip($src);

        $statement = '';
        $startLine = 1;
        $line = 1;
        $len = strlen($src);
        for ($i = 0; $i < $len; $i++) {
            $ch = $src[$i];
            if ($statement === '' && !ctype_space($ch)) {
                $startLine = $line;
            }
            if ($ch === "\n") {
                $line++;
            }
            if ($ch !== ';') {
                $statement .= $ch;
                continue;
            }

            $p = cglStatementToProto(cglClean($statement), $file, $path, $startLine);
            if ($p !== null) {
                $protos[] = $p;
                $blocks[$file]++;
            }
            $statement = '';
        }
    }

    return ['protos' => $protos, 'blocks' => $blocks];
}

/** @return array<string,mixed>|null null when the statement is not a function */
function cglStatementToProto(string $statement, string $file, string $path, int $line): ?array
{
    if ($statement === '' || str_contains($statement, 'typedef')) {
        return null;
    }
    // Apple's decorations are already gone, so the only parentheses left in a
    // declaration are its parameter list.
    if (!preg_match('/^(\S.*?\bCGL\w+)\s*\((.*)\)$/', $statement, $m)) {
        return null;
    }
    if (!preg_match('/^(.*?)(\bCGL\w+)$/', $m[1], $hm)) {
        return null;
    }
    $ret = trim($hm[1]);
    if ($ret === '') {
        return null;
    }

    return [
        'family' => 'cgl',
        'block' => $file,
        'major' => 0,
        'minor' => 0,
        'ret' => $ret,
        'name' => $hm[2],
        'args' => splitArgs($m[2], $hm[2], $path, $line),
        'pfn' => 'PHPGL_PFN_' . $hm[2],
        'line' => $line,
    ];
}

/**
 * Strip Apple's decorations, `extern` (including `extern "C"`) and stray
 * braces, then collapse whitespace. Any OPENGL_* macro taking arguments goes
 * with its argument list, so the only parentheses left in a declaration are
 * its own parameter list.
 */
function cglClean(string $s): string
{
    $s = preg_replace('/\bOPENGL_\w+\s*\([^)]*\)/', '', $s);
    $s = preg_replace('/\bOPENGL_\w+\b/', '', $s);
    $s = preg_replace('/\bextern\s*"C"/', '', $s);
    $s = preg_replace('/\bextern\b/', '', $s);
    $s = str_replace(['{', '}'], ' ', $s);
    $s = preg_replace('/\s+/', ' ', $s);

    return trim($s);
}

// ------------------------------------------------------------------ emitters

function classFor(array $p): string
{
    if ($p['family'] === 'gl') {
        return 'GL\\GL' . $p['major'] . $p['minor'];
    }

    return $p['family'] === 'egl' ? 'EGL\\EGL' : 'CGL\\CGL';
}

function symbolFor(array $p): string
{
    $segments = explode('\\', classFor($p));
    $cls = strtolower(end($segments));

    return 'phpgl_' . $cls . '_' . strtolower($p['name']);
}

/**
 * Why this prototype cannot be bound, or null when it can.
 *
 * Two classes of unbindable, and only two, both named in the emitted
 * @reserved line:
 *
 *   callback   a function-pointer parameter (GLDEBUGPROC and friends). PHP
 *              cannot be a C callback and this extension has no callback
 *              glue, so these are never bindable.
 *   foreign    a type owned by a framework this binding does not include
 *              (see FOREIGN_TYPES).
 *
 * Anything else the type table does not cover is still a hard failure that
 * names the type. A new scalar spelling must not quietly shrink the surface
 * by being mistaken for something unbindable.
 */
function reservationFor(array $p): ?string
{
    $types = [$p['ret']];
    foreach ($p['args'] as $a) {
        $types[] = $a['type'];
    }

    foreach ($types as $type) {
        $bare = trim(str_replace(['const', '*'], '', $type));
        if (str_contains($type, 'PROC')) {
            return "{$type} is a callback; PHP cannot be a C function pointer";
        }
        if (isset(FOREIGN_TYPES[$bare])) {
            return "{$bare} belongs to " . FOREIGN_TYPES[$bare]
                . ', which this binding does not include';
        }
    }

    return null;
}

/**
 * The visible `@reserved` line for a prototype that cannot be bound. The
 * audit counts it toward the header total, so nothing is silently omitted.
 */
function renderReserved(array $p, string $reason): string
{
    $args = [];
    foreach ($p['args'] as $a) {
        $args[] = trim($a['type'] . ' ' . $a['name']);
    }
    $signature = $p['ret'] . ' ' . $p['name'] . '(' . ($args === [] ? 'void' : implode(', ', $args)) . ')';
    // The annotation is a C comment, so nothing in it may close one.
    $signature = str_replace('*/', '* /', $signature);
    $reason = str_replace('*/', '* /', $reason);

    return sprintf('/*@reserved %s %s — %s */', classFor($p), $signature, $reason);
}

/**
 * Build the annotation, prototype and body for one prototype.
 *
 * @return array{annotation: string, proto: string, body: string}
 */
function renderBinding(array $p): array
{
    $class = classFor($p);
    $symbol = symbolFor($p);

    $retMap = mapReturn($p['ret']);
    if ($retMap === null) {
        fail("{$p['name']}: unsupported return type '{$p['ret']}'");
    }

    $zepParams = [];
    $cParams = [];
    $callArgs = [];
    $strvIndex = null;

    foreach ($p['args'] as $idx => $a) {
        $map = mapParam($a['type']);
        if ($map === null) {
            fail("{$p['name']}: unsupported parameter type '{$a['type']}' ({$a['name']})");
        }
        $cn = cName($a['name']);
        $zepParams[] = $map['zep'] . ' ' . $cn;
        $cParams[] = 'zval *' . $cn;
        if ($map['zep'] === 'array') {
            if ($strvIndex !== null) {
                fail("{$p['name']}: more than one array-of-strings parameter");
            }
            $strvIndex = $idx;
            $callArgs[] = '(' . $a['type'] . ') strv';
        } else {
            $callArgs[] = sprintf($map['cast'], $cn);
        }
    }

    $annotation = sprintf(
        '/*@zep %s %s(%s) -> %s */',
        $class,
        $p['name'],
        implode(', ', $zepParams),
        $retMap['zep']
    );

    $cReturn = match ($retMap['zep']) {
        'int', 'bool' => 'zend_long',
        'double' => 'double',
        default => 'void',
    };
    $needsReturnValue = in_array($retMap['zep'], ['string', 'array', 'var'], true);
    $protoParams = $cParams;
    if ($needsReturnValue) {
        array_unshift($protoParams, 'zval *return_value');
    }
    $protoParamSrc = $protoParams === [] ? 'void' : implode(', ', $protoParams);

    $proto = "{$cReturn} {$symbol}({$protoParamSrc});";

    // ---- body ----
    $earlyReturn = match ($retMap['zep']) {
        'int', 'bool' => '        return 0;',
        'double' => '        return 0.0;',
        'var', 'string', 'array' => "        ZVAL_NULL(return_value);\n\n        return;",
        default => '        return;',
    };

    $locals = "    static phpgl_slot slot = PHPGL_SLOT_INIT;\n";
    if ($strvIndex !== null) {
        $locals .= "    char **strv = NULL;\n    int strv_n = 0;\n";
    }
    $locals .= "    {$p['pfn']} fn = ({$p['pfn']}) phpgl_entry(\"{$p['name']}\", &slot, {$p['major']}, {$p['minor']});\n";

    $call = 'fn(' . implode(', ', $callArgs) . ')';
    $emitted = sprintf($retMap['emit'], $call);

    /*
     * The strv arity guard. Every array-of-strings parameter in these
     * headers is immediately preceded by a GLsizei count; the binding
     * refuses the call when the caller's count exceeds the array it was
     * given, because GL would otherwise read past the end of it. Derived
     * from the header's parameter order, never from knowledge of a
     * specific function — a header that breaks the shape stops the
     * generator rather than being special-cased.
     */
    $guard = '';
    if ($strvIndex !== null) {
        if ($strvIndex === 0 || $p['args'][$strvIndex - 1]['type'] !== 'GLsizei') {
            fail("{$p['name']}: array-of-strings parameter is not preceded by a GLsizei count");
        }
        $countName = cName($p['args'][$strvIndex - 1]['name']);
        $arrName = cName($p['args'][$strvIndex]['name']);
        $guard = "    strv = phpgl_arg_strv({$arrName}, &strv_n);\n"
            . "    if (phpgl_arg_long({$countName}) > (zend_long) strv_n) {\n"
            . "        php_error_docref(NULL, E_WARNING,\n"
            . "            \"{$p['name']}: count exceeds the number of strings given\");\n"
            . "        phpgl_free_strv(strv, strv_n);\n\n"
            . $earlyReturn . "\n"
            . "    }\n\n";

        // The free must follow the call; a value-returning call is captured
        // first so the order stays call -> free -> return.
        if ($retMap['zep'] === 'void') {
            $emitted = "    {$call};\n    phpgl_free_strv(strv, strv_n);";
        } elseif (in_array($retMap['zep'], ['var', 'string', 'array'], true)) {
            $emitted = sprintf($retMap['emit'], $call) . "\n    phpgl_free_strv(strv, strv_n);";
        } else {
            $rt = $retMap['zep'] === 'double' ? 'double' : 'zend_long';
            $expr = match ($retMap['zep']) {
                'bool' => "{$call} ? 1 : 0",
                'double' => "(double) {$call}",
                default => "(zend_long) {$call}",
            };
            $locals .= "    {$rt} result;\n";
            $emitted = "    result = {$expr};\n    phpgl_free_strv(strv, strv_n);\n\n    return result;";
        }
    }

    $body = "{$cReturn} {$symbol}({$protoParamSrc})\n{\n"
        . $locals
        . "\n"
        . "    if (!fn) {\n{$earlyReturn}\n    }\n\n"
        . $guard
        . $emitted . "\n"
        . "}\n";

    return ['annotation' => $annotation, 'proto' => $proto, 'body' => $body];
}

function headerBanner(string $title, string $provenance): string
{
    return "/*\n"
        . " * {$title}\n"
        . " *\n"
        . " * " . GENERATED_MARK . " — DO NOT EDIT.\n"
        . " * Source of truth: {$provenance}\n"
        . " */\n\n";
}

// ---------------------------------------------------------------------- main

$root = dirname(__DIR__);
$check = in_array('--check', array_slice($argv, 1), true);

$glPath = "{$root}/scripts/khronos/glcorearb.h";
$eglPath = "{$root}/scripts/khronos/egl.h";
is_file($glPath) || fail("missing {$glPath}");
is_file($eglPath) || fail("missing {$eglPath}");

$gl = parseGl($glPath);
$egl = parseEgl($eglPath);

$cglDir = cglHeaderDir();
$cgl = null;
if ($cglDir !== null) {
    $cgl = parseCgl($cglDir);
}

$files = [];
/** Prototypes that actually became bindings; reserved ones are not entry points. */
$boundProtos = [];
$reservedCount = 0;

// ---- src/gl-types.h ----
$typesOut = headerBanner(
    'gl-types.h — the GL types and PFNGL...PROC typedefs this binding calls through.',
    'scripts/khronos/glcorearb.h, blocks GL_VERSION_1_0 .. GL_VERSION_4_1'
);
$typesOut .= <<<'PRE'
#ifndef PHPGL_GL_TYPES_H
#define PHPGL_GL_TYPES_H

/*
 * The vendored header reaches its fixed-width types through
 * <KHR/khrplatform.h>, which is not present on every box this extension
 * builds on. The shim below is that file's contract expressed in <stdint.h>,
 * so the typedef lines copied out of glcorearb.h below are byte-identical to
 * the ones the driver was built against.
 */
#include <stdint.h>
#include <stddef.h>
#include <sys/types.h>

typedef float khronos_float_t;
typedef int8_t khronos_int8_t;
typedef uint8_t khronos_uint8_t;
typedef int16_t khronos_int16_t;
typedef uint16_t khronos_uint16_t;
typedef int64_t khronos_int64_t;
typedef uint64_t khronos_uint64_t;
typedef intptr_t khronos_intptr_t;
typedef ssize_t khronos_ssize_t;

#ifndef APIENTRY
#define APIENTRY
#endif
#ifndef APIENTRYP
#define APIENTRYP APIENTRY *
#endif

PRE;
$typesOut .= "\n/* ---- copied verbatim from the vendored header ---- */\n\n";
$typesOut .= implode("\n", $gl['typedefs']) . "\n";
$typesOut .= "\n#endif /* PHPGL_GL_TYPES_H */\n";
$files['src/gl-types.h'] = $typesOut;

// ---- src/gl-XY.{h,c} ----
$byBlock = [];
foreach ($gl['protos'] as $p) {
    $byBlock['gl-' . $p['major'] . $p['minor']][] = $p;
}
foreach ($byBlock as $stem => $protos) {
    $class = classFor($protos[0]);
    $block = $protos[0]['block'];
    $prov = "scripts/khronos/glcorearb.h, {$block} ("
        . count($protos) . ' prototypes)';

    $h = headerBanner("{$stem}.h — OpenGL\\{$class} bound 1:1.", $prov);
    $h .= "#ifndef PHPGL_" . strtoupper(str_replace('-', '_', $stem)) . "_H\n";
    $h .= "#define PHPGL_" . strtoupper(str_replace('-', '_', $stem)) . "_H\n\n";
    $h .= "#include <php.h>\n\n";
    $h .= "/*@audit block {$class} {$block} " . count($protos) . " */\n\n";

    $c = headerBanner("{$stem}.c — one call through the Bridge loader per binding.", $prov);
    $c .= "#include \"{$stem}.h\"\n#include \"gl-types.h\"\n#include \"phpgl-bridge.h\"\n#include \"phpgl-support.h\"\n\n";

    foreach ($protos as $p) {
        $reason = reservationFor($p);
        if ($reason !== null) {
            $h .= renderReserved($p, $reason) . "\n\n";
            $reservedCount++;
            continue;
        }
        $r = renderBinding($p);
        $h .= "{$r['annotation']}\n{$r['proto']}\n\n";
        $c .= "{$r['body']}\n";
        $boundProtos[] = $p;
    }

    $h .= "#endif\n";
    $files["src/{$stem}.h"] = $h;
    $files["src/{$stem}.c"] = $c;
}

// ---- src/egl.{h,c} ----
$eglProv = 'scripts/khronos/egl.h, EGL_VERSION_1_0 .. EGL_VERSION_1_5 ('
    . count($egl['protos']) . ' prototypes)';
$h = headerBanner('egl.h — OpenGL\\EGL\\EGL bound 1:1.', $eglProv);
$h .= "#ifndef PHPGL_EGL_H\n#define PHPGL_EGL_H\n\n#include <php.h>\n\n";
foreach ($egl['blocks'] as $block => $n) {
    $h .= "/*@audit block EGL\\EGL {$block} {$n} */\n";
}
$h .= "\n";
$c = headerBanner('egl.c — one call through the Bridge loader per binding.', $eglProv);
$c .= "#include \"egl.h\"\n#include \"egl-types.h\"\n#include \"phpgl-bridge.h\"\n#include \"phpgl-support.h\"\n\n";
$eglTypedefs = [];
foreach ($egl['protos'] as $p) {
    $reason = reservationFor($p);
    if ($reason !== null) {
        $h .= renderReserved($p, $reason) . "\n\n";
        $reservedCount++;
        continue;
    }
    $r = renderBinding($p);
    $h .= "{$r['annotation']}\n{$r['proto']}\n\n";
    $c .= "{$r['body']}\n";
    $eglTypedefs[] = synthTypedef($p);
    $boundProtos[] = $p;
}
$h .= "#endif\n";
$files['src/egl.h'] = $h;
$files['src/egl.c'] = $c;

$files['src/egl-types.h'] = headerBanner(
    'egl-types.h — the EGL types and function-pointer typedefs this binding calls through.',
    $eglProv
) . "#ifndef PHPGL_EGL_TYPES_H\n#define PHPGL_EGL_TYPES_H\n\n"
    . "#include <stdint.h>\n#include <stddef.h>\n\n"
    . eglBaseTypes()
    . "\n/* ---- one function-pointer typedef per bound prototype ---- */\n\n"
    . implode("\n", $eglTypedefs) . "\n"
    . "\n#endif /* PHPGL_EGL_TYPES_H */\n";

// ---- src/cgl.{h,c} ----
if ($cgl !== null) {
    $cglProv = 'OpenGL.framework/Headers/{' . implode(',', CGL_HEADER_FILES) . '} ('
        . count($cgl['protos']) . ' prototypes)';
    $h = headerBanner('cgl.h — OpenGL\\CGL\\CGL bound 1:1.', $cglProv);
    $h .= "#ifndef PHPGL_CGL_H\n#define PHPGL_CGL_H\n\n#include <php.h>\n\n";
    foreach ($cgl['blocks'] as $block => $n) {
        $h .= "/*@audit block CGL\\CGL {$block} {$n} */\n";
    }
    $h .= "\n";
    $c = headerBanner('cgl.c — one call through the Bridge loader per binding.', $cglProv);
    $c .= "#include \"cgl.h\"\n#include \"cgl-types.h\"\n#include \"phpgl-bridge.h\"\n#include \"phpgl-support.h\"\n\n";
    $cglTypedefs = [];
    foreach ($cgl['protos'] as $p) {
        $reason = reservationFor($p);
        if ($reason !== null) {
            $h .= renderReserved($p, $reason) . "\n\n";
            $reservedCount++;
            continue;
        }
        $r = renderBinding($p);
        $h .= "{$r['annotation']}\n{$r['proto']}\n\n";
        $c .= "{$r['body']}\n";
        $cglTypedefs[] = synthTypedef($p);
        $boundProtos[] = $p;
    }
    $h .= "#endif\n";
    $files['src/cgl.h'] = $h;
    $files['src/cgl.c'] = $c;

    $files['src/cgl-types.h'] = headerBanner(
        'cgl-types.h — the CGL types and function-pointer typedefs this binding calls through.',
        $cglProv
    ) . "#ifndef PHPGL_CGL_TYPES_H\n#define PHPGL_CGL_TYPES_H\n\n"
        . "#include <stdint.h>\n#include <stddef.h>\n\n"
        . cglBaseTypes()
        . "\n/* ---- one function-pointer typedef per bound prototype ---- */\n\n"
        . implode("\n", $cglTypedefs) . "\n"
        . "\n#endif /* PHPGL_CGL_TYPES_H */\n";
}

// ---- src/phpgl-registry.{h,c} ----
// Only bound prototypes are entry points; a reserved one has no binding to
// gate, so it gets no row.
$rows = [];
foreach ($boundProtos as $p) {
    $rows[] = "    {\"{$p['name']}\", {$p['major']}, {$p['minor']}},";
}
$files['src/phpgl-registry.h'] = headerBanner(
    'phpgl-registry.h — every bound entry point and the version it first appeared in.',
    'scripts/khronos/*.h and OpenGL.framework/Headers'
) . "#ifndef PHPGL_REGISTRY_H\n#define PHPGL_REGISTRY_H\n\n"
    . "typedef struct {\n    const char *name;\n    int major;\n    int minor;\n} phpgl_entry_row;\n\n"
    . "extern const phpgl_entry_row phpgl_entry_table[];\n"
    . "extern const int phpgl_entry_table_size;\n\n"
    . "#endif /* PHPGL_REGISTRY_H */\n";

$files['src/phpgl-registry.c'] = headerBanner(
    'phpgl-registry.c — the version gate\'s data. Bridge::isAvailable reads it.',
    'scripts/khronos/*.h and OpenGL.framework/Headers'
) . "#include \"phpgl-registry.h\"\n#include <string.h>\n\n"
    . "const phpgl_entry_row phpgl_entry_table[] = {\n"
    . implode("\n", $rows) . "\n};\n\n"
    . "const int phpgl_entry_table_size =\n"
    . "    (int) (sizeof(phpgl_entry_table) / sizeof(phpgl_entry_table[0]));\n\n"
    . "int phpgl_registry_version(const char *name, int *major, int *minor)\n"
    . "{\n"
    . "    int i;\n\n"
    . "    for (i = 0; i < phpgl_entry_table_size; i++) {\n"
    . "        if (strcmp(phpgl_entry_table[i].name, name) == 0) {\n"
    . "            if (major) {\n"
    . "                *major = phpgl_entry_table[i].major;\n"
    . "            }\n"
    . "            if (minor) {\n"
    . "                *minor = phpgl_entry_table[i].minor;\n"
    . "            }\n\n"
    . "            return 1;\n"
    . "        }\n"
    . "    }\n\n"
    . "    return 0;\n"
    . "}\n";

// ---- write / check ----

function synthTypedef(array $p): string
{
    $args = [];
    foreach ($p['args'] as $a) {
        $args[] = $a['type'] . ' ' . cName($a['name']);
    }
    $argSrc = $args === [] ? 'void' : implode(', ', $args);

    return "typedef {$p['ret']} (*{$p['pfn']})({$argSrc});";
}

function eglBaseTypes(): string
{
    return <<<'T'
/*
 * EGL's own <EGL/egl.h> pulls in <EGL/eglplatform.h> and the window system.
 * This binding never touches a window and resolves every entry point at
 * runtime, so it needs the ABI of these types and nothing else.
 */
typedef unsigned int EGLBoolean;
typedef unsigned int EGLenum;
typedef int32_t EGLint;
typedef void *EGLConfig;
typedef void *EGLContext;
typedef void *EGLDisplay;
typedef void *EGLSurface;
typedef void *EGLClientBuffer;
typedef void *EGLSync;
typedef void *EGLImage;
typedef void *EGLNativeDisplayType;
typedef void *EGLNativePixmapType;
typedef void *EGLNativeWindowType;
typedef intptr_t EGLAttrib;
typedef uint64_t EGLTime;
typedef void (*__eglMustCastToProperFunctionPointerType)(void);

T;
}

function cglBaseTypes(): string
{
    return <<<'T'
/*
 * <OpenGL/OpenGL.h> is Darwin-only and deprecated-annotated; this binding
 * resolves CGL at runtime like everything else, so it needs the ABI and
 * nothing else. Every CGL enum's enumerators fit in int, so int is the
 * underlying type clang gives them.
 */
typedef int CGLError;
typedef int CGLPixelFormatAttribute;
typedef int CGLRendererProperty;
typedef int CGLContextEnable;
typedef int CGLContextParameter;
typedef int CGLGlobalOption;
typedef struct _CGLContextObject *CGLContextObj;
typedef struct _CGLPixelFormatObject *CGLPixelFormatObj;
typedef struct _CGLRendererInfoObject *CGLRendererInfoObj;
typedef struct _CGLPBufferObject *CGLPBufferObj;
typedef struct CGLShareGroupRec *CGLShareGroupObj;

#ifndef PHPGL_GL_TYPES_H
typedef unsigned int GLenum;
typedef unsigned int GLuint;
typedef int GLint;
typedef int GLsizei;
typedef unsigned int GLbitfield;
#endif

T;
}

$written = 0;
$diffs = [];
foreach ($files as $rel => $contents) {
    $path = "{$root}/{$rel}";
    $existing = is_file($path) ? file_get_contents($path) : null;
    if ($existing === $contents) {
        continue;
    }
    if ($check) {
        $diffs[] = $rel;
        continue;
    }
    if (!is_dir(dirname($path))) {
        mkdir(dirname($path), 0755, true);
    }
    file_put_contents($path, $contents);
    $written++;
}

foreach ($gl['blocks'] as $block => $n) {
    printf("%-22s %4d\n", $block, $n);
}
printf("%-22s %4d\n", 'EGL_VERSION_1_0..1_5', count($egl['protos']));
if ($cgl !== null) {
    printf("%-22s %4d\n", 'CGL (live SDK)', count($cgl['protos']));
} else {
    printf("%-22s %s\n", 'CGL', 'SKIP (no OpenGL.framework on this box; src/cgl.* kept as committed)');
}

$total = count($gl['protos']) + count($egl['protos']) + ($cgl ? count($cgl['protos']) : 0);
echo 'files=' . count($files) . " written={$written} prototypes={$total}"
    . ' bound=' . count($boundProtos) . " reserved={$reservedCount}\n";

if ($check) {
    if ($diffs !== []) {
        foreach ($diffs as $d) {
            fwrite(STDERR, "gen-gl-src: {$d} differs from what the headers produce\n");
        }
        fwrite(STDERR, "GEN_SRC_DRIFT (" . count($diffs) . ")\n");
        exit(1);
    }
    echo "GEN_SRC_CLEAN\n";
    exit(0);
}

echo "GEN_SRC_OK\n";
