/*
 * cgl.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: OpenGL.framework/Headers/{OpenGL.h,CGLCurrent.h,CGLTypes.h,CGLContext.h,CGLDevice.h,CGLIOSurface.h} (52 prototypes)
 */

#include "cgl.h"
#include "cgl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

zend_long phpgl_cgl_cglchoosepixelformat(zval *attribs, zval *pix, zval *npix)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLChoosePixelFormat fn = (PHPGL_PFN_CGLChoosePixelFormat) phpgl_entry("CGLChoosePixelFormat", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((const CGLPixelFormatAttribute *) phpgl_arg_ptr(attribs), (CGLPixelFormatObj *) phpgl_arg_ptr(pix), (GLint *) phpgl_arg_ptr(npix));
}

zend_long phpgl_cgl_cgldestroypixelformat(zval *pix)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLDestroyPixelFormat fn = (PHPGL_PFN_CGLDestroyPixelFormat) phpgl_entry("CGLDestroyPixelFormat", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLPixelFormatObj) phpgl_arg_ptr(pix));
}

zend_long phpgl_cgl_cgldescribepixelformat(zval *pix, zval *pix_num, zval *attrib, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLDescribePixelFormat fn = (PHPGL_PFN_CGLDescribePixelFormat) phpgl_entry("CGLDescribePixelFormat", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLPixelFormatObj) phpgl_arg_ptr(pix), (GLint) phpgl_arg_long(pix_num), (CGLPixelFormatAttribute) phpgl_arg_long(attrib), (GLint *) phpgl_arg_ptr(value));
}

void phpgl_cgl_cglreleasepixelformat(zval *pix)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLReleasePixelFormat fn = (PHPGL_PFN_CGLReleasePixelFormat) phpgl_entry("CGLReleasePixelFormat", &slot, 0, 0);

    if (!fn) {
        return;
    }

    fn((CGLPixelFormatObj) phpgl_arg_ptr(pix));
}

zend_long phpgl_cgl_cglretainpixelformat(zval *pix)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLRetainPixelFormat fn = (PHPGL_PFN_CGLRetainPixelFormat) phpgl_entry("CGLRetainPixelFormat", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((CGLPixelFormatObj) phpgl_arg_ptr(pix));
}

zend_long phpgl_cgl_cglgetpixelformatretaincount(zval *pix)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLGetPixelFormatRetainCount fn = (PHPGL_PFN_CGLGetPixelFormatRetainCount) phpgl_entry("CGLGetPixelFormatRetainCount", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLPixelFormatObj) phpgl_arg_ptr(pix));
}

zend_long phpgl_cgl_cglqueryrendererinfo(zval *display_mask, zval *rend, zval *nrend)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLQueryRendererInfo fn = (PHPGL_PFN_CGLQueryRendererInfo) phpgl_entry("CGLQueryRendererInfo", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((GLuint) phpgl_arg_long(display_mask), (CGLRendererInfoObj *) phpgl_arg_ptr(rend), (GLint *) phpgl_arg_ptr(nrend));
}

zend_long phpgl_cgl_cgldestroyrendererinfo(zval *rend)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLDestroyRendererInfo fn = (PHPGL_PFN_CGLDestroyRendererInfo) phpgl_entry("CGLDestroyRendererInfo", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLRendererInfoObj) phpgl_arg_ptr(rend));
}

zend_long phpgl_cgl_cgldescriberenderer(zval *rend, zval *rend_num, zval *prop, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLDescribeRenderer fn = (PHPGL_PFN_CGLDescribeRenderer) phpgl_entry("CGLDescribeRenderer", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLRendererInfoObj) phpgl_arg_ptr(rend), (GLint) phpgl_arg_long(rend_num), (CGLRendererProperty) phpgl_arg_long(prop), (GLint *) phpgl_arg_ptr(value));
}

zend_long phpgl_cgl_cglcreatecontext(zval *pix, zval *share, zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLCreateContext fn = (PHPGL_PFN_CGLCreateContext) phpgl_entry("CGLCreateContext", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLPixelFormatObj) phpgl_arg_ptr(pix), (CGLContextObj) phpgl_arg_ptr(share), (CGLContextObj *) phpgl_arg_ptr(ctx));
}

zend_long phpgl_cgl_cgldestroycontext(zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLDestroyContext fn = (PHPGL_PFN_CGLDestroyContext) phpgl_entry("CGLDestroyContext", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx));
}

zend_long phpgl_cgl_cglcopycontext(zval *src, zval *dst, zval *mask)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLCopyContext fn = (PHPGL_PFN_CGLCopyContext) phpgl_entry("CGLCopyContext", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(src), (CGLContextObj) phpgl_arg_ptr(dst), (GLbitfield) phpgl_arg_long(mask));
}

zend_long phpgl_cgl_cglretaincontext(zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLRetainContext fn = (PHPGL_PFN_CGLRetainContext) phpgl_entry("CGLRetainContext", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((CGLContextObj) phpgl_arg_ptr(ctx));
}

void phpgl_cgl_cglreleasecontext(zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLReleaseContext fn = (PHPGL_PFN_CGLReleaseContext) phpgl_entry("CGLReleaseContext", &slot, 0, 0);

    if (!fn) {
        return;
    }

    fn((CGLContextObj) phpgl_arg_ptr(ctx));
}

zend_long phpgl_cgl_cglgetcontextretaincount(zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLGetContextRetainCount fn = (PHPGL_PFN_CGLGetContextRetainCount) phpgl_entry("CGLGetContextRetainCount", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx));
}

zend_long phpgl_cgl_cglgetpixelformat(zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLGetPixelFormat fn = (PHPGL_PFN_CGLGetPixelFormat) phpgl_entry("CGLGetPixelFormat", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((CGLContextObj) phpgl_arg_ptr(ctx));
}

zend_long phpgl_cgl_cglcreatepbuffer(zval *width, zval *height, zval *target, zval *internalFormat, zval *max_level, zval *pbuffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLCreatePBuffer fn = (PHPGL_PFN_CGLCreatePBuffer) phpgl_entry("CGLCreatePBuffer", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height), (GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(internalFormat), (GLint) phpgl_arg_long(max_level), (CGLPBufferObj *) phpgl_arg_ptr(pbuffer));
}

zend_long phpgl_cgl_cgldestroypbuffer(zval *pbuffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLDestroyPBuffer fn = (PHPGL_PFN_CGLDestroyPBuffer) phpgl_entry("CGLDestroyPBuffer", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLPBufferObj) phpgl_arg_ptr(pbuffer));
}

zend_long phpgl_cgl_cgldescribepbuffer(zval *obj, zval *width, zval *height, zval *target, zval *internalFormat, zval *mipmap)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLDescribePBuffer fn = (PHPGL_PFN_CGLDescribePBuffer) phpgl_entry("CGLDescribePBuffer", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLPBufferObj) phpgl_arg_ptr(obj), (GLsizei *) phpgl_arg_ptr(width), (GLsizei *) phpgl_arg_ptr(height), (GLenum *) phpgl_arg_ptr(target), (GLenum *) phpgl_arg_ptr(internalFormat), (GLint *) phpgl_arg_ptr(mipmap));
}

zend_long phpgl_cgl_cglteximagepbuffer(zval *ctx, zval *pbuffer, zval *source)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLTexImagePBuffer fn = (PHPGL_PFN_CGLTexImagePBuffer) phpgl_entry("CGLTexImagePBuffer", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx), (CGLPBufferObj) phpgl_arg_ptr(pbuffer), (GLenum) phpgl_arg_long(source));
}

zend_long phpgl_cgl_cglretainpbuffer(zval *pbuffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLRetainPBuffer fn = (PHPGL_PFN_CGLRetainPBuffer) phpgl_entry("CGLRetainPBuffer", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((CGLPBufferObj) phpgl_arg_ptr(pbuffer));
}

void phpgl_cgl_cglreleasepbuffer(zval *pbuffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLReleasePBuffer fn = (PHPGL_PFN_CGLReleasePBuffer) phpgl_entry("CGLReleasePBuffer", &slot, 0, 0);

    if (!fn) {
        return;
    }

    fn((CGLPBufferObj) phpgl_arg_ptr(pbuffer));
}

zend_long phpgl_cgl_cglgetpbufferretaincount(zval *pbuffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLGetPBufferRetainCount fn = (PHPGL_PFN_CGLGetPBufferRetainCount) phpgl_entry("CGLGetPBufferRetainCount", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLPBufferObj) phpgl_arg_ptr(pbuffer));
}

zend_long phpgl_cgl_cglsetoffscreen(zval *ctx, zval *width, zval *height, zval *rowbytes, zval *baseaddr)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLSetOffScreen fn = (PHPGL_PFN_CGLSetOffScreen) phpgl_entry("CGLSetOffScreen", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height), (GLint) phpgl_arg_long(rowbytes), (void *) phpgl_arg_ptr(baseaddr));
}

zend_long phpgl_cgl_cglgetoffscreen(zval *ctx, zval *width, zval *height, zval *rowbytes, zval *baseaddr)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLGetOffScreen fn = (PHPGL_PFN_CGLGetOffScreen) phpgl_entry("CGLGetOffScreen", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx), (GLsizei *) phpgl_arg_ptr(width), (GLsizei *) phpgl_arg_ptr(height), (GLint *) phpgl_arg_ptr(rowbytes), (void * *) phpgl_arg_ptr(baseaddr));
}

zend_long phpgl_cgl_cglsetfullscreen(zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLSetFullScreen fn = (PHPGL_PFN_CGLSetFullScreen) phpgl_entry("CGLSetFullScreen", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx));
}

zend_long phpgl_cgl_cglsetfullscreenondisplay(zval *ctx, zval *display_mask)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLSetFullScreenOnDisplay fn = (PHPGL_PFN_CGLSetFullScreenOnDisplay) phpgl_entry("CGLSetFullScreenOnDisplay", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx), (GLuint) phpgl_arg_long(display_mask));
}

zend_long phpgl_cgl_cglsetpbuffer(zval *ctx, zval *pbuffer, zval *face, zval *level, zval *screen)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLSetPBuffer fn = (PHPGL_PFN_CGLSetPBuffer) phpgl_entry("CGLSetPBuffer", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx), (CGLPBufferObj) phpgl_arg_ptr(pbuffer), (GLenum) phpgl_arg_long(face), (GLint) phpgl_arg_long(level), (GLint) phpgl_arg_long(screen));
}

zend_long phpgl_cgl_cglgetpbuffer(zval *ctx, zval *pbuffer, zval *face, zval *level, zval *screen)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLGetPBuffer fn = (PHPGL_PFN_CGLGetPBuffer) phpgl_entry("CGLGetPBuffer", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx), (CGLPBufferObj *) phpgl_arg_ptr(pbuffer), (GLenum *) phpgl_arg_ptr(face), (GLint *) phpgl_arg_ptr(level), (GLint *) phpgl_arg_ptr(screen));
}

zend_long phpgl_cgl_cglcleardrawable(zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLClearDrawable fn = (PHPGL_PFN_CGLClearDrawable) phpgl_entry("CGLClearDrawable", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx));
}

zend_long phpgl_cgl_cglflushdrawable(zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLFlushDrawable fn = (PHPGL_PFN_CGLFlushDrawable) phpgl_entry("CGLFlushDrawable", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx));
}

zend_long phpgl_cgl_cglenable(zval *ctx, zval *pname)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLEnable fn = (PHPGL_PFN_CGLEnable) phpgl_entry("CGLEnable", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx), (CGLContextEnable) phpgl_arg_long(pname));
}

zend_long phpgl_cgl_cgldisable(zval *ctx, zval *pname)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLDisable fn = (PHPGL_PFN_CGLDisable) phpgl_entry("CGLDisable", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx), (CGLContextEnable) phpgl_arg_long(pname));
}

zend_long phpgl_cgl_cglisenabled(zval *ctx, zval *pname, zval *enable)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLIsEnabled fn = (PHPGL_PFN_CGLIsEnabled) phpgl_entry("CGLIsEnabled", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx), (CGLContextEnable) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(enable));
}

zend_long phpgl_cgl_cglsetparameter(zval *ctx, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLSetParameter fn = (PHPGL_PFN_CGLSetParameter) phpgl_entry("CGLSetParameter", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx), (CGLContextParameter) phpgl_arg_long(pname), (const GLint *) phpgl_arg_ptr(params));
}

zend_long phpgl_cgl_cglgetparameter(zval *ctx, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLGetParameter fn = (PHPGL_PFN_CGLGetParameter) phpgl_entry("CGLGetParameter", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx), (CGLContextParameter) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

zend_long phpgl_cgl_cglsetvirtualscreen(zval *ctx, zval *screen)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLSetVirtualScreen fn = (PHPGL_PFN_CGLSetVirtualScreen) phpgl_entry("CGLSetVirtualScreen", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx), (GLint) phpgl_arg_long(screen));
}

zend_long phpgl_cgl_cglgetvirtualscreen(zval *ctx, zval *screen)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLGetVirtualScreen fn = (PHPGL_PFN_CGLGetVirtualScreen) phpgl_entry("CGLGetVirtualScreen", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx), (GLint *) phpgl_arg_ptr(screen));
}

zend_long phpgl_cgl_cglupdatecontext(zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLUpdateContext fn = (PHPGL_PFN_CGLUpdateContext) phpgl_entry("CGLUpdateContext", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx));
}

zend_long phpgl_cgl_cglsetglobaloption(zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLSetGlobalOption fn = (PHPGL_PFN_CGLSetGlobalOption) phpgl_entry("CGLSetGlobalOption", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLGlobalOption) phpgl_arg_long(pname), (const GLint *) phpgl_arg_ptr(params));
}

zend_long phpgl_cgl_cglgetglobaloption(zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLGetGlobalOption fn = (PHPGL_PFN_CGLGetGlobalOption) phpgl_entry("CGLGetGlobalOption", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLGlobalOption) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

zend_long phpgl_cgl_cglsetoption(zval *pname, zval *param)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLSetOption fn = (PHPGL_PFN_CGLSetOption) phpgl_entry("CGLSetOption", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLGlobalOption) phpgl_arg_long(pname), (GLint) phpgl_arg_long(param));
}

zend_long phpgl_cgl_cglgetoption(zval *pname, zval *param)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLGetOption fn = (PHPGL_PFN_CGLGetOption) phpgl_entry("CGLGetOption", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLGlobalOption) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(param));
}

zend_long phpgl_cgl_cgllockcontext(zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLLockContext fn = (PHPGL_PFN_CGLLockContext) phpgl_entry("CGLLockContext", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx));
}

zend_long phpgl_cgl_cglunlockcontext(zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLUnlockContext fn = (PHPGL_PFN_CGLUnlockContext) phpgl_entry("CGLUnlockContext", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx));
}

void phpgl_cgl_cglgetversion(zval *majorvers, zval *minorvers)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLGetVersion fn = (PHPGL_PFN_CGLGetVersion) phpgl_entry("CGLGetVersion", &slot, 0, 0);

    if (!fn) {
        return;
    }

    fn((GLint *) phpgl_arg_ptr(majorvers), (GLint *) phpgl_arg_ptr(minorvers));
}

void phpgl_cgl_cglerrorstring(zval *return_value, zval *error)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLErrorString fn = (PHPGL_PFN_CGLErrorString) phpgl_entry("CGLErrorString", &slot, 0, 0);

    if (!fn) {
        ZVAL_NULL(return_value);

        return;
    }

    phpgl_ret_string(return_value, fn((CGLError) phpgl_arg_long(error)));
}

zend_long phpgl_cgl_cglsetcurrentcontext(zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLSetCurrentContext fn = (PHPGL_PFN_CGLSetCurrentContext) phpgl_entry("CGLSetCurrentContext", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((CGLContextObj) phpgl_arg_ptr(ctx));
}

zend_long phpgl_cgl_cglgetcurrentcontext(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLGetCurrentContext fn = (PHPGL_PFN_CGLGetCurrentContext) phpgl_entry("CGLGetCurrentContext", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn();
}

zend_long phpgl_cgl_cglgetsharegroup(zval *ctx)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PHPGL_PFN_CGLGetShareGroup fn = (PHPGL_PFN_CGLGetShareGroup) phpgl_entry("CGLGetShareGroup", &slot, 0, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((CGLContextObj) phpgl_arg_ptr(ctx));
}

