/*
 * egl-types.h — the EGL types and function-pointer typedefs this binding calls through.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/egl.h, EGL_VERSION_1_0 .. EGL_VERSION_1_5 (44 prototypes)
 */

#ifndef PHPGL_EGL_TYPES_H
#define PHPGL_EGL_TYPES_H

#include <stdint.h>
#include <stddef.h>

/*
 * EGL's own <EGL/egl.h> pulls in <EGL/eglplatform.h> and the window system.
 * This binding never touches a window and resolves every entry point at
 * runtime, so it needs the ABI of these types and nothing else.
 */
typedef unsigned int EGLBoolean;
typedef unsigned int EGLenum;
typedef int32_t EGLint;
typedef void *EGLConfig;
typedef void *EGLContext;
typedef void *EGLDisplay;
typedef void *EGLSurface;
typedef void *EGLClientBuffer;
typedef void *EGLSync;
typedef void *EGLImage;
typedef void *EGLNativeDisplayType;
typedef void *EGLNativePixmapType;
typedef void *EGLNativeWindowType;
typedef intptr_t EGLAttrib;
typedef uint64_t EGLTime;
typedef void (*__eglMustCastToProperFunctionPointerType)(void);

/* ---- one function-pointer typedef per bound prototype ---- */

typedef EGLBoolean (*PHPGL_PFN_eglChooseConfig)(EGLDisplay dpy, const EGLint * attrib_list, EGLConfig * configs, EGLint config_size, EGLint * num_config);
typedef EGLBoolean (*PHPGL_PFN_eglCopyBuffers)(EGLDisplay dpy, EGLSurface surface, EGLNativePixmapType target);
typedef EGLContext (*PHPGL_PFN_eglCreateContext)(EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint * attrib_list);
typedef EGLSurface (*PHPGL_PFN_eglCreatePbufferSurface)(EGLDisplay dpy, EGLConfig config, const EGLint * attrib_list);
typedef EGLSurface (*PHPGL_PFN_eglCreatePixmapSurface)(EGLDisplay dpy, EGLConfig config, EGLNativePixmapType pixmap, const EGLint * attrib_list);
typedef EGLSurface (*PHPGL_PFN_eglCreateWindowSurface)(EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint * attrib_list);
typedef EGLBoolean (*PHPGL_PFN_eglDestroyContext)(EGLDisplay dpy, EGLContext ctx);
typedef EGLBoolean (*PHPGL_PFN_eglDestroySurface)(EGLDisplay dpy, EGLSurface surface);
typedef EGLBoolean (*PHPGL_PFN_eglGetConfigAttrib)(EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint * value);
typedef EGLBoolean (*PHPGL_PFN_eglGetConfigs)(EGLDisplay dpy, EGLConfig * configs, EGLint config_size, EGLint * num_config);
typedef EGLDisplay (*PHPGL_PFN_eglGetCurrentDisplay)(void);
typedef EGLSurface (*PHPGL_PFN_eglGetCurrentSurface)(EGLint readdraw);
typedef EGLDisplay (*PHPGL_PFN_eglGetDisplay)(EGLNativeDisplayType display_id);
typedef EGLint (*PHPGL_PFN_eglGetError)(void);
typedef __eglMustCastToProperFunctionPointerType (*PHPGL_PFN_eglGetProcAddress)(const char * procname);
typedef EGLBoolean (*PHPGL_PFN_eglInitialize)(EGLDisplay dpy, EGLint * major, EGLint * minor);
typedef EGLBoolean (*PHPGL_PFN_eglMakeCurrent)(EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx);
typedef EGLBoolean (*PHPGL_PFN_eglQueryContext)(EGLDisplay dpy, EGLContext ctx, EGLint attribute, EGLint * value);
typedef const char * (*PHPGL_PFN_eglQueryString)(EGLDisplay dpy, EGLint name);
typedef EGLBoolean (*PHPGL_PFN_eglQuerySurface)(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint * value);
typedef EGLBoolean (*PHPGL_PFN_eglSwapBuffers)(EGLDisplay dpy, EGLSurface surface);
typedef EGLBoolean (*PHPGL_PFN_eglTerminate)(EGLDisplay dpy);
typedef EGLBoolean (*PHPGL_PFN_eglWaitGL)(void);
typedef EGLBoolean (*PHPGL_PFN_eglWaitNative)(EGLint engine);
typedef EGLBoolean (*PHPGL_PFN_eglBindTexImage)(EGLDisplay dpy, EGLSurface surface, EGLint buffer);
typedef EGLBoolean (*PHPGL_PFN_eglReleaseTexImage)(EGLDisplay dpy, EGLSurface surface, EGLint buffer);
typedef EGLBoolean (*PHPGL_PFN_eglSurfaceAttrib)(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint value);
typedef EGLBoolean (*PHPGL_PFN_eglSwapInterval)(EGLDisplay dpy, EGLint interval);
typedef EGLBoolean (*PHPGL_PFN_eglBindAPI)(EGLenum api);
typedef EGLenum (*PHPGL_PFN_eglQueryAPI)(void);
typedef EGLSurface (*PHPGL_PFN_eglCreatePbufferFromClientBuffer)(EGLDisplay dpy, EGLenum buftype, EGLClientBuffer buffer, EGLConfig config, const EGLint * attrib_list);
typedef EGLBoolean (*PHPGL_PFN_eglReleaseThread)(void);
typedef EGLBoolean (*PHPGL_PFN_eglWaitClient)(void);
typedef EGLContext (*PHPGL_PFN_eglGetCurrentContext)(void);
typedef EGLSync (*PHPGL_PFN_eglCreateSync)(EGLDisplay dpy, EGLenum type, const EGLAttrib * attrib_list);
typedef EGLBoolean (*PHPGL_PFN_eglDestroySync)(EGLDisplay dpy, EGLSync sync);
typedef EGLint (*PHPGL_PFN_eglClientWaitSync)(EGLDisplay dpy, EGLSync sync, EGLint flags, EGLTime timeout);
typedef EGLBoolean (*PHPGL_PFN_eglGetSyncAttrib)(EGLDisplay dpy, EGLSync sync, EGLint attribute, EGLAttrib * value);
typedef EGLImage (*PHPGL_PFN_eglCreateImage)(EGLDisplay dpy, EGLContext ctx, EGLenum target, EGLClientBuffer buffer, const EGLAttrib * attrib_list);
typedef EGLBoolean (*PHPGL_PFN_eglDestroyImage)(EGLDisplay dpy, EGLImage image);
typedef EGLDisplay (*PHPGL_PFN_eglGetPlatformDisplay)(EGLenum platform, void * native_display, const EGLAttrib * attrib_list);
typedef EGLSurface (*PHPGL_PFN_eglCreatePlatformWindowSurface)(EGLDisplay dpy, EGLConfig config, void * native_window, const EGLAttrib * attrib_list);
typedef EGLSurface (*PHPGL_PFN_eglCreatePlatformPixmapSurface)(EGLDisplay dpy, EGLConfig config, void * native_pixmap, const EGLAttrib * attrib_list);
typedef EGLBoolean (*PHPGL_PFN_eglWaitSync)(EGLDisplay dpy, EGLSync sync, EGLint flags);

#endif /* PHPGL_EGL_TYPES_H */
