/*
 * egl.h — OpenGL\EGL\EGL bound 1:1.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/egl.h, EGL_VERSION_1_0 .. EGL_VERSION_1_5 (44 prototypes)
 */

#ifndef PHPGL_EGL_H
#define PHPGL_EGL_H

#include <php.h>

/*@audit block EGL\EGL EGL_VERSION_1_0 24 */
/*@audit block EGL\EGL EGL_VERSION_1_1 4 */
/*@audit block EGL\EGL EGL_VERSION_1_2 5 */
/*@audit block EGL\EGL EGL_VERSION_1_3 0 */
/*@audit block EGL\EGL EGL_VERSION_1_4 1 */
/*@audit block EGL\EGL EGL_VERSION_1_5 10 */

/*@zep EGL\EGL eglChooseConfig(int dpy, int attrib_list, int configs, int config_size, int num_config) -> bool */
zend_long phpgl_egl_eglchooseconfig(zval *dpy, zval *attrib_list, zval *configs, zval *config_size, zval *num_config);

/*@zep EGL\EGL eglCopyBuffers(int dpy, int surface, int target) -> bool */
zend_long phpgl_egl_eglcopybuffers(zval *dpy, zval *surface, zval *target);

/*@zep EGL\EGL eglCreateContext(int dpy, int config, int share_context, int attrib_list) -> int */
zend_long phpgl_egl_eglcreatecontext(zval *dpy, zval *config, zval *share_context, zval *attrib_list);

/*@zep EGL\EGL eglCreatePbufferSurface(int dpy, int config, int attrib_list) -> int */
zend_long phpgl_egl_eglcreatepbuffersurface(zval *dpy, zval *config, zval *attrib_list);

/*@zep EGL\EGL eglCreatePixmapSurface(int dpy, int config, int pixmap, int attrib_list) -> int */
zend_long phpgl_egl_eglcreatepixmapsurface(zval *dpy, zval *config, zval *pixmap, zval *attrib_list);

/*@zep EGL\EGL eglCreateWindowSurface(int dpy, int config, int win, int attrib_list) -> int */
zend_long phpgl_egl_eglcreatewindowsurface(zval *dpy, zval *config, zval *win, zval *attrib_list);

/*@zep EGL\EGL eglDestroyContext(int dpy, int ctx) -> bool */
zend_long phpgl_egl_egldestroycontext(zval *dpy, zval *ctx);

/*@zep EGL\EGL eglDestroySurface(int dpy, int surface) -> bool */
zend_long phpgl_egl_egldestroysurface(zval *dpy, zval *surface);

/*@zep EGL\EGL eglGetConfigAttrib(int dpy, int config, int attribute, int value) -> bool */
zend_long phpgl_egl_eglgetconfigattrib(zval *dpy, zval *config, zval *attribute, zval *value);

/*@zep EGL\EGL eglGetConfigs(int dpy, int configs, int config_size, int num_config) -> bool */
zend_long phpgl_egl_eglgetconfigs(zval *dpy, zval *configs, zval *config_size, zval *num_config);

/*@zep EGL\EGL eglGetCurrentDisplay() -> int */
zend_long phpgl_egl_eglgetcurrentdisplay(void);

/*@zep EGL\EGL eglGetCurrentSurface(int readdraw) -> int */
zend_long phpgl_egl_eglgetcurrentsurface(zval *readdraw);

/*@zep EGL\EGL eglGetDisplay(int display_id) -> int */
zend_long phpgl_egl_eglgetdisplay(zval *display_id);

/*@zep EGL\EGL eglGetError() -> int */
zend_long phpgl_egl_eglgeterror(void);

/*@zep EGL\EGL eglGetProcAddress(string procname) -> int */
zend_long phpgl_egl_eglgetprocaddress(zval *procname);

/*@zep EGL\EGL eglInitialize(int dpy, int major, int minor) -> bool */
zend_long phpgl_egl_eglinitialize(zval *dpy, zval *major, zval *minor);

/*@zep EGL\EGL eglMakeCurrent(int dpy, int draw, int read, int ctx) -> bool */
zend_long phpgl_egl_eglmakecurrent(zval *dpy, zval *draw, zval *read, zval *ctx);

/*@zep EGL\EGL eglQueryContext(int dpy, int ctx, int attribute, int value) -> bool */
zend_long phpgl_egl_eglquerycontext(zval *dpy, zval *ctx, zval *attribute, zval *value);

/*@zep EGL\EGL eglQueryString(int dpy, int name) -> var */
void phpgl_egl_eglquerystring(zval *return_value, zval *dpy, zval *name);

/*@zep EGL\EGL eglQuerySurface(int dpy, int surface, int attribute, int value) -> bool */
zend_long phpgl_egl_eglquerysurface(zval *dpy, zval *surface, zval *attribute, zval *value);

/*@zep EGL\EGL eglSwapBuffers(int dpy, int surface) -> bool */
zend_long phpgl_egl_eglswapbuffers(zval *dpy, zval *surface);

/*@zep EGL\EGL eglTerminate(int dpy) -> bool */
zend_long phpgl_egl_eglterminate(zval *dpy);

/*@zep EGL\EGL eglWaitGL() -> bool */
zend_long phpgl_egl_eglwaitgl(void);

/*@zep EGL\EGL eglWaitNative(int engine) -> bool */
zend_long phpgl_egl_eglwaitnative(zval *engine);

/*@zep EGL\EGL eglBindTexImage(int dpy, int surface, int buffer) -> bool */
zend_long phpgl_egl_eglbindteximage(zval *dpy, zval *surface, zval *buffer);

/*@zep EGL\EGL eglReleaseTexImage(int dpy, int surface, int buffer) -> bool */
zend_long phpgl_egl_eglreleaseteximage(zval *dpy, zval *surface, zval *buffer);

/*@zep EGL\EGL eglSurfaceAttrib(int dpy, int surface, int attribute, int value) -> bool */
zend_long phpgl_egl_eglsurfaceattrib(zval *dpy, zval *surface, zval *attribute, zval *value);

/*@zep EGL\EGL eglSwapInterval(int dpy, int interval) -> bool */
zend_long phpgl_egl_eglswapinterval(zval *dpy, zval *interval);

/*@zep EGL\EGL eglBindAPI(int api) -> bool */
zend_long phpgl_egl_eglbindapi(zval *api);

/*@zep EGL\EGL eglQueryAPI() -> int */
zend_long phpgl_egl_eglqueryapi(void);

/*@zep EGL\EGL eglCreatePbufferFromClientBuffer(int dpy, int buftype, int buffer, int config, int attrib_list) -> int */
zend_long phpgl_egl_eglcreatepbufferfromclientbuffer(zval *dpy, zval *buftype, zval *buffer, zval *config, zval *attrib_list);

/*@zep EGL\EGL eglReleaseThread() -> bool */
zend_long phpgl_egl_eglreleasethread(void);

/*@zep EGL\EGL eglWaitClient() -> bool */
zend_long phpgl_egl_eglwaitclient(void);

/*@zep EGL\EGL eglGetCurrentContext() -> int */
zend_long phpgl_egl_eglgetcurrentcontext(void);

/*@zep EGL\EGL eglCreateSync(int dpy, int type, int attrib_list) -> int */
zend_long phpgl_egl_eglcreatesync(zval *dpy, zval *type, zval *attrib_list);

/*@zep EGL\EGL eglDestroySync(int dpy, int sync) -> bool */
zend_long phpgl_egl_egldestroysync(zval *dpy, zval *sync);

/*@zep EGL\EGL eglClientWaitSync(int dpy, int sync, int flags, int timeout) -> int */
zend_long phpgl_egl_eglclientwaitsync(zval *dpy, zval *sync, zval *flags, zval *timeout);

/*@zep EGL\EGL eglGetSyncAttrib(int dpy, int sync, int attribute, int value) -> bool */
zend_long phpgl_egl_eglgetsyncattrib(zval *dpy, zval *sync, zval *attribute, zval *value);

/*@zep EGL\EGL eglCreateImage(int dpy, int ctx, int target, int buffer, int attrib_list) -> int */
zend_long phpgl_egl_eglcreateimage(zval *dpy, zval *ctx, zval *target, zval *buffer, zval *attrib_list);

/*@zep EGL\EGL eglDestroyImage(int dpy, int image) -> bool */
zend_long phpgl_egl_egldestroyimage(zval *dpy, zval *image);

/*@zep EGL\EGL eglGetPlatformDisplay(int platform, int native_display, int attrib_list) -> int */
zend_long phpgl_egl_eglgetplatformdisplay(zval *platform, zval *native_display, zval *attrib_list);

/*@zep EGL\EGL eglCreatePlatformWindowSurface(int dpy, int config, int native_window, int attrib_list) -> int */
zend_long phpgl_egl_eglcreateplatformwindowsurface(zval *dpy, zval *config, zval *native_window, zval *attrib_list);

/*@zep EGL\EGL eglCreatePlatformPixmapSurface(int dpy, int config, int native_pixmap, int attrib_list) -> int */
zend_long phpgl_egl_eglcreateplatformpixmapsurface(zval *dpy, zval *config, zval *native_pixmap, zval *attrib_list);

/*@zep EGL\EGL eglWaitSync(int dpy, int sync, int flags) -> bool */
zend_long phpgl_egl_eglwaitsync(zval *dpy, zval *sync, zval *flags);

#endif
