/*
 * gl-15.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_1_5 (19 prototypes)
 */

#include "gl-15.h"
#include "gl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

void phpgl_gl15_glgenqueries(zval *n, zval *ids)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGENQUERIESPROC fn = (PFNGLGENQUERIESPROC) phpgl_entry("glGenQueries", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (GLuint *) phpgl_arg_ptr(ids));
}

void phpgl_gl15_gldeletequeries(zval *n, zval *ids)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDELETEQUERIESPROC fn = (PFNGLDELETEQUERIESPROC) phpgl_entry("glDeleteQueries", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (const GLuint *) phpgl_arg_ptr(ids));
}

zend_long phpgl_gl15_glisquery(zval *id)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLISQUERYPROC fn = (PFNGLISQUERYPROC) phpgl_entry("glIsQuery", &slot, 1, 5);

    if (!fn) {
        return 0;
    }

    return fn((GLuint) phpgl_arg_long(id)) ? 1 : 0;
}

void phpgl_gl15_glbeginquery(zval *target, zval *id)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBEGINQUERYPROC fn = (PFNGLBEGINQUERYPROC) phpgl_entry("glBeginQuery", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(id));
}

void phpgl_gl15_glendquery(zval *target)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLENDQUERYPROC fn = (PFNGLENDQUERYPROC) phpgl_entry("glEndQuery", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target));
}

void phpgl_gl15_glgetqueryiv(zval *target, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETQUERYIVPROC fn = (PFNGLGETQUERYIVPROC) phpgl_entry("glGetQueryiv", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl15_glgetqueryobjectiv(zval *id, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETQUERYOBJECTIVPROC fn = (PFNGLGETQUERYOBJECTIVPROC) phpgl_entry("glGetQueryObjectiv", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(id), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl15_glgetqueryobjectuiv(zval *id, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETQUERYOBJECTUIVPROC fn = (PFNGLGETQUERYOBJECTUIVPROC) phpgl_entry("glGetQueryObjectuiv", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(id), (GLenum) phpgl_arg_long(pname), (GLuint *) phpgl_arg_ptr(params));
}

void phpgl_gl15_glbindbuffer(zval *target, zval *buffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBINDBUFFERPROC fn = (PFNGLBINDBUFFERPROC) phpgl_entry("glBindBuffer", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(buffer));
}

void phpgl_gl15_gldeletebuffers(zval *n, zval *buffers)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDELETEBUFFERSPROC fn = (PFNGLDELETEBUFFERSPROC) phpgl_entry("glDeleteBuffers", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (const GLuint *) phpgl_arg_ptr(buffers));
}

void phpgl_gl15_glgenbuffers(zval *n, zval *buffers)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGENBUFFERSPROC fn = (PFNGLGENBUFFERSPROC) phpgl_entry("glGenBuffers", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (GLuint *) phpgl_arg_ptr(buffers));
}

zend_long phpgl_gl15_glisbuffer(zval *buffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLISBUFFERPROC fn = (PFNGLISBUFFERPROC) phpgl_entry("glIsBuffer", &slot, 1, 5);

    if (!fn) {
        return 0;
    }

    return fn((GLuint) phpgl_arg_long(buffer)) ? 1 : 0;
}

void phpgl_gl15_glbufferdata(zval *target, zval *size, zval *data, zval *usage)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBUFFERDATAPROC fn = (PFNGLBUFFERDATAPROC) phpgl_entry("glBufferData", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLsizeiptr) phpgl_arg_long(size), (const void *) phpgl_arg_ptr(data), (GLenum) phpgl_arg_long(usage));
}

void phpgl_gl15_glbuffersubdata(zval *target, zval *offset, zval *size, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBUFFERSUBDATAPROC fn = (PFNGLBUFFERSUBDATAPROC) phpgl_entry("glBufferSubData", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLintptr) phpgl_arg_long(offset), (GLsizeiptr) phpgl_arg_long(size), (const void *) phpgl_arg_ptr(data));
}

void phpgl_gl15_glgetbuffersubdata(zval *target, zval *offset, zval *size, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETBUFFERSUBDATAPROC fn = (PFNGLGETBUFFERSUBDATAPROC) phpgl_entry("glGetBufferSubData", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLintptr) phpgl_arg_long(offset), (GLsizeiptr) phpgl_arg_long(size), (void *) phpgl_arg_ptr(data));
}

zend_long phpgl_gl15_glmapbuffer(zval *target, zval *access)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLMAPBUFFERPROC fn = (PFNGLMAPBUFFERPROC) phpgl_entry("glMapBuffer", &slot, 1, 5);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(access));
}

zend_long phpgl_gl15_glunmapbuffer(zval *target)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNMAPBUFFERPROC fn = (PFNGLUNMAPBUFFERPROC) phpgl_entry("glUnmapBuffer", &slot, 1, 5);

    if (!fn) {
        return 0;
    }

    return fn((GLenum) phpgl_arg_long(target)) ? 1 : 0;
}

void phpgl_gl15_glgetbufferparameteriv(zval *target, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETBUFFERPARAMETERIVPROC fn = (PFNGLGETBUFFERPARAMETERIVPROC) phpgl_entry("glGetBufferParameteriv", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl15_glgetbufferpointerv(zval *target, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETBUFFERPOINTERVPROC fn = (PFNGLGETBUFFERPOINTERVPROC) phpgl_entry("glGetBufferPointerv", &slot, 1, 5);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(pname), (void * *) phpgl_arg_ptr(params));
}

