/*
 * gl-14.h — OpenGL\GL\GL14 bound 1:1.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_1_4 (9 prototypes)
 */

#ifndef PHPGL_GL_14_H
#define PHPGL_GL_14_H

#include <php.h>

/*@audit block GL\GL14 GL_VERSION_1_4 9 */

/*@zep GL\GL14 glBlendFuncSeparate(int sfactorRGB, int dfactorRGB, int sfactorAlpha, int dfactorAlpha) -> void */
void phpgl_gl14_glblendfuncseparate(zval *sfactorRGB, zval *dfactorRGB, zval *sfactorAlpha, zval *dfactorAlpha);

/*@zep GL\GL14 glMultiDrawArrays(int mode, int first, int count, int drawcount) -> void */
void phpgl_gl14_glmultidrawarrays(zval *mode, zval *first, zval *count, zval *drawcount);

/*@zep GL\GL14 glMultiDrawElements(int mode, int count, int type, int indices, int drawcount) -> void */
void phpgl_gl14_glmultidrawelements(zval *mode, zval *count, zval *type, zval *indices, zval *drawcount);

/*@zep GL\GL14 glPointParameterf(int pname, double param) -> void */
void phpgl_gl14_glpointparameterf(zval *pname, zval *param);

/*@zep GL\GL14 glPointParameterfv(int pname, int params) -> void */
void phpgl_gl14_glpointparameterfv(zval *pname, zval *params);

/*@zep GL\GL14 glPointParameteri(int pname, int param) -> void */
void phpgl_gl14_glpointparameteri(zval *pname, zval *param);

/*@zep GL\GL14 glPointParameteriv(int pname, int params) -> void */
void phpgl_gl14_glpointparameteriv(zval *pname, zval *params);

/*@zep GL\GL14 glBlendColor(double red, double green, double blue, double alpha) -> void */
void phpgl_gl14_glblendcolor(zval *red, zval *green, zval *blue, zval *alpha);

/*@zep GL\GL14 glBlendEquation(int mode) -> void */
void phpgl_gl14_glblendequation(zval *mode);

#endif
