/*
 * gl-13.h — OpenGL\GL\GL13 bound 1:1.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_1_3 (9 prototypes)
 */

#ifndef PHPGL_GL_13_H
#define PHPGL_GL_13_H

#include <php.h>

/*@audit block GL\GL13 GL_VERSION_1_3 9 */

/*@zep GL\GL13 glActiveTexture(int texture) -> void */
void phpgl_gl13_glactivetexture(zval *texture);

/*@zep GL\GL13 glSampleCoverage(double value, bool invert) -> void */
void phpgl_gl13_glsamplecoverage(zval *value, zval *invert);

/*@zep GL\GL13 glCompressedTexImage3D(int target, int level, int internalformat, int width, int height, int depth, int border, int imageSize, int data) -> void */
void phpgl_gl13_glcompressedteximage3d(zval *target, zval *level, zval *internalformat, zval *width, zval *height, zval *depth, zval *border, zval *imageSize, zval *data);

/*@zep GL\GL13 glCompressedTexImage2D(int target, int level, int internalformat, int width, int height, int border, int imageSize, int data) -> void */
void phpgl_gl13_glcompressedteximage2d(zval *target, zval *level, zval *internalformat, zval *width, zval *height, zval *border, zval *imageSize, zval *data);

/*@zep GL\GL13 glCompressedTexImage1D(int target, int level, int internalformat, int width, int border, int imageSize, int data) -> void */
void phpgl_gl13_glcompressedteximage1d(zval *target, zval *level, zval *internalformat, zval *width, zval *border, zval *imageSize, zval *data);

/*@zep GL\GL13 glCompressedTexSubImage3D(int target, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int imageSize, int data) -> void */
void phpgl_gl13_glcompressedtexsubimage3d(zval *target, zval *level, zval *xoffset, zval *yoffset, zval *zoffset, zval *width, zval *height, zval *depth, zval *format, zval *imageSize, zval *data);

/*@zep GL\GL13 glCompressedTexSubImage2D(int target, int level, int xoffset, int yoffset, int width, int height, int format, int imageSize, int data) -> void */
void phpgl_gl13_glcompressedtexsubimage2d(zval *target, zval *level, zval *xoffset, zval *yoffset, zval *width, zval *height, zval *format, zval *imageSize, zval *data);

/*@zep GL\GL13 glCompressedTexSubImage1D(int target, int level, int xoffset, int width, int format, int imageSize, int data) -> void */
void phpgl_gl13_glcompressedtexsubimage1d(zval *target, zval *level, zval *xoffset, zval *width, zval *format, zval *imageSize, zval *data);

/*@zep GL\GL13 glGetCompressedTexImage(int target, int level, int img) -> void */
void phpgl_gl13_glgetcompressedteximage(zval *target, zval *level, zval *img);

#endif
