/*
 * gl-20.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_2_0 (93 prototypes)
 */

#include "gl-20.h"
#include "gl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

void phpgl_gl20_glblendequationseparate(zval *modeRGB, zval *modeAlpha)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBLENDEQUATIONSEPARATEPROC fn = (PFNGLBLENDEQUATIONSEPARATEPROC) phpgl_entry("glBlendEquationSeparate", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(modeRGB), (GLenum) phpgl_arg_long(modeAlpha));
}

void phpgl_gl20_gldrawbuffers(zval *n, zval *bufs)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDRAWBUFFERSPROC fn = (PFNGLDRAWBUFFERSPROC) phpgl_entry("glDrawBuffers", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (const GLenum *) phpgl_arg_ptr(bufs));
}

void phpgl_gl20_glstencilopseparate(zval *face, zval *sfail, zval *dpfail, zval *dppass)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLSTENCILOPSEPARATEPROC fn = (PFNGLSTENCILOPSEPARATEPROC) phpgl_entry("glStencilOpSeparate", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(face), (GLenum) phpgl_arg_long(sfail), (GLenum) phpgl_arg_long(dpfail), (GLenum) phpgl_arg_long(dppass));
}

void phpgl_gl20_glstencilfuncseparate(zval *face, zval *func, zval *ref, zval *mask)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLSTENCILFUNCSEPARATEPROC fn = (PFNGLSTENCILFUNCSEPARATEPROC) phpgl_entry("glStencilFuncSeparate", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(face), (GLenum) phpgl_arg_long(func), (GLint) phpgl_arg_long(ref), (GLuint) phpgl_arg_long(mask));
}

void phpgl_gl20_glstencilmaskseparate(zval *face, zval *mask)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLSTENCILMASKSEPARATEPROC fn = (PFNGLSTENCILMASKSEPARATEPROC) phpgl_entry("glStencilMaskSeparate", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(face), (GLuint) phpgl_arg_long(mask));
}

void phpgl_gl20_glattachshader(zval *program, zval *shader)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLATTACHSHADERPROC fn = (PFNGLATTACHSHADERPROC) phpgl_entry("glAttachShader", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLuint) phpgl_arg_long(shader));
}

void phpgl_gl20_glbindattriblocation(zval *program, zval *index, zval *name)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBINDATTRIBLOCATIONPROC fn = (PFNGLBINDATTRIBLOCATIONPROC) phpgl_entry("glBindAttribLocation", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLuint) phpgl_arg_long(index), (const GLchar *) phpgl_arg_string(name));
}

void phpgl_gl20_glcompileshader(zval *shader)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOMPILESHADERPROC fn = (PFNGLCOMPILESHADERPROC) phpgl_entry("glCompileShader", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(shader));
}

zend_long phpgl_gl20_glcreateprogram(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCREATEPROGRAMPROC fn = (PFNGLCREATEPROGRAMPROC) phpgl_entry("glCreateProgram", &slot, 2, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn();
}

zend_long phpgl_gl20_glcreateshader(zval *type)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCREATESHADERPROC fn = (PFNGLCREATESHADERPROC) phpgl_entry("glCreateShader", &slot, 2, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((GLenum) phpgl_arg_long(type));
}

void phpgl_gl20_gldeleteprogram(zval *program)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDELETEPROGRAMPROC fn = (PFNGLDELETEPROGRAMPROC) phpgl_entry("glDeleteProgram", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program));
}

void phpgl_gl20_gldeleteshader(zval *shader)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDELETESHADERPROC fn = (PFNGLDELETESHADERPROC) phpgl_entry("glDeleteShader", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(shader));
}

void phpgl_gl20_gldetachshader(zval *program, zval *shader)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDETACHSHADERPROC fn = (PFNGLDETACHSHADERPROC) phpgl_entry("glDetachShader", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLuint) phpgl_arg_long(shader));
}

void phpgl_gl20_gldisablevertexattribarray(zval *index)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDISABLEVERTEXATTRIBARRAYPROC fn = (PFNGLDISABLEVERTEXATTRIBARRAYPROC) phpgl_entry("glDisableVertexAttribArray", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index));
}

void phpgl_gl20_glenablevertexattribarray(zval *index)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLENABLEVERTEXATTRIBARRAYPROC fn = (PFNGLENABLEVERTEXATTRIBARRAYPROC) phpgl_entry("glEnableVertexAttribArray", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index));
}

void phpgl_gl20_glgetactiveattrib(zval *program, zval *index, zval *bufSize, zval *length, zval *size, zval *type, zval *name)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETACTIVEATTRIBPROC fn = (PFNGLGETACTIVEATTRIBPROC) phpgl_entry("glGetActiveAttrib", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLuint) phpgl_arg_long(index), (GLsizei) phpgl_arg_long(bufSize), (GLsizei *) phpgl_arg_ptr(length), (GLint *) phpgl_arg_ptr(size), (GLenum *) phpgl_arg_ptr(type), (GLchar *) phpgl_arg_ptr(name));
}

void phpgl_gl20_glgetactiveuniform(zval *program, zval *index, zval *bufSize, zval *length, zval *size, zval *type, zval *name)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETACTIVEUNIFORMPROC fn = (PFNGLGETACTIVEUNIFORMPROC) phpgl_entry("glGetActiveUniform", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLuint) phpgl_arg_long(index), (GLsizei) phpgl_arg_long(bufSize), (GLsizei *) phpgl_arg_ptr(length), (GLint *) phpgl_arg_ptr(size), (GLenum *) phpgl_arg_ptr(type), (GLchar *) phpgl_arg_ptr(name));
}

void phpgl_gl20_glgetattachedshaders(zval *program, zval *maxCount, zval *count, zval *shaders)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETATTACHEDSHADERSPROC fn = (PFNGLGETATTACHEDSHADERSPROC) phpgl_entry("glGetAttachedShaders", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLsizei) phpgl_arg_long(maxCount), (GLsizei *) phpgl_arg_ptr(count), (GLuint *) phpgl_arg_ptr(shaders));
}

zend_long phpgl_gl20_glgetattriblocation(zval *program, zval *name)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETATTRIBLOCATIONPROC fn = (PFNGLGETATTRIBLOCATIONPROC) phpgl_entry("glGetAttribLocation", &slot, 2, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((GLuint) phpgl_arg_long(program), (const GLchar *) phpgl_arg_string(name));
}

void phpgl_gl20_glgetprogramiv(zval *program, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETPROGRAMIVPROC fn = (PFNGLGETPROGRAMIVPROC) phpgl_entry("glGetProgramiv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl20_glgetprograminfolog(zval *program, zval *bufSize, zval *length, zval *infoLog)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETPROGRAMINFOLOGPROC fn = (PFNGLGETPROGRAMINFOLOGPROC) phpgl_entry("glGetProgramInfoLog", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLsizei) phpgl_arg_long(bufSize), (GLsizei *) phpgl_arg_ptr(length), (GLchar *) phpgl_arg_ptr(infoLog));
}

void phpgl_gl20_glgetshaderiv(zval *shader, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETSHADERIVPROC fn = (PFNGLGETSHADERIVPROC) phpgl_entry("glGetShaderiv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(shader), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl20_glgetshaderinfolog(zval *shader, zval *bufSize, zval *length, zval *infoLog)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETSHADERINFOLOGPROC fn = (PFNGLGETSHADERINFOLOGPROC) phpgl_entry("glGetShaderInfoLog", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(shader), (GLsizei) phpgl_arg_long(bufSize), (GLsizei *) phpgl_arg_ptr(length), (GLchar *) phpgl_arg_ptr(infoLog));
}

void phpgl_gl20_glgetshadersource(zval *shader, zval *bufSize, zval *length, zval *source)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETSHADERSOURCEPROC fn = (PFNGLGETSHADERSOURCEPROC) phpgl_entry("glGetShaderSource", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(shader), (GLsizei) phpgl_arg_long(bufSize), (GLsizei *) phpgl_arg_ptr(length), (GLchar *) phpgl_arg_ptr(source));
}

zend_long phpgl_gl20_glgetuniformlocation(zval *program, zval *name)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETUNIFORMLOCATIONPROC fn = (PFNGLGETUNIFORMLOCATIONPROC) phpgl_entry("glGetUniformLocation", &slot, 2, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((GLuint) phpgl_arg_long(program), (const GLchar *) phpgl_arg_string(name));
}

void phpgl_gl20_glgetuniformfv(zval *program, zval *location, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETUNIFORMFVPROC fn = (PFNGLGETUNIFORMFVPROC) phpgl_entry("glGetUniformfv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLfloat *) phpgl_arg_ptr(params));
}

void phpgl_gl20_glgetuniformiv(zval *program, zval *location, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETUNIFORMIVPROC fn = (PFNGLGETUNIFORMIVPROC) phpgl_entry("glGetUniformiv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl20_glgetvertexattribdv(zval *index, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETVERTEXATTRIBDVPROC fn = (PFNGLGETVERTEXATTRIBDVPROC) phpgl_entry("glGetVertexAttribdv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLenum) phpgl_arg_long(pname), (GLdouble *) phpgl_arg_ptr(params));
}

void phpgl_gl20_glgetvertexattribfv(zval *index, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETVERTEXATTRIBFVPROC fn = (PFNGLGETVERTEXATTRIBFVPROC) phpgl_entry("glGetVertexAttribfv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLenum) phpgl_arg_long(pname), (GLfloat *) phpgl_arg_ptr(params));
}

void phpgl_gl20_glgetvertexattribiv(zval *index, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETVERTEXATTRIBIVPROC fn = (PFNGLGETVERTEXATTRIBIVPROC) phpgl_entry("glGetVertexAttribiv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl20_glgetvertexattribpointerv(zval *index, zval *pname, zval *pointer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETVERTEXATTRIBPOINTERVPROC fn = (PFNGLGETVERTEXATTRIBPOINTERVPROC) phpgl_entry("glGetVertexAttribPointerv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLenum) phpgl_arg_long(pname), (void * *) phpgl_arg_ptr(pointer));
}

zend_long phpgl_gl20_glisprogram(zval *program)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLISPROGRAMPROC fn = (PFNGLISPROGRAMPROC) phpgl_entry("glIsProgram", &slot, 2, 0);

    if (!fn) {
        return 0;
    }

    return fn((GLuint) phpgl_arg_long(program)) ? 1 : 0;
}

zend_long phpgl_gl20_glisshader(zval *shader)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLISSHADERPROC fn = (PFNGLISSHADERPROC) phpgl_entry("glIsShader", &slot, 2, 0);

    if (!fn) {
        return 0;
    }

    return fn((GLuint) phpgl_arg_long(shader)) ? 1 : 0;
}

void phpgl_gl20_gllinkprogram(zval *program)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLLINKPROGRAMPROC fn = (PFNGLLINKPROGRAMPROC) phpgl_entry("glLinkProgram", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program));
}

void phpgl_gl20_glshadersource(zval *shader, zval *count, zval *string, zval *length)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    char **strv = NULL;
    int strv_n = 0;
    PFNGLSHADERSOURCEPROC fn = (PFNGLSHADERSOURCEPROC) phpgl_entry("glShaderSource", &slot, 2, 0);

    if (!fn) {
        return;
    }

    strv = phpgl_arg_strv(string, &strv_n);
    if (phpgl_arg_long(count) > (zend_long) strv_n) {
        php_error_docref(NULL, E_WARNING,
            "glShaderSource: count exceeds the number of strings given");
        phpgl_free_strv(strv, strv_n);

        return;
    }

    fn((GLuint) phpgl_arg_long(shader), (GLsizei) phpgl_arg_long(count), (const GLchar *const *) strv, (const GLint *) phpgl_arg_ptr(length));
    phpgl_free_strv(strv, strv_n);
}

void phpgl_gl20_gluseprogram(zval *program)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUSEPROGRAMPROC fn = (PFNGLUSEPROGRAMPROC) phpgl_entry("glUseProgram", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program));
}

void phpgl_gl20_gluniform1f(zval *location, zval *v0)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM1FPROC fn = (PFNGLUNIFORM1FPROC) phpgl_entry("glUniform1f", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLfloat) phpgl_arg_double(v0));
}

void phpgl_gl20_gluniform2f(zval *location, zval *v0, zval *v1)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM2FPROC fn = (PFNGLUNIFORM2FPROC) phpgl_entry("glUniform2f", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLfloat) phpgl_arg_double(v0), (GLfloat) phpgl_arg_double(v1));
}

void phpgl_gl20_gluniform3f(zval *location, zval *v0, zval *v1, zval *v2)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM3FPROC fn = (PFNGLUNIFORM3FPROC) phpgl_entry("glUniform3f", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLfloat) phpgl_arg_double(v0), (GLfloat) phpgl_arg_double(v1), (GLfloat) phpgl_arg_double(v2));
}

void phpgl_gl20_gluniform4f(zval *location, zval *v0, zval *v1, zval *v2, zval *v3)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM4FPROC fn = (PFNGLUNIFORM4FPROC) phpgl_entry("glUniform4f", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLfloat) phpgl_arg_double(v0), (GLfloat) phpgl_arg_double(v1), (GLfloat) phpgl_arg_double(v2), (GLfloat) phpgl_arg_double(v3));
}

void phpgl_gl20_gluniform1i(zval *location, zval *v0)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM1IPROC fn = (PFNGLUNIFORM1IPROC) phpgl_entry("glUniform1i", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLint) phpgl_arg_long(v0));
}

void phpgl_gl20_gluniform2i(zval *location, zval *v0, zval *v1)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM2IPROC fn = (PFNGLUNIFORM2IPROC) phpgl_entry("glUniform2i", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLint) phpgl_arg_long(v0), (GLint) phpgl_arg_long(v1));
}

void phpgl_gl20_gluniform3i(zval *location, zval *v0, zval *v1, zval *v2)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM3IPROC fn = (PFNGLUNIFORM3IPROC) phpgl_entry("glUniform3i", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLint) phpgl_arg_long(v0), (GLint) phpgl_arg_long(v1), (GLint) phpgl_arg_long(v2));
}

void phpgl_gl20_gluniform4i(zval *location, zval *v0, zval *v1, zval *v2, zval *v3)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM4IPROC fn = (PFNGLUNIFORM4IPROC) phpgl_entry("glUniform4i", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLint) phpgl_arg_long(v0), (GLint) phpgl_arg_long(v1), (GLint) phpgl_arg_long(v2), (GLint) phpgl_arg_long(v3));
}

void phpgl_gl20_gluniform1fv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM1FVPROC fn = (PFNGLUNIFORM1FVPROC) phpgl_entry("glUniform1fv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl20_gluniform2fv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM2FVPROC fn = (PFNGLUNIFORM2FVPROC) phpgl_entry("glUniform2fv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl20_gluniform3fv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM3FVPROC fn = (PFNGLUNIFORM3FVPROC) phpgl_entry("glUniform3fv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl20_gluniform4fv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM4FVPROC fn = (PFNGLUNIFORM4FVPROC) phpgl_entry("glUniform4fv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl20_gluniform1iv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM1IVPROC fn = (PFNGLUNIFORM1IVPROC) phpgl_entry("glUniform1iv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLint *) phpgl_arg_ptr(value));
}

void phpgl_gl20_gluniform2iv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM2IVPROC fn = (PFNGLUNIFORM2IVPROC) phpgl_entry("glUniform2iv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLint *) phpgl_arg_ptr(value));
}

void phpgl_gl20_gluniform3iv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM3IVPROC fn = (PFNGLUNIFORM3IVPROC) phpgl_entry("glUniform3iv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLint *) phpgl_arg_ptr(value));
}

void phpgl_gl20_gluniform4iv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM4IVPROC fn = (PFNGLUNIFORM4IVPROC) phpgl_entry("glUniform4iv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLint *) phpgl_arg_ptr(value));
}

void phpgl_gl20_gluniformmatrix2fv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX2FVPROC fn = (PFNGLUNIFORMMATRIX2FVPROC) phpgl_entry("glUniformMatrix2fv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl20_gluniformmatrix3fv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX3FVPROC fn = (PFNGLUNIFORMMATRIX3FVPROC) phpgl_entry("glUniformMatrix3fv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl20_gluniformmatrix4fv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX4FVPROC fn = (PFNGLUNIFORMMATRIX4FVPROC) phpgl_entry("glUniformMatrix4fv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl20_glvalidateprogram(zval *program)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVALIDATEPROGRAMPROC fn = (PFNGLVALIDATEPROGRAMPROC) phpgl_entry("glValidateProgram", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program));
}

void phpgl_gl20_glvertexattrib1d(zval *index, zval *x)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB1DPROC fn = (PFNGLVERTEXATTRIB1DPROC) phpgl_entry("glVertexAttrib1d", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLdouble) phpgl_arg_double(x));
}

void phpgl_gl20_glvertexattrib1dv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB1DVPROC fn = (PFNGLVERTEXATTRIB1DVPROC) phpgl_entry("glVertexAttrib1dv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLdouble *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib1f(zval *index, zval *x)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB1FPROC fn = (PFNGLVERTEXATTRIB1FPROC) phpgl_entry("glVertexAttrib1f", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLfloat) phpgl_arg_double(x));
}

void phpgl_gl20_glvertexattrib1fv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB1FVPROC fn = (PFNGLVERTEXATTRIB1FVPROC) phpgl_entry("glVertexAttrib1fv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLfloat *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib1s(zval *index, zval *x)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB1SPROC fn = (PFNGLVERTEXATTRIB1SPROC) phpgl_entry("glVertexAttrib1s", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLshort) phpgl_arg_long(x));
}

void phpgl_gl20_glvertexattrib1sv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB1SVPROC fn = (PFNGLVERTEXATTRIB1SVPROC) phpgl_entry("glVertexAttrib1sv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLshort *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib2d(zval *index, zval *x, zval *y)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB2DPROC fn = (PFNGLVERTEXATTRIB2DPROC) phpgl_entry("glVertexAttrib2d", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLdouble) phpgl_arg_double(x), (GLdouble) phpgl_arg_double(y));
}

void phpgl_gl20_glvertexattrib2dv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB2DVPROC fn = (PFNGLVERTEXATTRIB2DVPROC) phpgl_entry("glVertexAttrib2dv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLdouble *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib2f(zval *index, zval *x, zval *y)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB2FPROC fn = (PFNGLVERTEXATTRIB2FPROC) phpgl_entry("glVertexAttrib2f", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLfloat) phpgl_arg_double(x), (GLfloat) phpgl_arg_double(y));
}

void phpgl_gl20_glvertexattrib2fv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB2FVPROC fn = (PFNGLVERTEXATTRIB2FVPROC) phpgl_entry("glVertexAttrib2fv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLfloat *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib2s(zval *index, zval *x, zval *y)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB2SPROC fn = (PFNGLVERTEXATTRIB2SPROC) phpgl_entry("glVertexAttrib2s", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLshort) phpgl_arg_long(x), (GLshort) phpgl_arg_long(y));
}

void phpgl_gl20_glvertexattrib2sv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB2SVPROC fn = (PFNGLVERTEXATTRIB2SVPROC) phpgl_entry("glVertexAttrib2sv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLshort *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib3d(zval *index, zval *x, zval *y, zval *z)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB3DPROC fn = (PFNGLVERTEXATTRIB3DPROC) phpgl_entry("glVertexAttrib3d", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLdouble) phpgl_arg_double(x), (GLdouble) phpgl_arg_double(y), (GLdouble) phpgl_arg_double(z));
}

void phpgl_gl20_glvertexattrib3dv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB3DVPROC fn = (PFNGLVERTEXATTRIB3DVPROC) phpgl_entry("glVertexAttrib3dv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLdouble *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib3f(zval *index, zval *x, zval *y, zval *z)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB3FPROC fn = (PFNGLVERTEXATTRIB3FPROC) phpgl_entry("glVertexAttrib3f", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLfloat) phpgl_arg_double(x), (GLfloat) phpgl_arg_double(y), (GLfloat) phpgl_arg_double(z));
}

void phpgl_gl20_glvertexattrib3fv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB3FVPROC fn = (PFNGLVERTEXATTRIB3FVPROC) phpgl_entry("glVertexAttrib3fv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLfloat *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib3s(zval *index, zval *x, zval *y, zval *z)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB3SPROC fn = (PFNGLVERTEXATTRIB3SPROC) phpgl_entry("glVertexAttrib3s", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLshort) phpgl_arg_long(x), (GLshort) phpgl_arg_long(y), (GLshort) phpgl_arg_long(z));
}

void phpgl_gl20_glvertexattrib3sv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB3SVPROC fn = (PFNGLVERTEXATTRIB3SVPROC) phpgl_entry("glVertexAttrib3sv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLshort *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib4nbv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4NBVPROC fn = (PFNGLVERTEXATTRIB4NBVPROC) phpgl_entry("glVertexAttrib4Nbv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLbyte *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib4niv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4NIVPROC fn = (PFNGLVERTEXATTRIB4NIVPROC) phpgl_entry("glVertexAttrib4Niv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLint *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib4nsv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4NSVPROC fn = (PFNGLVERTEXATTRIB4NSVPROC) phpgl_entry("glVertexAttrib4Nsv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLshort *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib4nub(zval *index, zval *x, zval *y, zval *z, zval *w)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4NUBPROC fn = (PFNGLVERTEXATTRIB4NUBPROC) phpgl_entry("glVertexAttrib4Nub", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLubyte) phpgl_arg_long(x), (GLubyte) phpgl_arg_long(y), (GLubyte) phpgl_arg_long(z), (GLubyte) phpgl_arg_long(w));
}

void phpgl_gl20_glvertexattrib4nubv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4NUBVPROC fn = (PFNGLVERTEXATTRIB4NUBVPROC) phpgl_entry("glVertexAttrib4Nubv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLubyte *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib4nuiv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4NUIVPROC fn = (PFNGLVERTEXATTRIB4NUIVPROC) phpgl_entry("glVertexAttrib4Nuiv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLuint *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib4nusv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4NUSVPROC fn = (PFNGLVERTEXATTRIB4NUSVPROC) phpgl_entry("glVertexAttrib4Nusv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLushort *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib4bv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4BVPROC fn = (PFNGLVERTEXATTRIB4BVPROC) phpgl_entry("glVertexAttrib4bv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLbyte *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib4d(zval *index, zval *x, zval *y, zval *z, zval *w)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4DPROC fn = (PFNGLVERTEXATTRIB4DPROC) phpgl_entry("glVertexAttrib4d", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLdouble) phpgl_arg_double(x), (GLdouble) phpgl_arg_double(y), (GLdouble) phpgl_arg_double(z), (GLdouble) phpgl_arg_double(w));
}

void phpgl_gl20_glvertexattrib4dv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4DVPROC fn = (PFNGLVERTEXATTRIB4DVPROC) phpgl_entry("glVertexAttrib4dv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLdouble *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib4f(zval *index, zval *x, zval *y, zval *z, zval *w)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4FPROC fn = (PFNGLVERTEXATTRIB4FPROC) phpgl_entry("glVertexAttrib4f", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLfloat) phpgl_arg_double(x), (GLfloat) phpgl_arg_double(y), (GLfloat) phpgl_arg_double(z), (GLfloat) phpgl_arg_double(w));
}

void phpgl_gl20_glvertexattrib4fv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4FVPROC fn = (PFNGLVERTEXATTRIB4FVPROC) phpgl_entry("glVertexAttrib4fv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLfloat *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib4iv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4IVPROC fn = (PFNGLVERTEXATTRIB4IVPROC) phpgl_entry("glVertexAttrib4iv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLint *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib4s(zval *index, zval *x, zval *y, zval *z, zval *w)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4SPROC fn = (PFNGLVERTEXATTRIB4SPROC) phpgl_entry("glVertexAttrib4s", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLshort) phpgl_arg_long(x), (GLshort) phpgl_arg_long(y), (GLshort) phpgl_arg_long(z), (GLshort) phpgl_arg_long(w));
}

void phpgl_gl20_glvertexattrib4sv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4SVPROC fn = (PFNGLVERTEXATTRIB4SVPROC) phpgl_entry("glVertexAttrib4sv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLshort *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib4ubv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4UBVPROC fn = (PFNGLVERTEXATTRIB4UBVPROC) phpgl_entry("glVertexAttrib4ubv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLubyte *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib4uiv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4UIVPROC fn = (PFNGLVERTEXATTRIB4UIVPROC) phpgl_entry("glVertexAttrib4uiv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLuint *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattrib4usv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIB4USVPROC fn = (PFNGLVERTEXATTRIB4USVPROC) phpgl_entry("glVertexAttrib4usv", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLushort *) phpgl_arg_ptr(v));
}

void phpgl_gl20_glvertexattribpointer(zval *index, zval *size, zval *type, zval *normalized, zval *stride, zval *pointer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBPOINTERPROC fn = (PFNGLVERTEXATTRIBPOINTERPROC) phpgl_entry("glVertexAttribPointer", &slot, 2, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLint) phpgl_arg_long(size), (GLenum) phpgl_arg_long(type), (GLboolean) phpgl_arg_bool(normalized), (GLsizei) phpgl_arg_long(stride), (const void *) phpgl_arg_ptr(pointer));
}

