/*
 * gl-31.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_3_1 (12 prototypes)
 */

#include "gl-31.h"
#include "gl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

void phpgl_gl31_gldrawarraysinstanced(zval *mode, zval *first, zval *count, zval *instancecount)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDRAWARRAYSINSTANCEDPROC fn = (PFNGLDRAWARRAYSINSTANCEDPROC) phpgl_entry("glDrawArraysInstanced", &slot, 3, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (GLint) phpgl_arg_long(first), (GLsizei) phpgl_arg_long(count), (GLsizei) phpgl_arg_long(instancecount));
}

void phpgl_gl31_gldrawelementsinstanced(zval *mode, zval *count, zval *type, zval *indices, zval *instancecount)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDRAWELEMENTSINSTANCEDPROC fn = (PFNGLDRAWELEMENTSINSTANCEDPROC) phpgl_entry("glDrawElementsInstanced", &slot, 3, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (GLsizei) phpgl_arg_long(count), (GLenum) phpgl_arg_long(type), (const void *) phpgl_arg_ptr(indices), (GLsizei) phpgl_arg_long(instancecount));
}

void phpgl_gl31_gltexbuffer(zval *target, zval *internalformat, zval *buffer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLTEXBUFFERPROC fn = (PFNGLTEXBUFFERPROC) phpgl_entry("glTexBuffer", &slot, 3, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLenum) phpgl_arg_long(internalformat), (GLuint) phpgl_arg_long(buffer));
}

void phpgl_gl31_glprimitiverestartindex(zval *index)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPRIMITIVERESTARTINDEXPROC fn = (PFNGLPRIMITIVERESTARTINDEXPROC) phpgl_entry("glPrimitiveRestartIndex", &slot, 3, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index));
}

void phpgl_gl31_glcopybuffersubdata(zval *readTarget, zval *writeTarget, zval *readOffset, zval *writeOffset, zval *size)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCOPYBUFFERSUBDATAPROC fn = (PFNGLCOPYBUFFERSUBDATAPROC) phpgl_entry("glCopyBufferSubData", &slot, 3, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(readTarget), (GLenum) phpgl_arg_long(writeTarget), (GLintptr) phpgl_arg_long(readOffset), (GLintptr) phpgl_arg_long(writeOffset), (GLsizeiptr) phpgl_arg_long(size));
}

void phpgl_gl31_glgetuniformindices(zval *program, zval *uniformCount, zval *uniformNames, zval *uniformIndices)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    char **strv = NULL;
    int strv_n = 0;
    PFNGLGETUNIFORMINDICESPROC fn = (PFNGLGETUNIFORMINDICESPROC) phpgl_entry("glGetUniformIndices", &slot, 3, 1);

    if (!fn) {
        return;
    }

    strv = phpgl_arg_strv(uniformNames, &strv_n);
    if (phpgl_arg_long(uniformCount) > (zend_long) strv_n) {
        php_error_docref(NULL, E_WARNING,
            "glGetUniformIndices: count exceeds the number of strings given");
        phpgl_free_strv(strv, strv_n);

        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLsizei) phpgl_arg_long(uniformCount), (const GLchar *const *) strv, (GLuint *) phpgl_arg_ptr(uniformIndices));
    phpgl_free_strv(strv, strv_n);
}

void phpgl_gl31_glgetactiveuniformsiv(zval *program, zval *uniformCount, zval *uniformIndices, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETACTIVEUNIFORMSIVPROC fn = (PFNGLGETACTIVEUNIFORMSIVPROC) phpgl_entry("glGetActiveUniformsiv", &slot, 3, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLsizei) phpgl_arg_long(uniformCount), (const GLuint *) phpgl_arg_ptr(uniformIndices), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl31_glgetactiveuniformname(zval *program, zval *uniformIndex, zval *bufSize, zval *length, zval *uniformName)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETACTIVEUNIFORMNAMEPROC fn = (PFNGLGETACTIVEUNIFORMNAMEPROC) phpgl_entry("glGetActiveUniformName", &slot, 3, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLuint) phpgl_arg_long(uniformIndex), (GLsizei) phpgl_arg_long(bufSize), (GLsizei *) phpgl_arg_ptr(length), (GLchar *) phpgl_arg_ptr(uniformName));
}

zend_long phpgl_gl31_glgetuniformblockindex(zval *program, zval *uniformBlockName)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETUNIFORMBLOCKINDEXPROC fn = (PFNGLGETUNIFORMBLOCKINDEXPROC) phpgl_entry("glGetUniformBlockIndex", &slot, 3, 1);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((GLuint) phpgl_arg_long(program), (const GLchar *) phpgl_arg_string(uniformBlockName));
}

void phpgl_gl31_glgetactiveuniformblockiv(zval *program, zval *uniformBlockIndex, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETACTIVEUNIFORMBLOCKIVPROC fn = (PFNGLGETACTIVEUNIFORMBLOCKIVPROC) phpgl_entry("glGetActiveUniformBlockiv", &slot, 3, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLuint) phpgl_arg_long(uniformBlockIndex), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl31_glgetactiveuniformblockname(zval *program, zval *uniformBlockIndex, zval *bufSize, zval *length, zval *uniformBlockName)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC fn = (PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC) phpgl_entry("glGetActiveUniformBlockName", &slot, 3, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLuint) phpgl_arg_long(uniformBlockIndex), (GLsizei) phpgl_arg_long(bufSize), (GLsizei *) phpgl_arg_ptr(length), (GLchar *) phpgl_arg_ptr(uniformBlockName));
}

void phpgl_gl31_gluniformblockbinding(zval *program, zval *uniformBlockIndex, zval *uniformBlockBinding)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMBLOCKBINDINGPROC fn = (PFNGLUNIFORMBLOCKBINDINGPROC) phpgl_entry("glUniformBlockBinding", &slot, 3, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLuint) phpgl_arg_long(uniformBlockIndex), (GLuint) phpgl_arg_long(uniformBlockBinding));
}

