/*
 * gl-41.h — OpenGL\GL\GL41 bound 1:1.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_4_1 (88 prototypes)
 */

#ifndef PHPGL_GL_41_H
#define PHPGL_GL_41_H

#include <php.h>

/*@audit block GL\GL41 GL_VERSION_4_1 88 */

/*@zep GL\GL41 glReleaseShaderCompiler() -> void */
void phpgl_gl41_glreleaseshadercompiler(void);

/*@zep GL\GL41 glShaderBinary(int count, int shaders, int binaryFormat, int binary, int length) -> void */
void phpgl_gl41_glshaderbinary(zval *count, zval *shaders, zval *binaryFormat, zval *binary, zval *length);

/*@zep GL\GL41 glGetShaderPrecisionFormat(int shadertype, int precisiontype, int range, int precision) -> void */
void phpgl_gl41_glgetshaderprecisionformat(zval *shadertype, zval *precisiontype, zval *range, zval *precision);

/*@zep GL\GL41 glDepthRangef(double n, double f) -> void */
void phpgl_gl41_gldepthrangef(zval *n, zval *f);

/*@zep GL\GL41 glClearDepthf(double d) -> void */
void phpgl_gl41_glcleardepthf(zval *d);

/*@zep GL\GL41 glGetProgramBinary(int program, int bufSize, int length, int binaryFormat, int binary) -> void */
void phpgl_gl41_glgetprogrambinary(zval *program, zval *bufSize, zval *length, zval *binaryFormat, zval *binary);

/*@zep GL\GL41 glProgramBinary(int program, int binaryFormat, int binary, int length) -> void */
void phpgl_gl41_glprogrambinary(zval *program, zval *binaryFormat, zval *binary, zval *length);

/*@zep GL\GL41 glProgramParameteri(int program, int pname, int value) -> void */
void phpgl_gl41_glprogramparameteri(zval *program, zval *pname, zval *value);

/*@zep GL\GL41 glUseProgramStages(int pipeline, int stages, int program) -> void */
void phpgl_gl41_gluseprogramstages(zval *pipeline, zval *stages, zval *program);

/*@zep GL\GL41 glActiveShaderProgram(int pipeline, int program) -> void */
void phpgl_gl41_glactiveshaderprogram(zval *pipeline, zval *program);

/*@zep GL\GL41 glCreateShaderProgramv(int type, int count, array strings) -> int */
zend_long phpgl_gl41_glcreateshaderprogramv(zval *type, zval *count, zval *strings);

/*@zep GL\GL41 glBindProgramPipeline(int pipeline) -> void */
void phpgl_gl41_glbindprogrampipeline(zval *pipeline);

/*@zep GL\GL41 glDeleteProgramPipelines(int n, int pipelines) -> void */
void phpgl_gl41_gldeleteprogrampipelines(zval *n, zval *pipelines);

/*@zep GL\GL41 glGenProgramPipelines(int n, int pipelines) -> void */
void phpgl_gl41_glgenprogrampipelines(zval *n, zval *pipelines);

/*@zep GL\GL41 glIsProgramPipeline(int pipeline) -> bool */
zend_long phpgl_gl41_glisprogrampipeline(zval *pipeline);

/*@zep GL\GL41 glGetProgramPipelineiv(int pipeline, int pname, int params) -> void */
void phpgl_gl41_glgetprogrampipelineiv(zval *pipeline, zval *pname, zval *params);

/*@zep GL\GL41 glProgramUniform1i(int program, int location, int v0) -> void */
void phpgl_gl41_glprogramuniform1i(zval *program, zval *location, zval *v0);

/*@zep GL\GL41 glProgramUniform1iv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform1iv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform1f(int program, int location, double v0) -> void */
void phpgl_gl41_glprogramuniform1f(zval *program, zval *location, zval *v0);

/*@zep GL\GL41 glProgramUniform1fv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform1fv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform1d(int program, int location, double v0) -> void */
void phpgl_gl41_glprogramuniform1d(zval *program, zval *location, zval *v0);

/*@zep GL\GL41 glProgramUniform1dv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform1dv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform1ui(int program, int location, int v0) -> void */
void phpgl_gl41_glprogramuniform1ui(zval *program, zval *location, zval *v0);

/*@zep GL\GL41 glProgramUniform1uiv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform1uiv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform2i(int program, int location, int v0, int v1) -> void */
void phpgl_gl41_glprogramuniform2i(zval *program, zval *location, zval *v0, zval *v1);

/*@zep GL\GL41 glProgramUniform2iv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform2iv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform2f(int program, int location, double v0, double v1) -> void */
void phpgl_gl41_glprogramuniform2f(zval *program, zval *location, zval *v0, zval *v1);

/*@zep GL\GL41 glProgramUniform2fv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform2fv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform2d(int program, int location, double v0, double v1) -> void */
void phpgl_gl41_glprogramuniform2d(zval *program, zval *location, zval *v0, zval *v1);

/*@zep GL\GL41 glProgramUniform2dv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform2dv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform2ui(int program, int location, int v0, int v1) -> void */
void phpgl_gl41_glprogramuniform2ui(zval *program, zval *location, zval *v0, zval *v1);

/*@zep GL\GL41 glProgramUniform2uiv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform2uiv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform3i(int program, int location, int v0, int v1, int v2) -> void */
void phpgl_gl41_glprogramuniform3i(zval *program, zval *location, zval *v0, zval *v1, zval *v2);

/*@zep GL\GL41 glProgramUniform3iv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform3iv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform3f(int program, int location, double v0, double v1, double v2) -> void */
void phpgl_gl41_glprogramuniform3f(zval *program, zval *location, zval *v0, zval *v1, zval *v2);

/*@zep GL\GL41 glProgramUniform3fv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform3fv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform3d(int program, int location, double v0, double v1, double v2) -> void */
void phpgl_gl41_glprogramuniform3d(zval *program, zval *location, zval *v0, zval *v1, zval *v2);

/*@zep GL\GL41 glProgramUniform3dv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform3dv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform3ui(int program, int location, int v0, int v1, int v2) -> void */
void phpgl_gl41_glprogramuniform3ui(zval *program, zval *location, zval *v0, zval *v1, zval *v2);

/*@zep GL\GL41 glProgramUniform3uiv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform3uiv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform4i(int program, int location, int v0, int v1, int v2, int v3) -> void */
void phpgl_gl41_glprogramuniform4i(zval *program, zval *location, zval *v0, zval *v1, zval *v2, zval *v3);

/*@zep GL\GL41 glProgramUniform4iv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform4iv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform4f(int program, int location, double v0, double v1, double v2, double v3) -> void */
void phpgl_gl41_glprogramuniform4f(zval *program, zval *location, zval *v0, zval *v1, zval *v2, zval *v3);

/*@zep GL\GL41 glProgramUniform4fv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform4fv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform4d(int program, int location, double v0, double v1, double v2, double v3) -> void */
void phpgl_gl41_glprogramuniform4d(zval *program, zval *location, zval *v0, zval *v1, zval *v2, zval *v3);

/*@zep GL\GL41 glProgramUniform4dv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform4dv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniform4ui(int program, int location, int v0, int v1, int v2, int v3) -> void */
void phpgl_gl41_glprogramuniform4ui(zval *program, zval *location, zval *v0, zval *v1, zval *v2, zval *v3);

/*@zep GL\GL41 glProgramUniform4uiv(int program, int location, int count, int value) -> void */
void phpgl_gl41_glprogramuniform4uiv(zval *program, zval *location, zval *count, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix2fv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix2fv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix3fv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix3fv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix4fv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix4fv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix2dv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix2dv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix3dv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix3dv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix4dv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix4dv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix2x3fv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix2x3fv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix3x2fv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix3x2fv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix2x4fv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix2x4fv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix4x2fv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix4x2fv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix3x4fv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix3x4fv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix4x3fv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix4x3fv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix2x3dv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix2x3dv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix3x2dv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix3x2dv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix2x4dv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix2x4dv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix4x2dv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix4x2dv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix3x4dv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix3x4dv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glProgramUniformMatrix4x3dv(int program, int location, int count, bool transpose, int value) -> void */
void phpgl_gl41_glprogramuniformmatrix4x3dv(zval *program, zval *location, zval *count, zval *transpose, zval *value);

/*@zep GL\GL41 glValidateProgramPipeline(int pipeline) -> void */
void phpgl_gl41_glvalidateprogrampipeline(zval *pipeline);

/*@zep GL\GL41 glGetProgramPipelineInfoLog(int pipeline, int bufSize, int length, int infoLog) -> void */
void phpgl_gl41_glgetprogrampipelineinfolog(zval *pipeline, zval *bufSize, zval *length, zval *infoLog);

/*@zep GL\GL41 glVertexAttribL1d(int index, double x) -> void */
void phpgl_gl41_glvertexattribl1d(zval *index, zval *x);

/*@zep GL\GL41 glVertexAttribL2d(int index, double x, double y) -> void */
void phpgl_gl41_glvertexattribl2d(zval *index, zval *x, zval *y);

/*@zep GL\GL41 glVertexAttribL3d(int index, double x, double y, double z) -> void */
void phpgl_gl41_glvertexattribl3d(zval *index, zval *x, zval *y, zval *z);

/*@zep GL\GL41 glVertexAttribL4d(int index, double x, double y, double z, double w) -> void */
void phpgl_gl41_glvertexattribl4d(zval *index, zval *x, zval *y, zval *z, zval *w);

/*@zep GL\GL41 glVertexAttribL1dv(int index, int v) -> void */
void phpgl_gl41_glvertexattribl1dv(zval *index, zval *v);

/*@zep GL\GL41 glVertexAttribL2dv(int index, int v) -> void */
void phpgl_gl41_glvertexattribl2dv(zval *index, zval *v);

/*@zep GL\GL41 glVertexAttribL3dv(int index, int v) -> void */
void phpgl_gl41_glvertexattribl3dv(zval *index, zval *v);

/*@zep GL\GL41 glVertexAttribL4dv(int index, int v) -> void */
void phpgl_gl41_glvertexattribl4dv(zval *index, zval *v);

/*@zep GL\GL41 glVertexAttribLPointer(int index, int size, int type, int stride, int pointer) -> void */
void phpgl_gl41_glvertexattriblpointer(zval *index, zval *size, zval *type, zval *stride, zval *pointer);

/*@zep GL\GL41 glGetVertexAttribLdv(int index, int pname, int params) -> void */
void phpgl_gl41_glgetvertexattribldv(zval *index, zval *pname, zval *params);

/*@zep GL\GL41 glViewportArrayv(int first, int count, int v) -> void */
void phpgl_gl41_glviewportarrayv(zval *first, zval *count, zval *v);

/*@zep GL\GL41 glViewportIndexedf(int index, double x, double y, double w, double h) -> void */
void phpgl_gl41_glviewportindexedf(zval *index, zval *x, zval *y, zval *w, zval *h);

/*@zep GL\GL41 glViewportIndexedfv(int index, int v) -> void */
void phpgl_gl41_glviewportindexedfv(zval *index, zval *v);

/*@zep GL\GL41 glScissorArrayv(int first, int count, int v) -> void */
void phpgl_gl41_glscissorarrayv(zval *first, zval *count, zval *v);

/*@zep GL\GL41 glScissorIndexed(int index, int left, int bottom, int width, int height) -> void */
void phpgl_gl41_glscissorindexed(zval *index, zval *left, zval *bottom, zval *width, zval *height);

/*@zep GL\GL41 glScissorIndexedv(int index, int v) -> void */
void phpgl_gl41_glscissorindexedv(zval *index, zval *v);

/*@zep GL\GL41 glDepthRangeArrayv(int first, int count, int v) -> void */
void phpgl_gl41_gldepthrangearrayv(zval *first, zval *count, zval *v);

/*@zep GL\GL41 glDepthRangeIndexed(int index, double n, double f) -> void */
void phpgl_gl41_gldepthrangeindexed(zval *index, zval *n, zval *f);

/*@zep GL\GL41 glGetFloati_v(int target, int index, int data) -> void */
void phpgl_gl41_glgetfloati_v(zval *target, zval *index, zval *data);

/*@zep GL\GL41 glGetDoublei_v(int target, int index, int data) -> void */
void phpgl_gl41_glgetdoublei_v(zval *target, zval *index, zval *data);

#endif
