/*
 * gl-40.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_4_0 (46 prototypes)
 */

#include "gl-40.h"
#include "gl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

void phpgl_gl40_glminsampleshading(zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLMINSAMPLESHADINGPROC fn = (PFNGLMINSAMPLESHADINGPROC) phpgl_entry("glMinSampleShading", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLfloat) phpgl_arg_double(value));
}

void phpgl_gl40_glblendequationi(zval *buf, zval *mode)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBLENDEQUATIONIPROC fn = (PFNGLBLENDEQUATIONIPROC) phpgl_entry("glBlendEquationi", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(buf), (GLenum) phpgl_arg_long(mode));
}

void phpgl_gl40_glblendequationseparatei(zval *buf, zval *modeRGB, zval *modeAlpha)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBLENDEQUATIONSEPARATEIPROC fn = (PFNGLBLENDEQUATIONSEPARATEIPROC) phpgl_entry("glBlendEquationSeparatei", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(buf), (GLenum) phpgl_arg_long(modeRGB), (GLenum) phpgl_arg_long(modeAlpha));
}

void phpgl_gl40_glblendfunci(zval *buf, zval *src, zval *dst)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBLENDFUNCIPROC fn = (PFNGLBLENDFUNCIPROC) phpgl_entry("glBlendFunci", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(buf), (GLenum) phpgl_arg_long(src), (GLenum) phpgl_arg_long(dst));
}

void phpgl_gl40_glblendfuncseparatei(zval *buf, zval *srcRGB, zval *dstRGB, zval *srcAlpha, zval *dstAlpha)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBLENDFUNCSEPARATEIPROC fn = (PFNGLBLENDFUNCSEPARATEIPROC) phpgl_entry("glBlendFuncSeparatei", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(buf), (GLenum) phpgl_arg_long(srcRGB), (GLenum) phpgl_arg_long(dstRGB), (GLenum) phpgl_arg_long(srcAlpha), (GLenum) phpgl_arg_long(dstAlpha));
}

void phpgl_gl40_gldrawarraysindirect(zval *mode, zval *indirect)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDRAWARRAYSINDIRECTPROC fn = (PFNGLDRAWARRAYSINDIRECTPROC) phpgl_entry("glDrawArraysIndirect", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (const void *) phpgl_arg_ptr(indirect));
}

void phpgl_gl40_gldrawelementsindirect(zval *mode, zval *type, zval *indirect)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDRAWELEMENTSINDIRECTPROC fn = (PFNGLDRAWELEMENTSINDIRECTPROC) phpgl_entry("glDrawElementsIndirect", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (GLenum) phpgl_arg_long(type), (const void *) phpgl_arg_ptr(indirect));
}

void phpgl_gl40_gluniform1d(zval *location, zval *x)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM1DPROC fn = (PFNGLUNIFORM1DPROC) phpgl_entry("glUniform1d", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLdouble) phpgl_arg_double(x));
}

void phpgl_gl40_gluniform2d(zval *location, zval *x, zval *y)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM2DPROC fn = (PFNGLUNIFORM2DPROC) phpgl_entry("glUniform2d", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLdouble) phpgl_arg_double(x), (GLdouble) phpgl_arg_double(y));
}

void phpgl_gl40_gluniform3d(zval *location, zval *x, zval *y, zval *z)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM3DPROC fn = (PFNGLUNIFORM3DPROC) phpgl_entry("glUniform3d", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLdouble) phpgl_arg_double(x), (GLdouble) phpgl_arg_double(y), (GLdouble) phpgl_arg_double(z));
}

void phpgl_gl40_gluniform4d(zval *location, zval *x, zval *y, zval *z, zval *w)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM4DPROC fn = (PFNGLUNIFORM4DPROC) phpgl_entry("glUniform4d", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLdouble) phpgl_arg_double(x), (GLdouble) phpgl_arg_double(y), (GLdouble) phpgl_arg_double(z), (GLdouble) phpgl_arg_double(w));
}

void phpgl_gl40_gluniform1dv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM1DVPROC fn = (PFNGLUNIFORM1DVPROC) phpgl_entry("glUniform1dv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl40_gluniform2dv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM2DVPROC fn = (PFNGLUNIFORM2DVPROC) phpgl_entry("glUniform2dv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl40_gluniform3dv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM3DVPROC fn = (PFNGLUNIFORM3DVPROC) phpgl_entry("glUniform3dv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl40_gluniform4dv(zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORM4DVPROC fn = (PFNGLUNIFORM4DVPROC) phpgl_entry("glUniform4dv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl40_gluniformmatrix2dv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX2DVPROC fn = (PFNGLUNIFORMMATRIX2DVPROC) phpgl_entry("glUniformMatrix2dv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl40_gluniformmatrix3dv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX3DVPROC fn = (PFNGLUNIFORMMATRIX3DVPROC) phpgl_entry("glUniformMatrix3dv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl40_gluniformmatrix4dv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX4DVPROC fn = (PFNGLUNIFORMMATRIX4DVPROC) phpgl_entry("glUniformMatrix4dv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl40_gluniformmatrix2x3dv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX2X3DVPROC fn = (PFNGLUNIFORMMATRIX2X3DVPROC) phpgl_entry("glUniformMatrix2x3dv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl40_gluniformmatrix2x4dv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX2X4DVPROC fn = (PFNGLUNIFORMMATRIX2X4DVPROC) phpgl_entry("glUniformMatrix2x4dv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl40_gluniformmatrix3x2dv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX3X2DVPROC fn = (PFNGLUNIFORMMATRIX3X2DVPROC) phpgl_entry("glUniformMatrix3x2dv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl40_gluniformmatrix3x4dv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX3X4DVPROC fn = (PFNGLUNIFORMMATRIX3X4DVPROC) phpgl_entry("glUniformMatrix3x4dv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl40_gluniformmatrix4x2dv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX4X2DVPROC fn = (PFNGLUNIFORMMATRIX4X2DVPROC) phpgl_entry("glUniformMatrix4x2dv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl40_gluniformmatrix4x3dv(zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMMATRIX4X3DVPROC fn = (PFNGLUNIFORMMATRIX4X3DVPROC) phpgl_entry("glUniformMatrix4x3dv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl40_glgetuniformdv(zval *program, zval *location, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETUNIFORMDVPROC fn = (PFNGLGETUNIFORMDVPROC) phpgl_entry("glGetUniformdv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLdouble *) phpgl_arg_ptr(params));
}

zend_long phpgl_gl40_glgetsubroutineuniformlocation(zval *program, zval *shadertype, zval *name)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC fn = (PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC) phpgl_entry("glGetSubroutineUniformLocation", &slot, 4, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((GLuint) phpgl_arg_long(program), (GLenum) phpgl_arg_long(shadertype), (const GLchar *) phpgl_arg_string(name));
}

zend_long phpgl_gl40_glgetsubroutineindex(zval *program, zval *shadertype, zval *name)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETSUBROUTINEINDEXPROC fn = (PFNGLGETSUBROUTINEINDEXPROC) phpgl_entry("glGetSubroutineIndex", &slot, 4, 0);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((GLuint) phpgl_arg_long(program), (GLenum) phpgl_arg_long(shadertype), (const GLchar *) phpgl_arg_string(name));
}

void phpgl_gl40_glgetactivesubroutineuniformiv(zval *program, zval *shadertype, zval *index, zval *pname, zval *values)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC fn = (PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC) phpgl_entry("glGetActiveSubroutineUniformiv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLenum) phpgl_arg_long(shadertype), (GLuint) phpgl_arg_long(index), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(values));
}

void phpgl_gl40_glgetactivesubroutineuniformname(zval *program, zval *shadertype, zval *index, zval *bufSize, zval *length, zval *name)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC fn = (PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC) phpgl_entry("glGetActiveSubroutineUniformName", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLenum) phpgl_arg_long(shadertype), (GLuint) phpgl_arg_long(index), (GLsizei) phpgl_arg_long(bufSize), (GLsizei *) phpgl_arg_ptr(length), (GLchar *) phpgl_arg_ptr(name));
}

void phpgl_gl40_glgetactivesubroutinename(zval *program, zval *shadertype, zval *index, zval *bufSize, zval *length, zval *name)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETACTIVESUBROUTINENAMEPROC fn = (PFNGLGETACTIVESUBROUTINENAMEPROC) phpgl_entry("glGetActiveSubroutineName", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLenum) phpgl_arg_long(shadertype), (GLuint) phpgl_arg_long(index), (GLsizei) phpgl_arg_long(bufSize), (GLsizei *) phpgl_arg_ptr(length), (GLchar *) phpgl_arg_ptr(name));
}

void phpgl_gl40_gluniformsubroutinesuiv(zval *shadertype, zval *count, zval *indices)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUNIFORMSUBROUTINESUIVPROC fn = (PFNGLUNIFORMSUBROUTINESUIVPROC) phpgl_entry("glUniformSubroutinesuiv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(shadertype), (GLsizei) phpgl_arg_long(count), (const GLuint *) phpgl_arg_ptr(indices));
}

void phpgl_gl40_glgetuniformsubroutineuiv(zval *shadertype, zval *location, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETUNIFORMSUBROUTINEUIVPROC fn = (PFNGLGETUNIFORMSUBROUTINEUIVPROC) phpgl_entry("glGetUniformSubroutineuiv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(shadertype), (GLint) phpgl_arg_long(location), (GLuint *) phpgl_arg_ptr(params));
}

void phpgl_gl40_glgetprogramstageiv(zval *program, zval *shadertype, zval *pname, zval *values)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETPROGRAMSTAGEIVPROC fn = (PFNGLGETPROGRAMSTAGEIVPROC) phpgl_entry("glGetProgramStageiv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLenum) phpgl_arg_long(shadertype), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(values));
}

void phpgl_gl40_glpatchparameteri(zval *pname, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPATCHPARAMETERIPROC fn = (PFNGLPATCHPARAMETERIPROC) phpgl_entry("glPatchParameteri", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (GLint) phpgl_arg_long(value));
}

void phpgl_gl40_glpatchparameterfv(zval *pname, zval *values)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPATCHPARAMETERFVPROC fn = (PFNGLPATCHPARAMETERFVPROC) phpgl_entry("glPatchParameterfv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(pname), (const GLfloat *) phpgl_arg_ptr(values));
}

void phpgl_gl40_glbindtransformfeedback(zval *target, zval *id)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBINDTRANSFORMFEEDBACKPROC fn = (PFNGLBINDTRANSFORMFEEDBACKPROC) phpgl_entry("glBindTransformFeedback", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(id));
}

void phpgl_gl40_gldeletetransformfeedbacks(zval *n, zval *ids)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDELETETRANSFORMFEEDBACKSPROC fn = (PFNGLDELETETRANSFORMFEEDBACKSPROC) phpgl_entry("glDeleteTransformFeedbacks", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (const GLuint *) phpgl_arg_ptr(ids));
}

void phpgl_gl40_glgentransformfeedbacks(zval *n, zval *ids)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGENTRANSFORMFEEDBACKSPROC fn = (PFNGLGENTRANSFORMFEEDBACKSPROC) phpgl_entry("glGenTransformFeedbacks", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (GLuint *) phpgl_arg_ptr(ids));
}

zend_long phpgl_gl40_glistransformfeedback(zval *id)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLISTRANSFORMFEEDBACKPROC fn = (PFNGLISTRANSFORMFEEDBACKPROC) phpgl_entry("glIsTransformFeedback", &slot, 4, 0);

    if (!fn) {
        return 0;
    }

    return fn((GLuint) phpgl_arg_long(id)) ? 1 : 0;
}

void phpgl_gl40_glpausetransformfeedback(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPAUSETRANSFORMFEEDBACKPROC fn = (PFNGLPAUSETRANSFORMFEEDBACKPROC) phpgl_entry("glPauseTransformFeedback", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn();
}

void phpgl_gl40_glresumetransformfeedback(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLRESUMETRANSFORMFEEDBACKPROC fn = (PFNGLRESUMETRANSFORMFEEDBACKPROC) phpgl_entry("glResumeTransformFeedback", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn();
}

void phpgl_gl40_gldrawtransformfeedback(zval *mode, zval *id)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDRAWTRANSFORMFEEDBACKPROC fn = (PFNGLDRAWTRANSFORMFEEDBACKPROC) phpgl_entry("glDrawTransformFeedback", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (GLuint) phpgl_arg_long(id));
}

void phpgl_gl40_gldrawtransformfeedbackstream(zval *mode, zval *id, zval *stream)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC fn = (PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC) phpgl_entry("glDrawTransformFeedbackStream", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(mode), (GLuint) phpgl_arg_long(id), (GLuint) phpgl_arg_long(stream));
}

void phpgl_gl40_glbeginqueryindexed(zval *target, zval *index, zval *id)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBEGINQUERYINDEXEDPROC fn = (PFNGLBEGINQUERYINDEXEDPROC) phpgl_entry("glBeginQueryIndexed", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(index), (GLuint) phpgl_arg_long(id));
}

void phpgl_gl40_glendqueryindexed(zval *target, zval *index)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLENDQUERYINDEXEDPROC fn = (PFNGLENDQUERYINDEXEDPROC) phpgl_entry("glEndQueryIndexed", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(index));
}

void phpgl_gl40_glgetqueryindexediv(zval *target, zval *index, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETQUERYINDEXEDIVPROC fn = (PFNGLGETQUERYINDEXEDIVPROC) phpgl_entry("glGetQueryIndexediv", &slot, 4, 0);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(index), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

