/*
 * gl-41.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/glcorearb.h, GL_VERSION_4_1 (88 prototypes)
 */

#include "gl-41.h"
#include "gl-types.h"
#include "phpgl-bridge.h"
#include "phpgl-support.h"

void phpgl_gl41_glreleaseshadercompiler(void)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLRELEASESHADERCOMPILERPROC fn = (PFNGLRELEASESHADERCOMPILERPROC) phpgl_entry("glReleaseShaderCompiler", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn();
}

void phpgl_gl41_glshaderbinary(zval *count, zval *shaders, zval *binaryFormat, zval *binary, zval *length)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLSHADERBINARYPROC fn = (PFNGLSHADERBINARYPROC) phpgl_entry("glShaderBinary", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(count), (const GLuint *) phpgl_arg_ptr(shaders), (GLenum) phpgl_arg_long(binaryFormat), (const void *) phpgl_arg_ptr(binary), (GLsizei) phpgl_arg_long(length));
}

void phpgl_gl41_glgetshaderprecisionformat(zval *shadertype, zval *precisiontype, zval *range, zval *precision)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETSHADERPRECISIONFORMATPROC fn = (PFNGLGETSHADERPRECISIONFORMATPROC) phpgl_entry("glGetShaderPrecisionFormat", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(shadertype), (GLenum) phpgl_arg_long(precisiontype), (GLint *) phpgl_arg_ptr(range), (GLint *) phpgl_arg_ptr(precision));
}

void phpgl_gl41_gldepthrangef(zval *n, zval *f)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDEPTHRANGEFPROC fn = (PFNGLDEPTHRANGEFPROC) phpgl_entry("glDepthRangef", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLfloat) phpgl_arg_double(n), (GLfloat) phpgl_arg_double(f));
}

void phpgl_gl41_glcleardepthf(zval *d)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLCLEARDEPTHFPROC fn = (PFNGLCLEARDEPTHFPROC) phpgl_entry("glClearDepthf", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLfloat) phpgl_arg_double(d));
}

void phpgl_gl41_glgetprogrambinary(zval *program, zval *bufSize, zval *length, zval *binaryFormat, zval *binary)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETPROGRAMBINARYPROC fn = (PFNGLGETPROGRAMBINARYPROC) phpgl_entry("glGetProgramBinary", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLsizei) phpgl_arg_long(bufSize), (GLsizei *) phpgl_arg_ptr(length), (GLenum *) phpgl_arg_ptr(binaryFormat), (void *) phpgl_arg_ptr(binary));
}

void phpgl_gl41_glprogrambinary(zval *program, zval *binaryFormat, zval *binary, zval *length)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMBINARYPROC fn = (PFNGLPROGRAMBINARYPROC) phpgl_entry("glProgramBinary", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLenum) phpgl_arg_long(binaryFormat), (const void *) phpgl_arg_ptr(binary), (GLsizei) phpgl_arg_long(length));
}

void phpgl_gl41_glprogramparameteri(zval *program, zval *pname, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMPARAMETERIPROC fn = (PFNGLPROGRAMPARAMETERIPROC) phpgl_entry("glProgramParameteri", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLenum) phpgl_arg_long(pname), (GLint) phpgl_arg_long(value));
}

void phpgl_gl41_gluseprogramstages(zval *pipeline, zval *stages, zval *program)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLUSEPROGRAMSTAGESPROC fn = (PFNGLUSEPROGRAMSTAGESPROC) phpgl_entry("glUseProgramStages", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(pipeline), (GLbitfield) phpgl_arg_long(stages), (GLuint) phpgl_arg_long(program));
}

void phpgl_gl41_glactiveshaderprogram(zval *pipeline, zval *program)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLACTIVESHADERPROGRAMPROC fn = (PFNGLACTIVESHADERPROGRAMPROC) phpgl_entry("glActiveShaderProgram", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(pipeline), (GLuint) phpgl_arg_long(program));
}

zend_long phpgl_gl41_glcreateshaderprogramv(zval *type, zval *count, zval *strings)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    char **strv = NULL;
    int strv_n = 0;
    PFNGLCREATESHADERPROGRAMVPROC fn = (PFNGLCREATESHADERPROGRAMVPROC) phpgl_entry("glCreateShaderProgramv", &slot, 4, 1);
    zend_long result;

    if (!fn) {
        return 0;
    }

    strv = phpgl_arg_strv(strings, &strv_n);
    if (phpgl_arg_long(count) > (zend_long) strv_n) {
        php_error_docref(NULL, E_WARNING,
            "glCreateShaderProgramv: count exceeds the number of strings given");
        phpgl_free_strv(strv, strv_n);

        return 0;
    }

    result = (zend_long) fn((GLenum) phpgl_arg_long(type), (GLsizei) phpgl_arg_long(count), (const GLchar *const *) strv);
    phpgl_free_strv(strv, strv_n);

    return result;
}

void phpgl_gl41_glbindprogrampipeline(zval *pipeline)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLBINDPROGRAMPIPELINEPROC fn = (PFNGLBINDPROGRAMPIPELINEPROC) phpgl_entry("glBindProgramPipeline", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(pipeline));
}

void phpgl_gl41_gldeleteprogrampipelines(zval *n, zval *pipelines)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDELETEPROGRAMPIPELINESPROC fn = (PFNGLDELETEPROGRAMPIPELINESPROC) phpgl_entry("glDeleteProgramPipelines", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (const GLuint *) phpgl_arg_ptr(pipelines));
}

void phpgl_gl41_glgenprogrampipelines(zval *n, zval *pipelines)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGENPROGRAMPIPELINESPROC fn = (PFNGLGENPROGRAMPIPELINESPROC) phpgl_entry("glGenProgramPipelines", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLsizei) phpgl_arg_long(n), (GLuint *) phpgl_arg_ptr(pipelines));
}

zend_long phpgl_gl41_glisprogrampipeline(zval *pipeline)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLISPROGRAMPIPELINEPROC fn = (PFNGLISPROGRAMPIPELINEPROC) phpgl_entry("glIsProgramPipeline", &slot, 4, 1);

    if (!fn) {
        return 0;
    }

    return fn((GLuint) phpgl_arg_long(pipeline)) ? 1 : 0;
}

void phpgl_gl41_glgetprogrampipelineiv(zval *pipeline, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETPROGRAMPIPELINEIVPROC fn = (PFNGLGETPROGRAMPIPELINEIVPROC) phpgl_entry("glGetProgramPipelineiv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(pipeline), (GLenum) phpgl_arg_long(pname), (GLint *) phpgl_arg_ptr(params));
}

void phpgl_gl41_glprogramuniform1i(zval *program, zval *location, zval *v0)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM1IPROC fn = (PFNGLPROGRAMUNIFORM1IPROC) phpgl_entry("glProgramUniform1i", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLint) phpgl_arg_long(v0));
}

void phpgl_gl41_glprogramuniform1iv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM1IVPROC fn = (PFNGLPROGRAMUNIFORM1IVPROC) phpgl_entry("glProgramUniform1iv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLint *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform1f(zval *program, zval *location, zval *v0)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM1FPROC fn = (PFNGLPROGRAMUNIFORM1FPROC) phpgl_entry("glProgramUniform1f", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLfloat) phpgl_arg_double(v0));
}

void phpgl_gl41_glprogramuniform1fv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM1FVPROC fn = (PFNGLPROGRAMUNIFORM1FVPROC) phpgl_entry("glProgramUniform1fv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform1d(zval *program, zval *location, zval *v0)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM1DPROC fn = (PFNGLPROGRAMUNIFORM1DPROC) phpgl_entry("glProgramUniform1d", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLdouble) phpgl_arg_double(v0));
}

void phpgl_gl41_glprogramuniform1dv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM1DVPROC fn = (PFNGLPROGRAMUNIFORM1DVPROC) phpgl_entry("glProgramUniform1dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform1ui(zval *program, zval *location, zval *v0)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM1UIPROC fn = (PFNGLPROGRAMUNIFORM1UIPROC) phpgl_entry("glProgramUniform1ui", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLuint) phpgl_arg_long(v0));
}

void phpgl_gl41_glprogramuniform1uiv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM1UIVPROC fn = (PFNGLPROGRAMUNIFORM1UIVPROC) phpgl_entry("glProgramUniform1uiv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLuint *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform2i(zval *program, zval *location, zval *v0, zval *v1)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM2IPROC fn = (PFNGLPROGRAMUNIFORM2IPROC) phpgl_entry("glProgramUniform2i", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLint) phpgl_arg_long(v0), (GLint) phpgl_arg_long(v1));
}

void phpgl_gl41_glprogramuniform2iv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM2IVPROC fn = (PFNGLPROGRAMUNIFORM2IVPROC) phpgl_entry("glProgramUniform2iv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLint *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform2f(zval *program, zval *location, zval *v0, zval *v1)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM2FPROC fn = (PFNGLPROGRAMUNIFORM2FPROC) phpgl_entry("glProgramUniform2f", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLfloat) phpgl_arg_double(v0), (GLfloat) phpgl_arg_double(v1));
}

void phpgl_gl41_glprogramuniform2fv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM2FVPROC fn = (PFNGLPROGRAMUNIFORM2FVPROC) phpgl_entry("glProgramUniform2fv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform2d(zval *program, zval *location, zval *v0, zval *v1)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM2DPROC fn = (PFNGLPROGRAMUNIFORM2DPROC) phpgl_entry("glProgramUniform2d", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLdouble) phpgl_arg_double(v0), (GLdouble) phpgl_arg_double(v1));
}

void phpgl_gl41_glprogramuniform2dv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM2DVPROC fn = (PFNGLPROGRAMUNIFORM2DVPROC) phpgl_entry("glProgramUniform2dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform2ui(zval *program, zval *location, zval *v0, zval *v1)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM2UIPROC fn = (PFNGLPROGRAMUNIFORM2UIPROC) phpgl_entry("glProgramUniform2ui", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLuint) phpgl_arg_long(v0), (GLuint) phpgl_arg_long(v1));
}

void phpgl_gl41_glprogramuniform2uiv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM2UIVPROC fn = (PFNGLPROGRAMUNIFORM2UIVPROC) phpgl_entry("glProgramUniform2uiv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLuint *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform3i(zval *program, zval *location, zval *v0, zval *v1, zval *v2)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM3IPROC fn = (PFNGLPROGRAMUNIFORM3IPROC) phpgl_entry("glProgramUniform3i", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLint) phpgl_arg_long(v0), (GLint) phpgl_arg_long(v1), (GLint) phpgl_arg_long(v2));
}

void phpgl_gl41_glprogramuniform3iv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM3IVPROC fn = (PFNGLPROGRAMUNIFORM3IVPROC) phpgl_entry("glProgramUniform3iv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLint *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform3f(zval *program, zval *location, zval *v0, zval *v1, zval *v2)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM3FPROC fn = (PFNGLPROGRAMUNIFORM3FPROC) phpgl_entry("glProgramUniform3f", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLfloat) phpgl_arg_double(v0), (GLfloat) phpgl_arg_double(v1), (GLfloat) phpgl_arg_double(v2));
}

void phpgl_gl41_glprogramuniform3fv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM3FVPROC fn = (PFNGLPROGRAMUNIFORM3FVPROC) phpgl_entry("glProgramUniform3fv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform3d(zval *program, zval *location, zval *v0, zval *v1, zval *v2)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM3DPROC fn = (PFNGLPROGRAMUNIFORM3DPROC) phpgl_entry("glProgramUniform3d", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLdouble) phpgl_arg_double(v0), (GLdouble) phpgl_arg_double(v1), (GLdouble) phpgl_arg_double(v2));
}

void phpgl_gl41_glprogramuniform3dv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM3DVPROC fn = (PFNGLPROGRAMUNIFORM3DVPROC) phpgl_entry("glProgramUniform3dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform3ui(zval *program, zval *location, zval *v0, zval *v1, zval *v2)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM3UIPROC fn = (PFNGLPROGRAMUNIFORM3UIPROC) phpgl_entry("glProgramUniform3ui", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLuint) phpgl_arg_long(v0), (GLuint) phpgl_arg_long(v1), (GLuint) phpgl_arg_long(v2));
}

void phpgl_gl41_glprogramuniform3uiv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM3UIVPROC fn = (PFNGLPROGRAMUNIFORM3UIVPROC) phpgl_entry("glProgramUniform3uiv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLuint *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform4i(zval *program, zval *location, zval *v0, zval *v1, zval *v2, zval *v3)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM4IPROC fn = (PFNGLPROGRAMUNIFORM4IPROC) phpgl_entry("glProgramUniform4i", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLint) phpgl_arg_long(v0), (GLint) phpgl_arg_long(v1), (GLint) phpgl_arg_long(v2), (GLint) phpgl_arg_long(v3));
}

void phpgl_gl41_glprogramuniform4iv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM4IVPROC fn = (PFNGLPROGRAMUNIFORM4IVPROC) phpgl_entry("glProgramUniform4iv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLint *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform4f(zval *program, zval *location, zval *v0, zval *v1, zval *v2, zval *v3)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM4FPROC fn = (PFNGLPROGRAMUNIFORM4FPROC) phpgl_entry("glProgramUniform4f", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLfloat) phpgl_arg_double(v0), (GLfloat) phpgl_arg_double(v1), (GLfloat) phpgl_arg_double(v2), (GLfloat) phpgl_arg_double(v3));
}

void phpgl_gl41_glprogramuniform4fv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM4FVPROC fn = (PFNGLPROGRAMUNIFORM4FVPROC) phpgl_entry("glProgramUniform4fv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform4d(zval *program, zval *location, zval *v0, zval *v1, zval *v2, zval *v3)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM4DPROC fn = (PFNGLPROGRAMUNIFORM4DPROC) phpgl_entry("glProgramUniform4d", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLdouble) phpgl_arg_double(v0), (GLdouble) phpgl_arg_double(v1), (GLdouble) phpgl_arg_double(v2), (GLdouble) phpgl_arg_double(v3));
}

void phpgl_gl41_glprogramuniform4dv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM4DVPROC fn = (PFNGLPROGRAMUNIFORM4DVPROC) phpgl_entry("glProgramUniform4dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniform4ui(zval *program, zval *location, zval *v0, zval *v1, zval *v2, zval *v3)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM4UIPROC fn = (PFNGLPROGRAMUNIFORM4UIPROC) phpgl_entry("glProgramUniform4ui", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLuint) phpgl_arg_long(v0), (GLuint) phpgl_arg_long(v1), (GLuint) phpgl_arg_long(v2), (GLuint) phpgl_arg_long(v3));
}

void phpgl_gl41_glprogramuniform4uiv(zval *program, zval *location, zval *count, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORM4UIVPROC fn = (PFNGLPROGRAMUNIFORM4UIVPROC) phpgl_entry("glProgramUniform4uiv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (const GLuint *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix2fv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX2FVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX2FVPROC) phpgl_entry("glProgramUniformMatrix2fv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix3fv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX3FVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX3FVPROC) phpgl_entry("glProgramUniformMatrix3fv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix4fv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX4FVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX4FVPROC) phpgl_entry("glProgramUniformMatrix4fv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix2dv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX2DVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX2DVPROC) phpgl_entry("glProgramUniformMatrix2dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix3dv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX3DVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX3DVPROC) phpgl_entry("glProgramUniformMatrix3dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix4dv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX4DVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX4DVPROC) phpgl_entry("glProgramUniformMatrix4dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix2x3fv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC) phpgl_entry("glProgramUniformMatrix2x3fv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix3x2fv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC) phpgl_entry("glProgramUniformMatrix3x2fv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix2x4fv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC) phpgl_entry("glProgramUniformMatrix2x4fv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix4x2fv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC) phpgl_entry("glProgramUniformMatrix4x2fv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix3x4fv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC) phpgl_entry("glProgramUniformMatrix3x4fv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix4x3fv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC) phpgl_entry("glProgramUniformMatrix4x3fv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLfloat *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix2x3dv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC) phpgl_entry("glProgramUniformMatrix2x3dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix3x2dv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC) phpgl_entry("glProgramUniformMatrix3x2dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix2x4dv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC) phpgl_entry("glProgramUniformMatrix2x4dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix4x2dv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC) phpgl_entry("glProgramUniformMatrix4x2dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix3x4dv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC) phpgl_entry("glProgramUniformMatrix3x4dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glprogramuniformmatrix4x3dv(zval *program, zval *location, zval *count, zval *transpose, zval *value)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC fn = (PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC) phpgl_entry("glProgramUniformMatrix4x3dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(program), (GLint) phpgl_arg_long(location), (GLsizei) phpgl_arg_long(count), (GLboolean) phpgl_arg_bool(transpose), (const GLdouble *) phpgl_arg_ptr(value));
}

void phpgl_gl41_glvalidateprogrampipeline(zval *pipeline)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVALIDATEPROGRAMPIPELINEPROC fn = (PFNGLVALIDATEPROGRAMPIPELINEPROC) phpgl_entry("glValidateProgramPipeline", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(pipeline));
}

void phpgl_gl41_glgetprogrampipelineinfolog(zval *pipeline, zval *bufSize, zval *length, zval *infoLog)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETPROGRAMPIPELINEINFOLOGPROC fn = (PFNGLGETPROGRAMPIPELINEINFOLOGPROC) phpgl_entry("glGetProgramPipelineInfoLog", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(pipeline), (GLsizei) phpgl_arg_long(bufSize), (GLsizei *) phpgl_arg_ptr(length), (GLchar *) phpgl_arg_ptr(infoLog));
}

void phpgl_gl41_glvertexattribl1d(zval *index, zval *x)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBL1DPROC fn = (PFNGLVERTEXATTRIBL1DPROC) phpgl_entry("glVertexAttribL1d", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLdouble) phpgl_arg_double(x));
}

void phpgl_gl41_glvertexattribl2d(zval *index, zval *x, zval *y)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBL2DPROC fn = (PFNGLVERTEXATTRIBL2DPROC) phpgl_entry("glVertexAttribL2d", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLdouble) phpgl_arg_double(x), (GLdouble) phpgl_arg_double(y));
}

void phpgl_gl41_glvertexattribl3d(zval *index, zval *x, zval *y, zval *z)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBL3DPROC fn = (PFNGLVERTEXATTRIBL3DPROC) phpgl_entry("glVertexAttribL3d", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLdouble) phpgl_arg_double(x), (GLdouble) phpgl_arg_double(y), (GLdouble) phpgl_arg_double(z));
}

void phpgl_gl41_glvertexattribl4d(zval *index, zval *x, zval *y, zval *z, zval *w)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBL4DPROC fn = (PFNGLVERTEXATTRIBL4DPROC) phpgl_entry("glVertexAttribL4d", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLdouble) phpgl_arg_double(x), (GLdouble) phpgl_arg_double(y), (GLdouble) phpgl_arg_double(z), (GLdouble) phpgl_arg_double(w));
}

void phpgl_gl41_glvertexattribl1dv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBL1DVPROC fn = (PFNGLVERTEXATTRIBL1DVPROC) phpgl_entry("glVertexAttribL1dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLdouble *) phpgl_arg_ptr(v));
}

void phpgl_gl41_glvertexattribl2dv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBL2DVPROC fn = (PFNGLVERTEXATTRIBL2DVPROC) phpgl_entry("glVertexAttribL2dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLdouble *) phpgl_arg_ptr(v));
}

void phpgl_gl41_glvertexattribl3dv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBL3DVPROC fn = (PFNGLVERTEXATTRIBL3DVPROC) phpgl_entry("glVertexAttribL3dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLdouble *) phpgl_arg_ptr(v));
}

void phpgl_gl41_glvertexattribl4dv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBL4DVPROC fn = (PFNGLVERTEXATTRIBL4DVPROC) phpgl_entry("glVertexAttribL4dv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLdouble *) phpgl_arg_ptr(v));
}

void phpgl_gl41_glvertexattriblpointer(zval *index, zval *size, zval *type, zval *stride, zval *pointer)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVERTEXATTRIBLPOINTERPROC fn = (PFNGLVERTEXATTRIBLPOINTERPROC) phpgl_entry("glVertexAttribLPointer", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLint) phpgl_arg_long(size), (GLenum) phpgl_arg_long(type), (GLsizei) phpgl_arg_long(stride), (const void *) phpgl_arg_ptr(pointer));
}

void phpgl_gl41_glgetvertexattribldv(zval *index, zval *pname, zval *params)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETVERTEXATTRIBLDVPROC fn = (PFNGLGETVERTEXATTRIBLDVPROC) phpgl_entry("glGetVertexAttribLdv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLenum) phpgl_arg_long(pname), (GLdouble *) phpgl_arg_ptr(params));
}

void phpgl_gl41_glviewportarrayv(zval *first, zval *count, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVIEWPORTARRAYVPROC fn = (PFNGLVIEWPORTARRAYVPROC) phpgl_entry("glViewportArrayv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(first), (GLsizei) phpgl_arg_long(count), (const GLfloat *) phpgl_arg_ptr(v));
}

void phpgl_gl41_glviewportindexedf(zval *index, zval *x, zval *y, zval *w, zval *h)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVIEWPORTINDEXEDFPROC fn = (PFNGLVIEWPORTINDEXEDFPROC) phpgl_entry("glViewportIndexedf", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLfloat) phpgl_arg_double(x), (GLfloat) phpgl_arg_double(y), (GLfloat) phpgl_arg_double(w), (GLfloat) phpgl_arg_double(h));
}

void phpgl_gl41_glviewportindexedfv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLVIEWPORTINDEXEDFVPROC fn = (PFNGLVIEWPORTINDEXEDFVPROC) phpgl_entry("glViewportIndexedfv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLfloat *) phpgl_arg_ptr(v));
}

void phpgl_gl41_glscissorarrayv(zval *first, zval *count, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLSCISSORARRAYVPROC fn = (PFNGLSCISSORARRAYVPROC) phpgl_entry("glScissorArrayv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(first), (GLsizei) phpgl_arg_long(count), (const GLint *) phpgl_arg_ptr(v));
}

void phpgl_gl41_glscissorindexed(zval *index, zval *left, zval *bottom, zval *width, zval *height)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLSCISSORINDEXEDPROC fn = (PFNGLSCISSORINDEXEDPROC) phpgl_entry("glScissorIndexed", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLint) phpgl_arg_long(left), (GLint) phpgl_arg_long(bottom), (GLsizei) phpgl_arg_long(width), (GLsizei) phpgl_arg_long(height));
}

void phpgl_gl41_glscissorindexedv(zval *index, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLSCISSORINDEXEDVPROC fn = (PFNGLSCISSORINDEXEDVPROC) phpgl_entry("glScissorIndexedv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (const GLint *) phpgl_arg_ptr(v));
}

void phpgl_gl41_gldepthrangearrayv(zval *first, zval *count, zval *v)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDEPTHRANGEARRAYVPROC fn = (PFNGLDEPTHRANGEARRAYVPROC) phpgl_entry("glDepthRangeArrayv", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(first), (GLsizei) phpgl_arg_long(count), (const GLdouble *) phpgl_arg_ptr(v));
}

void phpgl_gl41_gldepthrangeindexed(zval *index, zval *n, zval *f)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLDEPTHRANGEINDEXEDPROC fn = (PFNGLDEPTHRANGEINDEXEDPROC) phpgl_entry("glDepthRangeIndexed", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLuint) phpgl_arg_long(index), (GLdouble) phpgl_arg_double(n), (GLdouble) phpgl_arg_double(f));
}

void phpgl_gl41_glgetfloati_v(zval *target, zval *index, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETFLOATI_VPROC fn = (PFNGLGETFLOATI_VPROC) phpgl_entry("glGetFloati_v", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(index), (GLfloat *) phpgl_arg_ptr(data));
}

void phpgl_gl41_glgetdoublei_v(zval *target, zval *index, zval *data)
{
    static phpgl_slot slot = PHPGL_SLOT_INIT;
    PFNGLGETDOUBLEI_VPROC fn = (PFNGLGETDOUBLEI_VPROC) phpgl_entry("glGetDoublei_v", &slot, 4, 1);

    if (!fn) {
        return;
    }

    fn((GLenum) phpgl_arg_long(target), (GLuint) phpgl_arg_long(index), (GLdouble *) phpgl_arg_ptr(data));
}

