/*
 * phpgl-registry.h — every bound entry point and the version it first appeared in.
 *
 * GENERATED by scripts/gen-gl-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/*.h and OpenGL.framework/Headers
 */

#ifndef PHPGL_REGISTRY_H
#define PHPGL_REGISTRY_H

typedef struct {
    const char *name;
    int major;
    int minor;
} phpgl_entry_row;

extern const phpgl_entry_row phpgl_entry_table[];
extern const int phpgl_entry_table_size;

#endif /* PHPGL_REGISTRY_H */
