// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace OpenGL\GL\GL32;

class GL32
{
    public static function glDrawElementsBaseVertex(int mode, int count, int type, int indices, int basevertex) -> void
    {
        gl32_gldrawelementsbasevertex(mode, count, type, indices, basevertex);
    }

    public static function glDrawRangeElementsBaseVertex(int mode, int start, int end, int count, int type, int indices, int basevertex) -> void
    {
        gl32_gldrawrangeelementsbasevertex(mode, start, end, count, type, indices, basevertex);
    }

    public static function glDrawElementsInstancedBaseVertex(int mode, int count, int type, int indices, int instancecount, int basevertex) -> void
    {
        gl32_gldrawelementsinstancedbasevertex(mode, count, type, indices, instancecount, basevertex);
    }

    public static function glMultiDrawElementsBaseVertex(int mode, int count, int type, int indices, int drawcount, int basevertex) -> void
    {
        gl32_glmultidrawelementsbasevertex(mode, count, type, indices, drawcount, basevertex);
    }

    public static function glProvokingVertex(int mode) -> void
    {
        gl32_glprovokingvertex(mode);
    }

    public static function glFenceSync(int condition, int flags) -> int
    {
        return gl32_glfencesync(condition, flags);
    }

    public static function glIsSync(int sync) -> bool
    {
        int r;

        let r = gl32_glissync(sync);

        return r == 1;
    }

    public static function glDeleteSync(int sync) -> void
    {
        gl32_gldeletesync(sync);
    }

    public static function glClientWaitSync(int sync, int flags, int timeout) -> int
    {
        return gl32_glclientwaitsync(sync, flags, timeout);
    }

    public static function glWaitSync(int sync, int flags, int timeout) -> void
    {
        gl32_glwaitsync(sync, flags, timeout);
    }

    public static function glGetInteger64v(int pname, int data) -> void
    {
        gl32_glgetinteger64v(pname, data);
    }

    public static function glGetSynciv(int sync, int pname, int count, int length, int values) -> void
    {
        gl32_glgetsynciv(sync, pname, count, length, values);
    }

    public static function glGetInteger64i_v(int target, int index, int data) -> void
    {
        gl32_glgetinteger64i_v(target, index, data);
    }

    public static function glGetBufferParameteri64v(int target, int pname, int params) -> void
    {
        gl32_glgetbufferparameteri64v(target, pname, params);
    }

    public static function glFramebufferTexture(int target, int attachment, int texture, int level) -> void
    {
        gl32_glframebuffertexture(target, attachment, texture, level);
    }

    public static function glTexImage2DMultisample(int target, int samples, int internalformat, int width, int height, bool fixedsamplelocations) -> void
    {
        gl32_glteximage2dmultisample(target, samples, internalformat, width, height, fixedsamplelocations);
    }

    public static function glTexImage3DMultisample(int target, int samples, int internalformat, int width, int height, int depth, bool fixedsamplelocations) -> void
    {
        gl32_glteximage3dmultisample(target, samples, internalformat, width, height, depth, fixedsamplelocations);
    }

    public static function glGetMultisamplefv(int pname, int index, int val) -> void
    {
        gl32_glgetmultisamplefv(pname, index, val);
    }

    public static function glSampleMaski(int maskNumber, int mask) -> void
    {
        gl32_glsamplemaski(maskNumber, mask);
    }
}
