// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace OpenGL\GL\GL13;

class GL13
{
    public static function glActiveTexture(int texture) -> void
    {
        gl13_glactivetexture(texture);
    }

    public static function glSampleCoverage(double value, bool invert) -> void
    {
        gl13_glsamplecoverage(value, invert);
    }

    public static function glCompressedTexImage3D(int target, int level, int internalformat, int width, int height, int depth, int border, int imageSize, int data) -> void
    {
        gl13_glcompressedteximage3d(target, level, internalformat, width, height, depth, border, imageSize, data);
    }

    public static function glCompressedTexImage2D(int target, int level, int internalformat, int width, int height, int border, int imageSize, int data) -> void
    {
        gl13_glcompressedteximage2d(target, level, internalformat, width, height, border, imageSize, data);
    }

    public static function glCompressedTexImage1D(int target, int level, int internalformat, int width, int border, int imageSize, int data) -> void
    {
        gl13_glcompressedteximage1d(target, level, internalformat, width, border, imageSize, data);
    }

    public static function glCompressedTexSubImage3D(int target, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int imageSize, int data) -> void
    {
        gl13_glcompressedtexsubimage3d(target, level, xoffset, yoffset, zoffset, width, height, depth, format, imageSize, data);
    }

    public static function glCompressedTexSubImage2D(int target, int level, int xoffset, int yoffset, int width, int height, int format, int imageSize, int data) -> void
    {
        gl13_glcompressedtexsubimage2d(target, level, xoffset, yoffset, width, height, format, imageSize, data);
    }

    public static function glCompressedTexSubImage1D(int target, int level, int xoffset, int width, int format, int imageSize, int data) -> void
    {
        gl13_glcompressedtexsubimage1d(target, level, xoffset, width, format, imageSize, data);
    }

    public static function glGetCompressedTexImage(int target, int level, int img) -> void
    {
        gl13_glgetcompressedteximage(target, level, img);
    }
}
