// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace OpenGL\GL\GL10;

class GL10
{
    public static function glCullFace(int mode) -> void
    {
        gl10_glcullface(mode);
    }

    public static function glFrontFace(int mode) -> void
    {
        gl10_glfrontface(mode);
    }

    public static function glHint(int target, int mode) -> void
    {
        gl10_glhint(target, mode);
    }

    public static function glLineWidth(double width) -> void
    {
        gl10_gllinewidth(width);
    }

    public static function glPointSize(double size) -> void
    {
        gl10_glpointsize(size);
    }

    public static function glPolygonMode(int face, int mode) -> void
    {
        gl10_glpolygonmode(face, mode);
    }

    public static function glScissor(int x, int y, int width, int height) -> void
    {
        gl10_glscissor(x, y, width, height);
    }

    public static function glTexParameterf(int target, int pname, double param) -> void
    {
        gl10_gltexparameterf(target, pname, param);
    }

    public static function glTexParameterfv(int target, int pname, int params) -> void
    {
        gl10_gltexparameterfv(target, pname, params);
    }

    public static function glTexParameteri(int target, int pname, int param) -> void
    {
        gl10_gltexparameteri(target, pname, param);
    }

    public static function glTexParameteriv(int target, int pname, int params) -> void
    {
        gl10_gltexparameteriv(target, pname, params);
    }

    public static function glTexImage1D(int target, int level, int internalformat, int width, int border, int format, int type, int pixels) -> void
    {
        gl10_glteximage1d(target, level, internalformat, width, border, format, type, pixels);
    }

    public static function glTexImage2D(int target, int level, int internalformat, int width, int height, int border, int format, int type, int pixels) -> void
    {
        gl10_glteximage2d(target, level, internalformat, width, height, border, format, type, pixels);
    }

    public static function glDrawBuffer(int buf) -> void
    {
        gl10_gldrawbuffer(buf);
    }

    public static function glClear(int mask) -> void
    {
        gl10_glclear(mask);
    }

    public static function glClearColor(double red, double green, double blue, double alpha) -> void
    {
        gl10_glclearcolor(red, green, blue, alpha);
    }

    public static function glClearStencil(int s) -> void
    {
        gl10_glclearstencil(s);
    }

    public static function glClearDepth(double depth) -> void
    {
        gl10_glcleardepth(depth);
    }

    public static function glStencilMask(int mask) -> void
    {
        gl10_glstencilmask(mask);
    }

    public static function glColorMask(bool red, bool green, bool blue, bool alpha) -> void
    {
        gl10_glcolormask(red, green, blue, alpha);
    }

    public static function glDepthMask(bool flag) -> void
    {
        gl10_gldepthmask(flag);
    }

    public static function glDisable(int cap) -> void
    {
        gl10_gldisable(cap);
    }

    public static function glEnable(int cap) -> void
    {
        gl10_glenable(cap);
    }

    public static function glFinish() -> void
    {
        gl10_glfinish();
    }

    public static function glFlush() -> void
    {
        gl10_glflush();
    }

    public static function glBlendFunc(int sfactor, int dfactor) -> void
    {
        gl10_glblendfunc(sfactor, dfactor);
    }

    public static function glLogicOp(int opcode) -> void
    {
        gl10_gllogicop(opcode);
    }

    public static function glStencilFunc(int func, int ref, int mask) -> void
    {
        gl10_glstencilfunc(func, ref, mask);
    }

    public static function glStencilOp(int fail, int zfail, int zpass) -> void
    {
        gl10_glstencilop(fail, zfail, zpass);
    }

    public static function glDepthFunc(int func) -> void
    {
        gl10_gldepthfunc(func);
    }

    public static function glPixelStoref(int pname, double param) -> void
    {
        gl10_glpixelstoref(pname, param);
    }

    public static function glPixelStorei(int pname, int param) -> void
    {
        gl10_glpixelstorei(pname, param);
    }

    public static function glReadBuffer(int src) -> void
    {
        gl10_glreadbuffer(src);
    }

    public static function glReadPixels(int x, int y, int width, int height, int format, int type, int pixels) -> void
    {
        gl10_glreadpixels(x, y, width, height, format, type, pixels);
    }

    public static function glGetBooleanv(int pname, int data) -> void
    {
        gl10_glgetbooleanv(pname, data);
    }

    public static function glGetDoublev(int pname, int data) -> void
    {
        gl10_glgetdoublev(pname, data);
    }

    public static function glGetError() -> int
    {
        return gl10_glgeterror();
    }

    public static function glGetFloatv(int pname, int data) -> void
    {
        gl10_glgetfloatv(pname, data);
    }

    public static function glGetIntegerv(int pname, int data) -> void
    {
        gl10_glgetintegerv(pname, data);
    }

    public static function glGetString(int name) -> var
    {
        var result;

        let result = gl10_glgetstring(name);

        return result;
    }

    public static function glGetTexImage(int target, int level, int format, int type, int pixels) -> void
    {
        gl10_glgetteximage(target, level, format, type, pixels);
    }

    public static function glGetTexParameterfv(int target, int pname, int params) -> void
    {
        gl10_glgettexparameterfv(target, pname, params);
    }

    public static function glGetTexParameteriv(int target, int pname, int params) -> void
    {
        gl10_glgettexparameteriv(target, pname, params);
    }

    public static function glGetTexLevelParameterfv(int target, int level, int pname, int params) -> void
    {
        gl10_glgettexlevelparameterfv(target, level, pname, params);
    }

    public static function glGetTexLevelParameteriv(int target, int level, int pname, int params) -> void
    {
        gl10_glgettexlevelparameteriv(target, level, pname, params);
    }

    public static function glIsEnabled(int cap) -> bool
    {
        int r;

        let r = gl10_glisenabled(cap);

        return r == 1;
    }

    public static function glDepthRange(double n, double f) -> void
    {
        gl10_gldepthrange(n, f);
    }

    public static function glViewport(int x, int y, int width, int height) -> void
    {
        gl10_glviewport(x, y, width, height);
    }
}
